/** Programmatic blog post definitions — auto-generated from live data */

export interface BlogPostDef {
  slug: string;
  title: string;
  description: string;
  indicatorId: string;
  count: number;         // top N countries to feature
  direction: 'top' | 'bottom';
  intro: string;         // template — {year}, {count}, {#1}, {#1_value}, etc. filled at render
  category: string;
}

export const BLOG_POSTS: BlogPostDef[] = [
  // ── ECONOMY: GDP ────────────────────────────────────────
  {
    slug: 'richest-countries-in-the-world',
    title: 'Richest Countries in the World by GDP',
    description: 'The top 25 richest countries in the world ranked by GDP (nominal USD). Updated with the latest IMF data.',
    indicatorId: 'IMF.NGDPD',
    count: 25,
    direction: 'top',
    intro: 'The global economy in {year} is dominated by a handful of powerhouses. Here are the {count} richest countries in the world by gross domestic product (nominal USD), based on IMF World Economic Outlook data.',
    category: 'Economy',
  },
  {
    slug: 'smallest-economies-in-the-world',
    title: 'Smallest Economies in the World by GDP',
    description: 'The 25 smallest economies ranked by nominal GDP. Microstates, island nations, and developing countries.',
    indicatorId: 'IMF.NGDPD',
    count: 25,
    direction: 'bottom',
    intro: 'While the global economy is worth over $100 trillion, some nations produce remarkably little. Here are the {count} smallest economies in {year} by nominal GDP.',
    category: 'Economy',
  },
  {
    slug: 'highest-gdp-per-capita',
    title: 'Countries with the Highest GDP per Capita',
    description: 'Top 25 countries ranked by GDP per capita (nominal USD). A measure of individual economic output and wealth.',
    indicatorId: 'IMF.NGDPDPC',
    count: 25,
    direction: 'top',
    intro: 'GDP per capita is one of the best proxies for individual economic output and living standards. Here are the {count} countries with the highest GDP per capita in {year}.',
    category: 'Economy',
  },
  {
    slug: 'poorest-countries-in-the-world',
    title: 'Poorest Countries in the World by GDP per Capita',
    description: 'The 25 poorest countries ranked by GDP per capita. Economic development challenges and extreme poverty.',
    indicatorId: 'IMF.NGDPDPC',
    count: 25,
    direction: 'bottom',
    intro: 'GDP per capita reveals stark global inequality. Here are the {count} poorest countries in {year}, where economic output per person remains critically low.',
    category: 'Economy',
  },
  {
    slug: 'largest-economies-by-ppp',
    title: 'Largest Economies by GDP (PPP)',
    description: 'Top 25 countries ranked by purchasing power parity GDP. A fairer comparison of economic size.',
    indicatorId: 'IMF.PPPGDP',
    count: 25,
    direction: 'top',
    intro: 'Purchasing power parity adjusts for price differences across countries, giving a fairer picture of economic size. Here are the {count} largest economies by PPP in {year}.',
    category: 'Economy',
  },
  {
    slug: 'highest-gdp-per-capita-ppp',
    title: 'Countries with the Highest GDP per Capita (PPP)',
    description: 'Top 25 countries by GDP per capita adjusted for purchasing power. The best measure of living standards.',
    indicatorId: 'IMF.PPPPC',
    count: 25,
    direction: 'top',
    intro: 'GDP per capita PPP is the gold standard for comparing living standards. Here are the {count} countries where purchasing power is highest in {year}.',
    category: 'Economy',
  },

  // ── ECONOMY: GROWTH ─────────────────────────────────────
  {
    slug: 'fastest-growing-economies',
    title: 'Fastest Growing Economies in the World',
    description: 'Top 25 countries by real GDP growth rate. Emerging markets and economic expansion leaders.',
    indicatorId: 'IMF.NGDP_RPCH',
    count: 25,
    direction: 'top',
    intro: 'While advanced economies grow steadily, some nations are expanding at remarkable speed. Here are the {count} fastest-growing economies in {year}.',
    category: 'Economy',
  },
  {
    slug: 'slowest-growing-economies',
    title: 'Slowest Growing and Shrinking Economies',
    description: 'The 25 countries with the lowest GDP growth — recessions, contractions, and economic decline.',
    indicatorId: 'IMF.NGDP_RPCH',
    count: 25,
    direction: 'bottom',
    intro: 'Not every economy is growing. These {count} countries face the weakest or most negative GDP growth rates in {year} — many in outright contraction.',
    category: 'Economy',
  },

  // ── ECONOMY: INFLATION ──────────────────────────────────
  {
    slug: 'countries-with-highest-inflation',
    title: 'Countries with the Highest Inflation Rates',
    description: 'Top 25 countries with the highest consumer price inflation. Hyperinflation, causes, and trends.',
    indicatorId: 'IMF.PCPIPCH',
    count: 25,
    direction: 'top',
    intro: 'Inflation erodes purchasing power and can destabilize economies. Here are the {count} countries with the highest inflation rates in {year}, based on IMF consumer price data.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-inflation',
    title: 'Countries with the Lowest Inflation — and Deflation',
    description: 'The 25 countries with the lowest inflation or deflation. Price stability and monetary policy.',
    indicatorId: 'IMF.PCPIPCH',
    count: 25,
    direction: 'bottom',
    intro: 'Low inflation or outright deflation can signal economic weakness or tight monetary policy. Here are the {count} countries with the lowest price changes in {year}.',
    category: 'Economy',
  },

  // ── ECONOMY: UNEMPLOYMENT ───────────────────────────────
  {
    slug: 'countries-with-highest-unemployment',
    title: 'Countries with the Highest Unemployment Rates',
    description: 'The 25 countries with the highest unemployment rates. Labor market challenges worldwide.',
    indicatorId: 'IMF.LUR',
    count: 25,
    direction: 'top',
    intro: 'High unemployment reflects deep structural and economic challenges. These {count} countries have the highest unemployment rates in {year}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-unemployment',
    title: 'Countries with the Lowest Unemployment Rates',
    description: 'Top 25 countries with the lowest unemployment. Full employment economies and labor market analysis.',
    indicatorId: 'IMF.LUR',
    count: 25,
    direction: 'bottom',
    intro: 'Low unemployment signals a healthy, productive economy. Here are the {count} countries with the lowest unemployment rates in {year}.',
    category: 'Economy',
  },

  // ── ECONOMY: DEBT & FISCAL ──────────────────────────────
  {
    slug: 'countries-with-highest-debt-to-gdp',
    title: 'Countries with the Highest Government Debt-to-GDP Ratio',
    description: 'Top 25 countries ranked by government gross debt as a percentage of GDP. Fiscal sustainability analysis.',
    indicatorId: 'IMF.GGXWDG_NGDP',
    count: 25,
    direction: 'top',
    intro: 'Government debt is a critical measure of fiscal health. Here are the {count} countries with the highest debt-to-GDP ratios in {year}, based on IMF data.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-debt-to-gdp',
    title: 'Countries with the Lowest Government Debt',
    description: 'The 25 countries with the lowest government debt relative to GDP. Fiscal conservatives and resource-rich nations.',
    indicatorId: 'IMF.GGXWDG_NGDP',
    count: 25,
    direction: 'bottom',
    intro: 'Some countries manage to keep government debt remarkably low. Here are the {count} most fiscally conservative nations in {year}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-largest-current-account-surplus',
    title: 'Countries with the Largest Current Account Surplus',
    description: 'Top 25 countries by current account balance. Trade surpluses and capital flows.',
    indicatorId: 'IMF.BCA_NGDPD',
    count: 25,
    direction: 'top',
    intro: 'A current account surplus means a country exports more than it imports. Here are the {count} countries running the largest surpluses in {year}.',
    category: 'Economy',
  },

  // ── ECONOMY: TRADE ──────────────────────────────────────
  {
    slug: 'most-trade-open-economies',
    title: 'Most Trade-Open Economies in the World',
    description: 'Top 25 countries by trade as a percentage of GDP. Globalization and economic openness.',
    indicatorId: 'NE.TRD.GNFS.ZS',
    count: 25,
    direction: 'top',
    intro: 'Trade openness measures how integrated an economy is with the rest of the world. Here are the {count} most trade-dependent economies in {year}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-most-fdi',
    title: 'Countries Attracting the Most Foreign Direct Investment',
    description: 'Top 25 countries by FDI inflows as a percentage of GDP. Investment destinations and capital flows.',
    indicatorId: 'BX.KLT.DINV.WD.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Foreign direct investment signals confidence in an economy. Here are the {count} countries attracting the most FDI relative to GDP in {year}.',
    category: 'Economy',
  },

  // ── DEMOGRAPHICS ────────────────────────────────────────
  {
    slug: 'most-populated-countries',
    title: 'Most Populated Countries in the World',
    description: 'The 25 most populated countries ranked by total population. Demographics, trends, and projections.',
    indicatorId: 'SP.POP.TOTL',
    count: 25,
    direction: 'top',
    intro: 'Over 8 billion people live on Earth. Here are the {count} most populated countries in {year}, together accounting for the vast majority of the global population.',
    category: 'Demographics',
  },
  {
    slug: 'least-populated-countries',
    title: 'Least Populated Countries in the World',
    description: 'The 25 smallest countries by population. Microstates, island nations, and remote territories.',
    indicatorId: 'SP.POP.TOTL',
    count: 25,
    direction: 'bottom',
    intro: 'While India and China each hold over a billion people, some nations have populations smaller than a single city. Here are the {count} least populated countries in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'fastest-growing-populations',
    title: 'Countries with the Fastest Growing Populations',
    description: 'Top 25 countries by annual population growth rate. Demographic booms and migration trends.',
    indicatorId: 'SP.POP.GROW',
    count: 25,
    direction: 'top',
    intro: 'Some countries are experiencing rapid demographic expansion driven by high birth rates and migration. Here are the {count} fastest-growing populations in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'shrinking-populations',
    title: 'Countries with Shrinking Populations',
    description: 'The 25 countries losing population fastest. Demographic decline, aging, and emigration.',
    indicatorId: 'SP.POP.GROW',
    count: 25,
    direction: 'bottom',
    intro: 'Aging societies, low birth rates, and emigration are causing populations to shrink. These {count} countries face the steepest demographic decline in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'most-urbanized-countries',
    title: 'Most Urbanized Countries in the World',
    description: 'Top 25 countries by urban population percentage. Urbanization trends and city growth.',
    indicatorId: 'SP.URB.TOTL.IN.ZS',
    count: 25,
    direction: 'top',
    intro: 'Urbanization is one of the defining trends of modern civilization. Here are the {count} most urbanized countries in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'oldest-populations-in-the-world',
    title: 'Countries with the Oldest Populations',
    description: 'Top 25 countries by share of population aged 65+. Aging societies and pension challenges.',
    indicatorId: 'SP.POP.65UP.TO.ZS',
    count: 25,
    direction: 'top',
    intro: 'An aging population strains pension systems, healthcare, and economic growth. Here are the {count} countries with the largest share of people aged 65+ in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'highest-fertility-rate-countries',
    title: 'Countries with the Highest Fertility Rates',
    description: 'Top 25 countries by total fertility rate. Birth rates, demographics, and population growth.',
    indicatorId: 'SP.DYN.TFRT.IN',
    count: 25,
    direction: 'top',
    intro: 'High fertility rates drive rapid population growth. Here are the {count} countries with the highest birth rates in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'lowest-fertility-rate-countries',
    title: 'Countries with the Lowest Fertility Rates',
    description: 'The 25 countries with the lowest birth rates. Below-replacement fertility and population decline.',
    indicatorId: 'SP.DYN.TFRT.IN',
    count: 25,
    direction: 'bottom',
    intro: 'When fertility drops below the replacement rate of 2.1, populations eventually shrink. These {count} countries have the lowest fertility rates in {year}.',
    category: 'Demographics',
  },

  // ── HEALTH ──────────────────────────────────────────────
  {
    slug: 'highest-life-expectancy-countries',
    title: 'Countries with the Highest Life Expectancy',
    description: 'Top 25 countries where people live the longest. Life expectancy data from the World Bank.',
    indicatorId: 'SP.DYN.LE00.IN',
    count: 25,
    direction: 'top',
    intro: 'Life expectancy at birth is a key measure of population health and development. Here are the {count} countries where people live the longest in {year}.',
    category: 'Health',
  },
  {
    slug: 'lowest-life-expectancy-countries',
    title: 'Countries with the Lowest Life Expectancy',
    description: 'The 25 countries with the lowest life expectancy at birth. Health challenges and development gaps.',
    indicatorId: 'SP.DYN.LE00.IN',
    count: 25,
    direction: 'bottom',
    intro: 'Life expectancy remains starkly unequal across the world. These {count} countries face the greatest health and development challenges in {year}.',
    category: 'Health',
  },
  {
    slug: 'countries-with-highest-infant-mortality',
    title: 'Countries with the Highest Infant Mortality Rates',
    description: 'The 25 countries where the most children die before age 5. Child health and development.',
    indicatorId: 'SH.DYN.MORT',
    count: 25,
    direction: 'top',
    intro: 'Infant mortality is one of the starkest indicators of development. These {count} countries have the highest under-5 mortality rates in {year}.',
    category: 'Health',
  },
  {
    slug: 'countries-with-highest-health-spending',
    title: 'Countries that Spend the Most on Healthcare',
    description: 'Top 25 countries by health expenditure as a share of GDP. Healthcare investment and outcomes.',
    indicatorId: 'SH.XPD.CHEX.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Healthcare spending as a share of GDP varies enormously. Here are the {count} countries investing the most in health in {year}.',
    category: 'Health',
  },

  // ── EDUCATION ───────────────────────────────────────────
  {
    slug: 'most-educated-countries',
    title: 'Most Educated Countries — Tertiary Enrollment Rates',
    description: 'Top 25 countries by tertiary education enrollment rate. Higher education access worldwide.',
    indicatorId: 'SE.TER.ENRR',
    count: 25,
    direction: 'top',
    intro: 'Access to higher education varies enormously. Here are the {count} countries with the highest tertiary enrollment rates in {year}.',
    category: 'Education',
  },
  {
    slug: 'countries-with-highest-education-spending',
    title: 'Countries that Spend the Most on Education',
    description: 'Top 25 countries by education expenditure as a percentage of GDP. Public investment in education.',
    indicatorId: 'SE.XPD.TOTL.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Education spending reflects a nation\'s investment in its future. Here are the {count} countries that dedicate the highest share of GDP to education in {year}.',
    category: 'Education',
  },
  {
    slug: 'countries-with-lowest-literacy-rates',
    title: 'Countries with the Lowest Literacy Rates',
    description: 'The 25 countries where literacy is lowest. Education gaps and development challenges.',
    indicatorId: 'SE.ADT.LITR.ZS',
    count: 25,
    direction: 'bottom',
    intro: 'Literacy is foundational to economic participation and human development. These {count} countries face the greatest literacy challenges in {year}.',
    category: 'Education',
  },

  // ── ENVIRONMENT ─────────────────────────────────────────
  {
    slug: 'countries-with-highest-co2-emissions',
    title: 'Countries with the Highest CO₂ Emissions per Capita',
    description: 'Top 25 countries ranked by carbon dioxide emissions per person. Climate change and emissions data.',
    indicatorId: 'EN.GHG.CO2.PC.CE.AR5',
    count: 25,
    direction: 'top',
    intro: 'Per capita CO₂ emissions reveal which countries contribute most to climate change relative to their population. Here are the {count} highest emitters in {year}.',
    category: 'Environment',
  },
  {
    slug: 'countries-with-most-renewable-energy',
    title: 'Countries with the Most Renewable Energy',
    description: 'Top 25 countries by renewable energy consumption as a share of total energy. Green energy leaders.',
    indicatorId: 'EG.FEC.RNEW.ZS',
    count: 25,
    direction: 'top',
    intro: 'The transition to renewable energy is a defining challenge of our era. Here are the {count} countries leading the way in renewable energy consumption in {year}.',
    category: 'Environment',
  },
  {
    slug: 'countries-with-most-forest-area',
    title: 'Countries with the Most Forest Coverage',
    description: 'Top 25 countries by forest area as a percentage of land. Deforestation and conservation.',
    indicatorId: 'AG.LND.FRST.ZS',
    count: 25,
    direction: 'top',
    intro: 'Forests are critical for biodiversity, carbon capture, and climate regulation. Here are the {count} most forested countries in {year}.',
    category: 'Environment',
  },
  {
    slug: 'countries-without-electricity',
    title: 'Countries with the Lowest Access to Electricity',
    description: 'The 25 countries where electricity access is lowest. Energy poverty and development.',
    indicatorId: 'EG.ELC.ACCS.ZS',
    count: 25,
    direction: 'bottom',
    intro: 'Hundreds of millions of people still lack reliable electricity. These {count} countries have the lowest electricity access rates in {year}.',
    category: 'Environment',
  },

  // ── GOVERNANCE & SECURITY ───────────────────────────────
  {
    slug: 'countries-with-highest-military-spending',
    title: 'Countries with the Highest Military Spending',
    description: 'Top 25 countries by military expenditure as a percentage of GDP. Defense spending trends.',
    indicatorId: 'MS.MIL.XPND.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Military spending reflects a nation\'s security priorities and geopolitical posture. Here are the {count} countries that spend the most on defense relative to GDP in {year}.',
    category: 'Governance',
  },
  {
    slug: 'most-corrupt-countries',
    title: 'Most and Least Corrupt Countries in the World',
    description: 'Country rankings by World Bank Control of Corruption indicator. Governance quality worldwide.',
    indicatorId: 'CC.EST',
    count: 25,
    direction: 'bottom',
    intro: 'Corruption undermines development, trust, and economic growth. Here are the {count} countries with the weakest corruption control in {year}, according to the World Bank Governance Indicators.',
    category: 'Governance',
  },
  {
    slug: 'countries-with-strongest-rule-of-law',
    title: 'Countries with the Strongest Rule of Law',
    description: 'Top 25 countries ranked by World Bank Rule of Law indicator. Judicial independence and legal strength.',
    indicatorId: 'RL.EST',
    count: 25,
    direction: 'top',
    intro: 'Strong rule of law underpins investment, stability, and human rights. Here are the {count} countries with the strongest legal institutions in {year}.',
    category: 'Governance',
  },
  {
    slug: 'countries-with-weakest-rule-of-law',
    title: 'Countries with the Weakest Rule of Law',
    description: 'The 25 countries with the weakest legal systems. Corruption, instability, and governance failures.',
    indicatorId: 'RL.EST',
    count: 25,
    direction: 'bottom',
    intro: 'Weak rule of law signals instability, corruption, and lack of judicial independence. These {count} countries score lowest in {year}.',
    category: 'Governance',
  },
  {
    slug: 'countries-with-most-women-in-parliament',
    title: 'Countries with the Most Women in Parliament',
    description: 'Top 25 countries by female representation in national legislature. Gender equality in politics.',
    indicatorId: 'SG.GEN.PARL.ZS',
    count: 25,
    direction: 'top',
    intro: 'Gender representation in government is a key indicator of political equality. Here are the {count} countries with the most women in parliament in {year}.',
    category: 'Governance',
  },

  // ── INEQUALITY ──────────────────────────────────────────
  {
    slug: 'most-unequal-countries-gini',
    title: 'Most Unequal Countries by Gini Index',
    description: 'Top 25 countries with the highest income inequality. Gini coefficient rankings and analysis.',
    indicatorId: 'SI.POV.GINI',
    count: 25,
    direction: 'top',
    intro: 'The Gini index measures income inequality on a scale of 0 (perfect equality) to 100. Here are the {count} most unequal countries in {year}.',
    category: 'Inequality',
  },
  {
    slug: 'most-equal-countries-gini',
    title: 'Most Equal Countries by Gini Index',
    description: 'The 25 countries with the lowest income inequality. Egalitarian societies and wealth distribution.',
    indicatorId: 'SI.POV.GINI',
    count: 25,
    direction: 'bottom',
    intro: 'These {count} countries have the most egalitarian income distribution in {year}, according to the Gini index.',
    category: 'Inequality',
  },
  {
    slug: 'countries-with-highest-poverty-rates',
    title: 'Countries with the Highest Poverty Rates',
    description: 'The 25 countries with the highest extreme poverty ($2.15/day). Development gaps and humanitarian challenges.',
    indicatorId: 'SI.POV.DDAY',
    count: 25,
    direction: 'top',
    intro: 'Extreme poverty — living on less than $2.15 per day — affects hundreds of millions of people. These {count} countries have the highest poverty rates in {year}.',
    category: 'Inequality',
  },

  // ── TECHNOLOGY ──────────────────────────────────────────
  {
    slug: 'countries-with-most-internet-users',
    title: 'Countries with the Highest Internet Penetration',
    description: 'Top 25 countries by percentage of population using the internet. Digital connectivity worldwide.',
    indicatorId: 'IT.NET.USER.ZS',
    count: 25,
    direction: 'top',
    intro: 'The internet has reshaped every aspect of modern life. Here are the {count} most connected countries in {year}.',
    category: 'Technology',
  },
  {
    slug: 'countries-with-least-internet-access',
    title: 'Countries with the Lowest Internet Access',
    description: 'The 25 countries with the lowest internet penetration. The digital divide and connectivity gaps.',
    indicatorId: 'IT.NET.USER.ZS',
    count: 25,
    direction: 'bottom',
    intro: 'While much of the world is online, a significant digital divide persists. These {count} countries have the lowest internet access in {year}.',
    category: 'Technology',
  },
  {
    slug: 'countries-spending-most-on-research',
    title: 'Countries that Spend the Most on R&D',
    description: 'Top 25 countries by research and development expenditure as a share of GDP. Innovation leaders.',
    indicatorId: 'GB.XPD.RSDV.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'R&D spending is the engine of innovation and long-term growth. Here are the {count} countries investing the most in research in {year}.',
    category: 'Technology',
  },
  {
    slug: 'countries-with-most-patents',
    title: 'Countries with the Most Patent Applications',
    description: 'Top 25 countries by resident patent applications. Innovation pipelines and intellectual property.',
    indicatorId: 'IP.PAT.RESD',
    count: 25,
    direction: 'top',
    intro: 'Patent applications measure the output of a country\'s innovation ecosystem. Here are the {count} countries filing the most patents in {year}.',
    category: 'Technology',
  },

  // ── TOURISM ─────────────────────────────────────────────
  {
    slug: 'most-visited-countries',
    title: 'Most Visited Countries in the World',
    description: 'Top 25 countries by international tourist arrivals. Travel destinations and tourism revenue.',
    indicatorId: 'ST.INT.ARVL',
    count: 25,
    direction: 'top',
    intro: 'Tourism is a major driver of economic growth for many nations. Here are the {count} most visited countries in {year} by international arrivals.',
    category: 'Tourism',
  },
];

export function getBlogPost(slug: string): BlogPostDef | undefined {
  return BLOG_POSTS.find(p => p.slug === slug);
}
