/** Programmatic blog post definitions — auto-generated from live data */

export interface BlogPostDef {
  slug: string;
  title: string;
  description: string;
  indicatorId: string;
  count: number;         // top N countries to feature
  direction: 'top' | 'bottom';
  intro: string;         // template — {year}, {count}, {#1}, {#1_value}, etc. filled at render
  category: string;
}

export const BLOG_POSTS: BlogPostDef[] = [
  // ── ECONOMY: GDP ────────────────────────────────────────
  {
    slug: 'richest-countries-in-the-world',
    title: 'Richest Countries in the World by GDP',
    description: 'The top 25 richest countries in the world ranked by GDP (nominal USD). Updated with the latest IMF data.',
    indicatorId: 'IMF.NGDPD',
    count: 25,
    direction: 'top',
    intro: 'The global economy in {year} is dominated by a handful of powerhouses. Here are the {count} richest countries in the world by gross domestic product (nominal USD), based on IMF World Economic Outlook data.',
    category: 'Economy',
  },
  {
    slug: 'smallest-economies-in-the-world',
    title: 'Smallest Economies in the World by GDP',
    description: 'The 25 smallest economies ranked by nominal GDP. Microstates, island nations, and developing countries.',
    indicatorId: 'IMF.NGDPD',
    count: 25,
    direction: 'bottom',
    intro: 'While the global economy is worth over $100 trillion, some nations produce remarkably little. Here are the {count} smallest economies in {year} by nominal GDP.',
    category: 'Economy',
  },
  {
    slug: 'highest-gdp-per-capita',
    title: 'Countries with the Highest GDP per Capita',
    description: 'Top 25 countries ranked by GDP per capita (nominal USD). A measure of individual economic output and wealth.',
    indicatorId: 'IMF.NGDPDPC',
    count: 25,
    direction: 'top',
    intro: 'GDP per capita is one of the best proxies for individual economic output and living standards. Here are the {count} countries with the highest GDP per capita in {year}.',
    category: 'Economy',
  },
  {
    slug: 'poorest-countries-in-the-world',
    title: 'Poorest Countries in the World by GDP per Capita',
    description: 'The 25 poorest countries ranked by GDP per capita. Economic development challenges and extreme poverty.',
    indicatorId: 'IMF.NGDPDPC',
    count: 25,
    direction: 'bottom',
    intro: 'GDP per capita reveals stark global inequality. Here are the {count} poorest countries in {year}, where economic output per person remains critically low.',
    category: 'Economy',
  },
  {
    slug: 'largest-economies-by-ppp',
    title: 'Largest Economies by GDP (PPP)',
    description: 'Top 25 countries ranked by purchasing power parity GDP. A fairer comparison of economic size.',
    indicatorId: 'IMF.PPPGDP',
    count: 25,
    direction: 'top',
    intro: 'Purchasing power parity adjusts for price differences across countries, giving a fairer picture of economic size. Here are the {count} largest economies by PPP in {year}.',
    category: 'Economy',
  },
  {
    slug: 'highest-gdp-per-capita-ppp',
    title: 'Countries with the Highest GDP per Capita (PPP)',
    description: 'Top 25 countries by GDP per capita adjusted for purchasing power. The best measure of living standards.',
    indicatorId: 'IMF.PPPPC',
    count: 25,
    direction: 'top',
    intro: 'GDP per capita PPP is the gold standard for comparing living standards. Here are the {count} countries where purchasing power is highest in {year}.',
    category: 'Economy',
  },

  // ── ECONOMY: GROWTH ─────────────────────────────────────
  {
    slug: 'fastest-growing-economies',
    title: 'Fastest Growing Economies in the World',
    description: 'Top 25 countries by real GDP growth rate. Emerging markets and economic expansion leaders.',
    indicatorId: 'IMF.NGDP_RPCH',
    count: 25,
    direction: 'top',
    intro: 'While advanced economies grow steadily, some nations are expanding at remarkable speed. Here are the {count} fastest-growing economies in {year}.',
    category: 'Economy',
  },
  {
    slug: 'slowest-growing-economies',
    title: 'Slowest Growing and Shrinking Economies',
    description: 'The 25 countries with the lowest GDP growth — recessions, contractions, and economic decline.',
    indicatorId: 'IMF.NGDP_RPCH',
    count: 25,
    direction: 'bottom',
    intro: 'Not every economy is growing. These {count} countries face the weakest or most negative GDP growth rates in {year} — many in outright contraction.',
    category: 'Economy',
  },

  // ── ECONOMY: INFLATION ──────────────────────────────────
  {
    slug: 'countries-with-highest-inflation',
    title: 'Countries with the Highest Inflation Rates',
    description: 'Top 25 countries with the highest consumer price inflation. Hyperinflation, causes, and trends.',
    indicatorId: 'IMF.PCPIPCH',
    count: 25,
    direction: 'top',
    intro: 'Inflation erodes purchasing power and can destabilize economies. Here are the {count} countries with the highest inflation rates in {year}, based on IMF consumer price data.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-inflation',
    title: 'Countries with the Lowest Inflation — and Deflation',
    description: 'The 25 countries with the lowest inflation or deflation. Price stability and monetary policy.',
    indicatorId: 'IMF.PCPIPCH',
    count: 25,
    direction: 'bottom',
    intro: 'Low inflation or outright deflation can signal economic weakness or tight monetary policy. Here are the {count} countries with the lowest price changes in {year}.',
    category: 'Economy',
  },

  // ── ECONOMY: UNEMPLOYMENT ───────────────────────────────
  {
    slug: 'countries-with-highest-unemployment',
    title: 'Countries with the Highest Unemployment Rates',
    description: 'The 25 countries with the highest unemployment rates. Labor market challenges worldwide.',
    indicatorId: 'IMF.LUR',
    count: 25,
    direction: 'top',
    intro: 'High unemployment reflects deep structural and economic challenges. These {count} countries have the highest unemployment rates in {year}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-unemployment',
    title: 'Countries with the Lowest Unemployment Rates',
    description: 'Top 25 countries with the lowest unemployment. Full employment economies and labor market analysis.',
    indicatorId: 'IMF.LUR',
    count: 25,
    direction: 'bottom',
    intro: 'Low unemployment signals a healthy, productive economy. Here are the {count} countries with the lowest unemployment rates in {year}.',
    category: 'Economy',
  },

  // ── ECONOMY: DEBT & FISCAL ──────────────────────────────
  {
    slug: 'countries-with-highest-debt-to-gdp',
    title: 'Countries with the Highest Government Debt-to-GDP Ratio',
    description: 'Top 25 countries ranked by government gross debt as a percentage of GDP. Fiscal sustainability analysis.',
    indicatorId: 'IMF.GGXWDG_NGDP',
    count: 25,
    direction: 'top',
    intro: 'Government debt is a critical measure of fiscal health. Here are the {count} countries with the highest debt-to-GDP ratios in {year}, based on IMF data.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-debt-to-gdp',
    title: 'Countries with the Lowest Government Debt',
    description: 'The 25 countries with the lowest government debt relative to GDP. Fiscal conservatives and resource-rich nations.',
    indicatorId: 'IMF.GGXWDG_NGDP',
    count: 25,
    direction: 'bottom',
    intro: 'Some countries manage to keep government debt remarkably low. Here are the {count} most fiscally conservative nations in {year}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-largest-current-account-surplus',
    title: 'Countries with the Largest Current Account Surplus',
    description: 'Top 25 countries by current account balance. Trade surpluses and capital flows.',
    indicatorId: 'IMF.BCA_NGDPD',
    count: 25,
    direction: 'top',
    intro: 'A current account surplus means a country exports more than it imports. Here are the {count} countries running the largest surpluses in {year}.',
    category: 'Economy',
  },

  // ── ECONOMY: TRADE ──────────────────────────────────────
  {
    slug: 'most-trade-open-economies',
    title: 'Most Trade-Open Economies in the World',
    description: 'Top 25 countries by trade as a percentage of GDP. Globalization and economic openness.',
    indicatorId: 'NE.TRD.GNFS.ZS',
    count: 25,
    direction: 'top',
    intro: 'Trade openness measures how integrated an economy is with the rest of the world. Here are the {count} most trade-dependent economies in {year}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-most-fdi',
    title: 'Countries Attracting the Most Foreign Direct Investment',
    description: 'Top 25 countries by FDI inflows as a percentage of GDP. Investment destinations and capital flows.',
    indicatorId: 'BX.KLT.DINV.WD.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Foreign direct investment signals confidence in an economy. Here are the {count} countries attracting the most FDI relative to GDP in {year}.',
    category: 'Economy',
  },

  // ── DEMOGRAPHICS ────────────────────────────────────────
  {
    slug: 'most-populated-countries',
    title: 'Most Populated Countries in the World',
    description: 'The 25 most populated countries ranked by total population. Demographics, trends, and projections.',
    indicatorId: 'SP.POP.TOTL',
    count: 25,
    direction: 'top',
    intro: 'Over 8 billion people live on Earth. Here are the {count} most populated countries in {year}, together accounting for the vast majority of the global population.',
    category: 'Demographics',
  },
  {
    slug: 'least-populated-countries',
    title: 'Least Populated Countries in the World',
    description: 'The 25 smallest countries by population. Microstates, island nations, and remote territories.',
    indicatorId: 'SP.POP.TOTL',
    count: 25,
    direction: 'bottom',
    intro: 'While India and China each hold over a billion people, some nations have populations smaller than a single city. Here are the {count} least populated countries in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'fastest-growing-populations',
    title: 'Countries with the Fastest Growing Populations',
    description: 'Top 25 countries by annual population growth rate. Demographic booms and migration trends.',
    indicatorId: 'SP.POP.GROW',
    count: 25,
    direction: 'top',
    intro: 'Some countries are experiencing rapid demographic expansion driven by high birth rates and migration. Here are the {count} fastest-growing populations in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'shrinking-populations',
    title: 'Countries with Shrinking Populations',
    description: 'The 25 countries losing population fastest. Demographic decline, aging, and emigration.',
    indicatorId: 'SP.POP.GROW',
    count: 25,
    direction: 'bottom',
    intro: 'Aging societies, low birth rates, and emigration are causing populations to shrink. These {count} countries face the steepest demographic decline in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'most-urbanized-countries',
    title: 'Most Urbanized Countries in the World',
    description: 'Top 25 countries by urban population percentage. Urbanization trends and city growth.',
    indicatorId: 'SP.URB.TOTL.IN.ZS',
    count: 25,
    direction: 'top',
    intro: 'Urbanization is one of the defining trends of modern civilization. Here are the {count} most urbanized countries in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'oldest-populations-in-the-world',
    title: 'Countries with the Oldest Populations',
    description: 'Top 25 countries by share of population aged 65+. Aging societies and pension challenges.',
    indicatorId: 'SP.POP.65UP.TO.ZS',
    count: 25,
    direction: 'top',
    intro: 'An aging population strains pension systems, healthcare, and economic growth. Here are the {count} countries with the largest share of people aged 65+ in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'highest-fertility-rate-countries',
    title: 'Countries with the Highest Fertility Rates',
    description: 'Top 25 countries by total fertility rate. Birth rates, demographics, and population growth.',
    indicatorId: 'SP.DYN.TFRT.IN',
    count: 25,
    direction: 'top',
    intro: 'High fertility rates drive rapid population growth. Here are the {count} countries with the highest birth rates in {year}.',
    category: 'Demographics',
  },
  {
    slug: 'lowest-fertility-rate-countries',
    title: 'Countries with the Lowest Fertility Rates',
    description: 'The 25 countries with the lowest birth rates. Below-replacement fertility and population decline.',
    indicatorId: 'SP.DYN.TFRT.IN',
    count: 25,
    direction: 'bottom',
    intro: 'When fertility drops below the replacement rate of 2.1, populations eventually shrink. These {count} countries have the lowest fertility rates in {year}.',
    category: 'Demographics',
  },

  // ── HEALTH ──────────────────────────────────────────────
  {
    slug: 'highest-life-expectancy-countries',
    title: 'Countries with the Highest Life Expectancy',
    description: 'Top 25 countries where people live the longest. Life expectancy data from the World Bank.',
    indicatorId: 'SP.DYN.LE00.IN',
    count: 25,
    direction: 'top',
    intro: 'Life expectancy at birth is a key measure of population health and development. Here are the {count} countries where people live the longest in {year}.',
    category: 'Health',
  },
  {
    slug: 'lowest-life-expectancy-countries',
    title: 'Countries with the Lowest Life Expectancy',
    description: 'The 25 countries with the lowest life expectancy at birth. Health challenges and development gaps.',
    indicatorId: 'SP.DYN.LE00.IN',
    count: 25,
    direction: 'bottom',
    intro: 'Life expectancy remains starkly unequal across the world. These {count} countries face the greatest health and development challenges in {year}.',
    category: 'Health',
  },
  {
    slug: 'countries-with-highest-infant-mortality',
    title: 'Countries with the Highest Infant Mortality Rates',
    description: 'The 25 countries where the most children die before age 5. Child health and development.',
    indicatorId: 'SH.DYN.MORT',
    count: 25,
    direction: 'top',
    intro: 'Infant mortality is one of the starkest indicators of development. These {count} countries have the highest under-5 mortality rates in {year}.',
    category: 'Health',
  },
  {
    slug: 'countries-with-highest-health-spending',
    title: 'Countries that Spend the Most on Healthcare',
    description: 'Top 25 countries by health expenditure as a share of GDP. Healthcare investment and outcomes.',
    indicatorId: 'SH.XPD.CHEX.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Healthcare spending as a share of GDP varies enormously. Here are the {count} countries investing the most in health in {year}.',
    category: 'Health',
  },

  // ── EDUCATION ───────────────────────────────────────────
  {
    slug: 'most-educated-countries',
    title: 'Most Educated Countries — Tertiary Enrollment Rates',
    description: 'Top 25 countries by tertiary education enrollment rate. Higher education access worldwide.',
    indicatorId: 'SE.TER.ENRR',
    count: 25,
    direction: 'top',
    intro: 'Access to higher education varies enormously. Here are the {count} countries with the highest tertiary enrollment rates in {year}.',
    category: 'Education',
  },
  {
    slug: 'countries-with-highest-education-spending',
    title: 'Countries that Spend the Most on Education',
    description: 'Top 25 countries by education expenditure as a percentage of GDP. Public investment in education.',
    indicatorId: 'SE.XPD.TOTL.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Education spending reflects a nation\'s investment in its future. Here are the {count} countries that dedicate the highest share of GDP to education in {year}.',
    category: 'Education',
  },
  {
    slug: 'countries-with-lowest-literacy-rates',
    title: 'Countries with the Lowest Literacy Rates',
    description: 'The 25 countries where literacy is lowest. Education gaps and development challenges.',
    indicatorId: 'SE.ADT.LITR.ZS',
    count: 25,
    direction: 'bottom',
    intro: 'Literacy is foundational to economic participation and human development. These {count} countries face the greatest literacy challenges in {year}.',
    category: 'Education',
  },

  // ── ENVIRONMENT ─────────────────────────────────────────
  {
    slug: 'countries-with-highest-co2-emissions',
    title: 'Countries with the Highest CO₂ Emissions per Capita',
    description: 'Top 25 countries ranked by carbon dioxide emissions per person. Climate change and emissions data.',
    indicatorId: 'EN.GHG.CO2.PC.CE.AR5',
    count: 25,
    direction: 'top',
    intro: 'Per capita CO₂ emissions reveal which countries contribute most to climate change relative to their population. Here are the {count} highest emitters in {year}.',
    category: 'Environment',
  },
  {
    slug: 'countries-with-most-renewable-energy',
    title: 'Countries with the Most Renewable Energy',
    description: 'Top 25 countries by renewable energy consumption as a share of total energy. Green energy leaders.',
    indicatorId: 'EG.FEC.RNEW.ZS',
    count: 25,
    direction: 'top',
    intro: 'The transition to renewable energy is a defining challenge of our era. Here are the {count} countries leading the way in renewable energy consumption in {year}.',
    category: 'Environment',
  },
  {
    slug: 'countries-with-most-forest-area',
    title: 'Countries with the Most Forest Coverage',
    description: 'Top 25 countries by forest area as a percentage of land. Deforestation and conservation.',
    indicatorId: 'AG.LND.FRST.ZS',
    count: 25,
    direction: 'top',
    intro: 'Forests are critical for biodiversity, carbon capture, and climate regulation. Here are the {count} most forested countries in {year}.',
    category: 'Environment',
  },
  {
    slug: 'countries-without-electricity',
    title: 'Countries with the Lowest Access to Electricity',
    description: 'The 25 countries where electricity access is lowest. Energy poverty and development.',
    indicatorId: 'EG.ELC.ACCS.ZS',
    count: 25,
    direction: 'bottom',
    intro: 'Hundreds of millions of people still lack reliable electricity. These {count} countries have the lowest electricity access rates in {year}.',
    category: 'Environment',
  },

  // ── GOVERNANCE & SECURITY ───────────────────────────────
  {
    slug: 'countries-with-highest-military-spending',
    title: 'Countries with the Highest Military Spending',
    description: 'Top 25 countries by military expenditure as a percentage of GDP. Defense spending trends.',
    indicatorId: 'MS.MIL.XPND.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Military spending reflects a nation\'s security priorities and geopolitical posture. Here are the {count} countries that spend the most on defense relative to GDP in {year}.',
    category: 'Governance',
  },
  {
    slug: 'most-corrupt-countries',
    title: 'Most and Least Corrupt Countries in the World',
    description: 'Country rankings by World Bank Control of Corruption indicator. Governance quality worldwide.',
    indicatorId: 'CC.EST',
    count: 25,
    direction: 'bottom',
    intro: 'Corruption undermines development, trust, and economic growth. Here are the {count} countries with the weakest corruption control in {year}, according to the World Bank Governance Indicators.',
    category: 'Governance',
  },
  {
    slug: 'countries-with-strongest-rule-of-law',
    title: 'Countries with the Strongest Rule of Law',
    description: 'Top 25 countries ranked by World Bank Rule of Law indicator. Judicial independence and legal strength.',
    indicatorId: 'RL.EST',
    count: 25,
    direction: 'top',
    intro: 'Strong rule of law underpins investment, stability, and human rights. Here are the {count} countries with the strongest legal institutions in {year}.',
    category: 'Governance',
  },
  {
    slug: 'countries-with-weakest-rule-of-law',
    title: 'Countries with the Weakest Rule of Law',
    description: 'The 25 countries with the weakest legal systems. Corruption, instability, and governance failures.',
    indicatorId: 'RL.EST',
    count: 25,
    direction: 'bottom',
    intro: 'Weak rule of law signals instability, corruption, and lack of judicial independence. These {count} countries score lowest in {year}.',
    category: 'Governance',
  },
  {
    slug: 'countries-with-most-women-in-parliament',
    title: 'Countries with the Most Women in Parliament',
    description: 'Top 25 countries by female representation in national legislature. Gender equality in politics.',
    indicatorId: 'SG.GEN.PARL.ZS',
    count: 25,
    direction: 'top',
    intro: 'Gender representation in government is a key indicator of political equality. Here are the {count} countries with the most women in parliament in {year}.',
    category: 'Governance',
  },

  // ── INEQUALITY ──────────────────────────────────────────
  {
    slug: 'most-unequal-countries-gini',
    title: 'Most Unequal Countries by Gini Index',
    description: 'Top 25 countries with the highest income inequality. Gini coefficient rankings and analysis.',
    indicatorId: 'SI.POV.GINI',
    count: 25,
    direction: 'top',
    intro: 'The Gini index measures income inequality on a scale of 0 (perfect equality) to 100. Here are the {count} most unequal countries in {year}.',
    category: 'Inequality',
  },
  {
    slug: 'most-equal-countries-gini',
    title: 'Most Equal Countries by Gini Index',
    description: 'The 25 countries with the lowest income inequality. Egalitarian societies and wealth distribution.',
    indicatorId: 'SI.POV.GINI',
    count: 25,
    direction: 'bottom',
    intro: 'These {count} countries have the most egalitarian income distribution in {year}, according to the Gini index.',
    category: 'Inequality',
  },
  {
    slug: 'countries-with-highest-poverty-rates',
    title: 'Countries with the Highest Poverty Rates',
    description: 'The 25 countries with the highest extreme poverty ($2.15/day). Development gaps and humanitarian challenges.',
    indicatorId: 'SI.POV.DDAY',
    count: 25,
    direction: 'top',
    intro: 'Extreme poverty — living on less than $2.15 per day — affects hundreds of millions of people. These {count} countries have the highest poverty rates in {year}.',
    category: 'Inequality',
  },

  // ── TECHNOLOGY ──────────────────────────────────────────
  {
    slug: 'countries-with-most-internet-users',
    title: 'Countries with the Highest Internet Penetration',
    description: 'Top 25 countries by percentage of population using the internet. Digital connectivity worldwide.',
    indicatorId: 'IT.NET.USER.ZS',
    count: 25,
    direction: 'top',
    intro: 'The internet has reshaped every aspect of modern life. Here are the {count} most connected countries in {year}.',
    category: 'Technology',
  },
  {
    slug: 'countries-with-least-internet-access',
    title: 'Countries with the Lowest Internet Access',
    description: 'The 25 countries with the lowest internet penetration. The digital divide and connectivity gaps.',
    indicatorId: 'IT.NET.USER.ZS',
    count: 25,
    direction: 'bottom',
    intro: 'While much of the world is online, a significant digital divide persists. These {count} countries have the lowest internet access in {year}.',
    category: 'Technology',
  },
  {
    slug: 'countries-spending-most-on-research',
    title: 'Countries that Spend the Most on R&D',
    description: 'Top 25 countries by research and development expenditure as a share of GDP. Innovation leaders.',
    indicatorId: 'GB.XPD.RSDV.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'R&D spending is the engine of innovation and long-term growth. Here are the {count} countries investing the most in research in {year}.',
    category: 'Technology',
  },
  {
    slug: 'countries-with-most-patents',
    title: 'Countries with the Most Patent Applications',
    description: 'Top 25 countries by resident patent applications. Innovation pipelines and intellectual property.',
    indicatorId: 'IP.PAT.RESD',
    count: 25,
    direction: 'top',
    intro: 'Patent applications measure the output of a country\'s innovation ecosystem. Here are the {count} countries filing the most patents in {year}.',
    category: 'Technology',
  },

  // ── TOURISM ─────────────────────────────────────────────
  {
    slug: 'most-visited-countries',
    title: 'Most Visited Countries in the World',
    description: 'Top 25 countries by international tourist arrivals. Travel destinations and tourism revenue.',
    indicatorId: 'ST.INT.ARVL',
    count: 25,
    direction: 'top',
    intro: 'Tourism is a major driver of economic growth for many nations. Here are the {count} most visited countries in {year} by international arrivals.',
    category: 'Tourism',
  },

  // ── HIGH-VOLUME QUERY TARGETS ──────────────────────────
  // Targeting specific search queries from GSC + Google Trends
  {
    slug: 'largest-economies-in-the-world',
    title: 'Largest Economies in the World (2026)',
    description: 'The 25 largest economies in the world ranked by GDP in 2026. Comprehensive data from the IMF World Economic Outlook.',
    indicatorId: 'IMF.NGDPD',
    count: 25,
    direction: 'top',
    intro: 'The world economy in {year} is worth over $110 trillion. Here are the {count} largest economies, led by {#1} with a GDP of {#1_value}. Data from the IMF World Economic Outlook.',
    category: 'Economy',
  },
  {
    slug: 'top-10-gdp-countries',
    title: 'Top 10 Countries by GDP in 2026',
    description: 'The top 10 countries by GDP (nominal) in 2026. The United States, China, and Germany lead. IMF data.',
    indicatorId: 'IMF.NGDPD',
    count: 10,
    direction: 'top',
    intro: 'These {count} countries account for over 65% of global economic output. Led by {#1} at {#1_value}, this is where the bulk of the world\'s wealth is concentrated. Source: IMF World Economic Outlook.',
    category: 'Economy',
  },
  {
    slug: 'most-populated-countries',
    title: 'Most Populated Countries in the World (2026)',
    description: 'The 25 most populated countries in the world in 2026. India leads with 1.47 billion, followed by China. World Bank data.',
    indicatorId: 'SP.POP.TOTL',
    count: 25,
    direction: 'top',
    intro: 'With 8.3 billion people on Earth in {year}, population is one of the most fundamental indicators. Here are the {count} most populated countries, led by {#1} with {#1_value} people.',
    category: 'People',
  },
  {
    slug: 'countries-with-highest-inflation-2026',
    title: 'Countries with the Highest Inflation in 2026',
    description: 'Which countries have the highest inflation rates in 2026? Ranked list of 190+ countries with IMF data.',
    indicatorId: 'IMF.PCPIPCH',
    count: 25,
    direction: 'top',
    intro: 'Inflation remains one of the most closely watched economic indicators globally. In {year}, {#1} leads with an inflation rate of {#1_value}. Here are the {count} countries with the highest consumer price inflation, based on IMF projections.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-unemployment',
    title: 'Countries with the Lowest Unemployment Rate (2026)',
    description: 'The 25 countries with the lowest unemployment rates in 2026. Full employment leaders. IMF data.',
    indicatorId: 'IMF.LUR',
    count: 25,
    direction: 'bottom',
    intro: 'Low unemployment signals economic health and tight labor markets. In {year}, these {count} countries have the lowest unemployment rates, led by {#1} at just {#1_value}.',
    category: 'Labor',
  },
  {
    slug: 'richest-countries-by-gdp-per-capita-ppp',
    title: 'Richest Countries by GDP per Capita (PPP) in 2026',
    description: 'The 25 richest countries by GDP per capita adjusted for purchasing power. The best measure of living standards.',
    indicatorId: 'IMF.PPPPC',
    count: 25,
    direction: 'top',
    intro: 'GDP per capita adjusted for purchasing power parity (PPP) is the best single measure of average living standards. In {year}, {#1} leads at {#1_value} per person. Source: IMF.',
    category: 'Economy',
  },
  {
    slug: 'fastest-growing-economies-2026',
    title: 'Fastest Growing Economies in 2026',
    description: 'The 25 fastest growing economies in 2026 by real GDP growth rate. Emerging markets lead. IMF data.',
    indicatorId: 'IMF.NGDP_RPCH',
    count: 25,
    direction: 'top',
    intro: 'While the global economy grows at around 3%, some countries are expanding far faster. In {year}, {#1} leads with {#1_value} real GDP growth. Here are the {count} fastest growing economies.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-most-debt',
    title: 'Countries with the Most Government Debt (% of GDP)',
    description: 'The 25 most indebted countries by government debt as a share of GDP. Fiscal sustainability risks.',
    indicatorId: 'IMF.GGXWDG_NGDP',
    count: 25,
    direction: 'top',
    intro: 'Government debt has ballooned globally since the pandemic. In {year}, {#1} carries the heaviest burden at {#1_value} of GDP. Here are the {count} most indebted countries.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-life-expectancy-2026',
    title: 'Countries with the Highest Life Expectancy (2026)',
    description: 'The 25 countries where people live the longest in 2026. Life expectancy rankings from World Bank data.',
    indicatorId: 'SP.DYN.LE00.IN',
    count: 25,
    direction: 'top',
    intro: 'Life expectancy at birth is one of the most powerful measures of health and development. In {year}, {#1} leads the world at {#1_value} years. Source: World Bank.',
    category: 'People',
  },
  {
    slug: 'countries-with-highest-homicide-rate',
    title: 'Countries with the Highest Homicide Rate',
    description: 'The 25 countries with the highest intentional homicide rates per 100,000 people. Safety and crime data.',
    indicatorId: 'VC.IHR.PSRC.P5',
    count: 25,
    direction: 'top',
    intro: 'Homicide rates vary dramatically across the world. {#1} has the highest rate at {#1_value} per 100,000 people. Here are the {count} countries with the most violent crime.',
    category: 'Safety',
  },
  {
    slug: 'countries-with-aging-population',
    title: 'Countries with the Oldest Population (% Over 65)',
    description: 'The 25 countries with the highest share of population aged 65 and above. The aging crisis.',
    indicatorId: 'SP.POP.65UP.TO.ZS',
    count: 25,
    direction: 'top',
    intro: 'Population aging is one of the defining challenges of the 21st century. In {year}, {#1} has the oldest population with {#1_value} of its people aged 65 or above.',
    category: 'People',
  },
  {
    slug: 'countries-with-youngest-population',
    title: 'Countries with the Youngest Population (% Under 15)',
    description: 'The 25 countries with the highest share of population under 15. Youth bulge and demographic dividends.',
    indicatorId: 'SP.POP.0014.TO.ZS',
    count: 25,
    direction: 'top',
    intro: 'A young population can be a powerful economic asset — or a challenge. In {year}, {#1} has the youngest population with {#1_value} of its people under age 15.',
    category: 'People',
  },
  {
    slug: 'countries-with-highest-tax-revenue',
    title: 'Countries with the Highest Tax Revenue (% of GDP)',
    description: 'The 25 countries collecting the most tax revenue as a share of GDP. Fiscal capacity rankings.',
    indicatorId: 'GC.TAX.TOTL.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Tax revenue as a share of GDP reflects a government\'s fiscal capacity. In {year}, {#1} collects the most at {#1_value} of GDP.',
    category: 'Fiscal',
  },
  {
    slug: 'countries-with-most-air-passengers',
    title: 'Countries with the Most Air Passengers',
    description: 'The 25 countries carrying the most air transport passengers. Aviation and connectivity rankings.',
    indicatorId: 'IS.AIR.PSGR',
    count: 25,
    direction: 'top',
    intro: 'Air passenger volumes reflect both economic activity and global connectivity. {#1} carries the most air passengers at {#1_value}. Here are the top {count} countries.',
    category: 'Infrastructure',
  },
  {
    slug: 'countries-with-highest-suicide-rate',
    title: 'Countries with the Highest Suicide Rate',
    description: 'The 25 countries with the highest suicide mortality rates per 100,000 people. WHO data.',
    indicatorId: 'SH.STA.SUIC.P5',
    count: 25,
    direction: 'top',
    intro: 'Suicide rates reveal the mental health challenges facing nations. {#1} has the highest rate at {#1_value} per 100,000 people. Data from the WHO Global Health Observatory.',
    category: 'Health',
  },
  {
    slug: 'countries-with-most-road-deaths',
    title: 'Countries with the Highest Road Traffic Death Rate',
    description: 'The 25 countries with the most road traffic deaths per 100,000 people. WHO road safety data.',
    indicatorId: 'WHO.ROAD_DEATHS',
    count: 25,
    direction: 'top',
    intro: 'Road traffic fatalities remain a leading cause of death globally. {#1} has the highest rate at {#1_value} per 100,000 people. Source: WHO.',
    category: 'Health',
  },
  {
    slug: 'countries-with-most-immigration',
    title: 'Countries with the Most Net Migration',
    description: 'The 25 countries receiving the most immigrants (net migration). Population flows and immigration patterns.',
    indicatorId: 'SM.POP.NETM',
    count: 25,
    direction: 'top',
    intro: 'Net migration shows where people are moving to — and from. {#1} has the highest net migration at {#1_value}. Here are the top {count} destination countries.',
    category: 'People',
  },
  // ── QUESTION-FORMAT: targeting "what is the GDP of X" and similar ──
  {
    slug: 'largest-economies-in-europe',
    title: 'Largest Economies in Europe by GDP (2026)',
    description: 'The top 25 European economies ranked by GDP. From Germany to the Baltic states. IMF data.',
    indicatorId: 'IMF.NGDPD',
    count: 25,
    direction: 'top',
    intro: 'Europe is the world\'s second-largest economic region. In {year}, {#1} leads European GDP rankings at {#1_value}. Here are the {count} largest European economies.',
    category: 'Economy',
  },
  {
    slug: 'largest-economies-in-asia',
    title: 'Largest Economies in Asia by GDP (2026)',
    description: 'The top 25 Asian economies ranked by GDP. China, Japan, India, and the rising Southeast Asian tigers.',
    indicatorId: 'IMF.NGDPD',
    count: 25,
    direction: 'top',
    intro: 'Asia is home to the world\'s fastest-growing economies. In {year}, {#1} leads Asian GDP rankings at {#1_value}. The top {count} Asian economies by GDP:',
    category: 'Economy',
  },
  {
    slug: 'largest-economies-in-africa',
    title: 'Largest Economies in Africa by GDP (2026)',
    description: 'The top 25 African economies ranked by GDP. Nigeria, South Africa, Egypt, and the emerging markets.',
    indicatorId: 'IMF.NGDPD',
    count: 25,
    direction: 'top',
    intro: 'Africa is the world\'s youngest and fastest-urbanizing continent. In {year}, {#1} leads with {#1_value} GDP. Here are Africa\'s {count} largest economies.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-inflation',
    title: 'Countries with the Lowest Inflation Rate (2026)',
    description: 'The 25 countries with the lowest inflation or deflation. Price stability leaders and deflation risks.',
    indicatorId: 'IMF.PCPIPCH',
    count: 25,
    direction: 'bottom',
    intro: 'While much of the world battles high inflation, some countries maintain remarkably stable prices. In {year}, {#1} has the lowest inflation at {#1_value}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-unemployment',
    title: 'Countries with the Lowest Unemployment Rate (2026)',
    description: 'The 25 countries with the lowest unemployment. Full employment leaders and tight labor markets.',
    indicatorId: 'IMF.LUR',
    count: 25,
    direction: 'bottom',
    intro: 'Low unemployment reflects a healthy labor market — or sometimes, an informal economy that hides true joblessness. In {year}, {#1} has just {#1_value} unemployment.',
    category: 'Economy',
  },
  {
    slug: 'most-urbanized-countries',
    title: 'Most Urbanized Countries in the World (2026)',
    description: 'The 25 most urbanized countries by share of population living in cities. Urbanization trends.',
    indicatorId: 'SP.URB.TOTL.IN.ZS',
    count: 25,
    direction: 'top',
    intro: 'The world is rapidly urbanizing — over 56% of humanity now lives in cities. In {year}, {#1} is the most urbanized at {#1_value}. Here are the top {count}.',
    category: 'People',
  },
  {
    slug: 'countries-with-highest-fertility-rate',
    title: 'Countries with the Highest Fertility Rate (2026)',
    description: 'The 25 countries with the highest fertility rates. Population growth, demographic dividends, and challenges.',
    indicatorId: 'SP.DYN.TFRT.IN',
    count: 25,
    direction: 'top',
    intro: 'Fertility rates determine long-term population trajectories. In {year}, {#1} has the highest fertility at {#1_value} births per woman. The replacement rate is 2.1.',
    category: 'People',
  },
  {
    slug: 'countries-with-lowest-fertility-rate',
    title: 'Countries with the Lowest Fertility Rate (2026)',
    description: 'The 25 countries with the lowest fertility rates. Population decline, aging, and demographic crisis.',
    indicatorId: 'SP.DYN.TFRT.IN',
    count: 25,
    direction: 'bottom',
    intro: 'Below-replacement fertility threatens long-term economic sustainability. In {year}, {#1} has just {#1_value} births per woman — far below the 2.1 replacement rate.',
    category: 'People',
  },
  {
    slug: 'safest-countries-in-the-world',
    title: 'Safest Countries in the World by Homicide Rate (2026)',
    description: 'The 25 safest countries ranked by lowest homicide rate per 100,000 people. Crime and safety data.',
    indicatorId: 'VC.IHR.PSRC.P5',
    count: 25,
    direction: 'bottom',
    intro: 'Safety is a key factor in quality of life and economic development. {#1} ranks as the safest country with only {#1_value} homicides per 100,000 people.',
    category: 'Safety',
  },
  {
    slug: 'countries-with-highest-rd-spending',
    title: 'Countries Spending the Most on R&D (% of GDP)',
    description: 'The 25 countries investing the most in research and development. Innovation leaders worldwide.',
    indicatorId: 'GB.XPD.RSDV.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'R&D investment drives innovation and long-term economic competitiveness. In {year}, {#1} invests {#1_value} of GDP in research and development.',
    category: 'Innovation',
  },
  {
    slug: 'countries-with-most-internet-users',
    title: 'Countries with the Most Internet Users (% of Population)',
    description: 'The 25 most connected countries by internet penetration. Digital divide and connectivity.',
    indicatorId: 'IT.NET.USER.ZS',
    count: 25,
    direction: 'top',
    intro: 'Internet access is increasingly essential for economic participation. {#1} leads with {#1_value} of its population online. Here are the most connected countries.',
    category: 'Technology',
  },
  {
    slug: 'countries-with-highest-renewable-energy',
    title: 'Countries with the Highest Renewable Energy Use (2026)',
    description: 'The 25 countries leading the clean energy transition by renewable energy share. Climate and energy.',
    indicatorId: 'EG.FEC.RNEW.ZS',
    count: 25,
    direction: 'top',
    intro: 'The energy transition is reshaping the global economy. {#1} leads with {#1_value} of energy from renewable sources. Here are the top {count} green energy leaders.',
    category: 'Climate',
  },
  {
    slug: 'most-corrupt-countries',
    title: 'Most Corrupt Countries in the World (2026)',
    description: 'The 25 countries scoring worst on the World Bank\'s Control of Corruption indicator. Governance data.',
    indicatorId: 'CC.EST',
    count: 25,
    direction: 'bottom',
    intro: 'Corruption undermines economic development and institutional trust. The World Bank\'s governance indicators rank {#1} as having the weakest corruption control at {#1_value}.',
    category: 'Governance',
  },
  {
    slug: 'least-corrupt-countries',
    title: 'Least Corrupt Countries in the World (2026)',
    description: 'The 25 countries with the strongest corruption control. Governance and institutional quality.',
    indicatorId: 'CC.EST',
    count: 25,
    direction: 'top',
    intro: 'Strong institutions and rule of law are foundations of economic prosperity. {#1} leads the world in corruption control with a score of {#1_value}.',
    category: 'Governance',
  },
  {
    slug: 'countries-with-best-rule-of-law',
    title: 'Countries with the Strongest Rule of Law (2026)',
    description: 'The 25 countries scoring highest on the World Bank\'s Rule of Law indicator. Governance and justice.',
    indicatorId: 'RL.EST',
    count: 25,
    direction: 'top',
    intro: 'Rule of law is fundamental to economic confidence and investment. {#1} leads globally with a score of {#1_value} on the World Bank governance indicator.',
    category: 'Governance',
  },
  {
    slug: 'countries-with-highest-trade-openness',
    title: 'Most Open Economies by Trade (% of GDP) — 2026',
    description: 'The 25 most trade-open economies measured by imports+exports as a share of GDP. Globalization data.',
    indicatorId: 'NE.TRD.GNFS.ZS',
    count: 25,
    direction: 'top',
    intro: 'Trade openness measures how integrated an economy is with the rest of the world. {#1} leads at {#1_value} of GDP from trade. Small, open economies tend to rank highest.',
    category: 'Trade',
  },
  {
    slug: 'countries-with-lowest-life-expectancy',
    title: 'Countries with the Lowest Life Expectancy (2026)',
    description: 'The 25 countries where people live the shortest. Health crises, poverty, and development challenges.',
    indicatorId: 'SP.DYN.LE00.IN',
    count: 25,
    direction: 'bottom',
    intro: 'Low life expectancy reflects severe health and development challenges. In {year}, {#1} has the lowest life expectancy at just {#1_value} years.',
    category: 'Health',
  },
  {
    slug: 'countries-with-highest-infant-mortality',
    title: 'Countries with the Highest Infant Mortality Rate (2026)',
    description: 'The 25 countries with the highest under-5 mortality per 1,000 live births. Child health crisis.',
    indicatorId: 'SH.DYN.MORT',
    count: 25,
    direction: 'top',
    intro: 'Infant mortality is one of the starkest measures of development inequality. {#1} has the highest under-5 mortality at {#1_value} per 1,000 live births.',
    category: 'Health',
  },
  {
    slug: 'countries-with-highest-fdi',
    title: 'Countries Receiving the Most Foreign Direct Investment (2026)',
    description: 'The 25 countries attracting the most FDI as a share of GDP. Investment flows and economic openness.',
    indicatorId: 'BX.KLT.DINV.WD.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Foreign direct investment reflects global confidence in a country\'s economy. {#1} attracts the most FDI at {#1_value} of GDP. Here are the top {count} FDI destinations.',
    category: 'Investment',
  },
  {
    slug: 'countries-with-most-inequality',
    title: 'Countries with the Most Inequality (Gini Index)',
    description: 'The 25 most unequal countries by Gini coefficient. Income distribution and poverty.',
    indicatorId: 'SI.POV.GINI',
    count: 25,
    direction: 'top',
    intro: 'The Gini Index measures income inequality — 0 is perfect equality, 100 is maximum inequality. {#1} has the highest inequality at {#1_value}.',
    category: 'Social',
  },
  {
    slug: 'countries-with-most-forest',
    title: 'Countries with the Most Forest Cover (% of Land Area)',
    description: 'The 25 most forested countries by percentage of total land area. Deforestation and conservation.',
    indicatorId: 'AG.LND.FRST.ZS',
    count: 25,
    direction: 'top',
    intro: 'Forests are critical for biodiversity, carbon sequestration, and climate regulation. {#1} has the most forest cover at {#1_value} of its land area.',
    category: 'Environment',
  },
  {
    slug: 'countries-with-highest-youth-unemployment',
    title: 'Countries with the Highest Youth Unemployment (2026)',
    description: 'The 25 countries with the highest youth unemployment rates (ages 15-24). Social stability risks.',
    indicatorId: 'SL.UEM.1524.ZS',
    count: 25,
    direction: 'top',
    intro: 'Youth unemployment is a ticking time bomb for social stability. In {year}, {#1} has {#1_value} of its young people unable to find work.',
    category: 'Labor',
  },
  {
    slug: 'countries-with-highest-imports',
    title: 'Countries with the Highest Imports (2026)',
    description: 'The 25 largest importing countries by total imports in USD. Global trade flows.',
    indicatorId: 'NE.IMP.GNFS.CD',
    count: 25,
    direction: 'top',
    intro: 'Import volumes reveal a country\'s consumption patterns and supply chain dependencies. {#1} is the world\'s largest importer at {#1_value}.',
    category: 'Trade',
  },
  {
    slug: 'countries-with-most-tourists',
    title: 'Most Visited Countries in the World (2026)',
    description: 'The 25 most visited countries by international tourist arrivals. Tourism rankings and travel data.',
    indicatorId: 'ST.INT.ARVL',
    count: 25,
    direction: 'top',
    intro: 'Tourism is a major economic driver for many countries. {#1} leads the world with {#1_value} international tourist arrivals. Here are the top {count} destinations.',
    category: 'Tourism',
  },
  {
    slug: 'countries-with-highest-health-spending',
    title: 'Countries Spending the Most on Healthcare (% of GDP)',
    description: 'The 25 countries with the highest health expenditure as a share of GDP. Healthcare systems comparison.',
    indicatorId: 'SH.XPD.CHEX.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Health spending reveals national priorities and healthcare system costs. {#1} spends {#1_value} of its GDP on health — the highest in the world.',
    category: 'Health',
  },
  {
    slug: 'countries-with-highest-military-spending',
    title: 'Countries with the Highest Military Spending (% of GDP)',
    description: 'The 25 countries spending the most on defense as a share of GDP. Military budgets worldwide.',
    indicatorId: 'MS.MIL.XPND.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Military spending reflects geopolitical priorities and security threats. {#1} allocates {#1_value} of GDP to defense — the highest share globally.',
    category: 'Defense',
  },
  {
    slug: 'countries-with-highest-education-spending',
    title: 'Countries Spending the Most on Education (% of GDP)',
    description: 'The 25 countries investing the most in education. Human capital and development priorities.',
    indicatorId: 'SE.XPD.TOTL.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Education spending is an investment in human capital. {#1} leads globally at {#1_value} of GDP spent on education.',
    category: 'Education',
  },
  {
    slug: 'countries-with-highest-gni',
    title: 'Countries with the Highest Gross National Income (2026)',
    description: 'The 25 countries with the highest GNI. Total income earned by a country\'s residents worldwide.',
    indicatorId: 'NY.GNP.MKTP.CD',
    count: 25,
    direction: 'top',
    intro: 'Gross National Income includes all income earned by a country\'s residents, including abroad. {#1} leads at {#1_value}. GNI differs from GDP by accounting for net income from overseas.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-current-account-surplus',
    title: 'Countries with the Largest Current Account Surplus (2026)',
    description: 'The 25 countries with the biggest current account surpluses. Trade balances and capital flows.',
    indicatorId: 'IMF.BCA_NGDPD',
    count: 25,
    direction: 'top',
    intro: 'A current account surplus means a country earns more from the rest of the world than it spends. {#1} has the largest surplus at {#1_value}.',
    category: 'Trade',
  },
  {
    slug: 'countries-with-highest-poverty-rate',
    title: 'Countries with the Highest Poverty Rate (2026)',
    description: 'The 25 countries with the most extreme poverty ($2.15/day). Global poverty and development.',
    indicatorId: 'SI.POV.DDAY',
    count: 25,
    direction: 'top',
    intro: 'Despite global progress, extreme poverty persists. In {year}, {#1} has the highest poverty rate at {#1_value} of its population living on less than $2.15/day.',
    category: 'Social',
  },

  // ── ROUND 2: 30 MORE LONG-TAIL POSTS ──────────────────────

  // LABOR & EMPLOYMENT
  {
    slug: 'countries-with-highest-female-labor-participation',
    title: 'Countries with the Highest Female Labor Force Participation',
    description: 'Top 25 countries by female labor force participation rate. Gender equality and economic inclusion.',
    indicatorId: 'SL.TLF.CACT.FE.ZS',
    count: 25,
    direction: 'top',
    intro: 'Female labor force participation varies enormously worldwide. {#1} leads at {#1_value}, reflecting strong policies for gender economic inclusion.',
    category: 'Labor',
  },
  {
    slug: 'countries-with-lowest-female-labor-participation',
    title: 'Countries with the Lowest Female Labor Force Participation',
    description: 'The 25 countries where women participate least in the formal workforce.',
    indicatorId: 'SL.TLF.CACT.FE.ZS',
    count: 25,
    direction: 'bottom',
    intro: 'In some countries, fewer than 20% of women participate in the formal labor force. {#1} has the lowest rate at {#1_value}.',
    category: 'Labor',
  },
  {
    slug: 'countries-with-most-employment-in-agriculture',
    title: 'Countries Where Most People Work in Agriculture (2026)',
    description: 'The 25 countries with the highest share of employment in agriculture. Subsistence farming and rural economies.',
    indicatorId: 'SL.AGR.EMPL.ZS',
    count: 25,
    direction: 'top',
    intro: 'Agriculture remains the primary employer in many developing countries. In {#1}, {#1_value} of all workers are employed in farming.',
    category: 'Labor',
  },
  {
    slug: 'countries-with-most-employment-in-services',
    title: 'Countries with the Most Service Sector Employment',
    description: 'The 25 countries where services dominate the economy. Post-industrial and knowledge economies.',
    indicatorId: 'SL.SRV.EMPL.ZS',
    count: 25,
    direction: 'top',
    intro: 'Service-sector dominance is a hallmark of advanced economies. {#1} leads with {#1_value} of employment in services.',
    category: 'Labor',
  },

  // TRADE & INVESTMENT
  {
    slug: 'countries-with-highest-exports',
    title: 'Countries with the Highest Exports (2026)',
    description: 'The 25 largest exporting countries by total goods and services exports in USD.',
    indicatorId: 'NE.EXP.GNFS.CD',
    count: 25,
    direction: 'top',
    intro: 'Global trade is dominated by manufacturing and commodity exporters. {#1} leads world exports at {#1_value}.',
    category: 'Trade',
  },
  {
    slug: 'countries-with-highest-imports',
    title: 'Countries with the Highest Imports (2026)',
    description: 'The 25 largest importing countries by total goods and services imports in USD.',
    indicatorId: 'NE.IMP.GNFS.CD',
    count: 25,
    direction: 'top',
    intro: 'The world\'s largest importers drive global demand. {#1} is the top importer at {#1_value}.',
    category: 'Trade',
  },
  {
    slug: 'countries-with-highest-high-tech-exports',
    title: 'Countries with the Most High-Tech Exports',
    description: 'The 25 countries with the highest share of high-technology exports in manufacturing.',
    indicatorId: 'TX.VAL.TECH.MF.ZS',
    count: 25,
    direction: 'top',
    intro: 'High-tech exports reflect innovation capacity. {#1} leads with {#1_value} of manufactured exports being high-technology products.',
    category: 'Trade',
  },
  {
    slug: 'countries-with-most-remittances',
    title: 'Countries Receiving the Most Remittances (2026)',
    description: 'The 25 countries that receive the most in personal remittances as % of GDP.',
    indicatorId: 'BX.TRF.PWKR.DT.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Remittances are a lifeline for many developing economies. {#1} receives remittances equal to {#1_value} of GDP.',
    category: 'Trade',
  },

  // FINANCE
  {
    slug: 'countries-with-largest-stock-markets',
    title: 'Countries with the Largest Stock Markets (2026)',
    description: 'The 25 countries with the highest stock market capitalization as % of GDP.',
    indicatorId: 'CM.MKT.LCAP.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Stock market depth reflects financial development. {#1} has a market capitalization of {#1_value} of GDP.',
    category: 'Finance',
  },
  {
    slug: 'countries-with-highest-foreign-reserves',
    title: 'Countries with the Largest Foreign Reserves (2026)',
    description: 'The 25 countries with the most foreign currency reserves including gold.',
    indicatorId: 'FI.RES.TOTL.CD',
    count: 25,
    direction: 'top',
    intro: 'Foreign reserves provide a buffer against economic shocks. {#1} holds the world\'s largest reserves at {#1_value}.',
    category: 'Finance',
  },
  {
    slug: 'countries-with-highest-financial-inclusion',
    title: 'Countries with the Highest Financial Inclusion',
    description: 'The 25 countries where the most adults have a bank account. Financial access and inclusion.',
    indicatorId: 'FX.OWN.TOTL.ZS',
    count: 25,
    direction: 'top',
    intro: 'Financial inclusion means access to basic banking. {#1} leads at {#1_value} of adults with an account.',
    category: 'Finance',
  },

  // ENVIRONMENT & ENERGY
  {
    slug: 'countries-with-highest-forest-coverage',
    title: 'Countries with the Most Forest Coverage (% of Land)',
    description: 'The 25 most forested countries by percentage of land area covered by forest.',
    indicatorId: 'AG.LND.FRST.ZS',
    count: 25,
    direction: 'top',
    intro: 'Forests are critical for biodiversity and carbon absorption. {#1} has the most forest coverage at {#1_value} of its land area.',
    category: 'Environment',
  },
  {
    slug: 'countries-with-lowest-co2-emissions',
    title: 'Countries with the Lowest CO2 Emissions per Capita',
    description: 'The 25 countries emitting the least CO2 per person. Clean energy and low carbon footprints.',
    indicatorId: 'EN.ATM.CO2E.PC',
    count: 25,
    direction: 'bottom',
    intro: 'Some countries produce almost no carbon per person. {#1} emits just {#1_value} metric tons per capita.',
    category: 'Environment',
  },
  {
    slug: 'countries-with-highest-renewable-energy-share',
    title: 'Countries with the Most Renewable Energy (2026)',
    description: 'The 25 countries with the highest share of energy from renewable sources.',
    indicatorId: 'EG.FEC.RNEW.ZS',
    count: 25,
    direction: 'top',
    intro: 'The energy transition is underway. {#1} leads with {#1_value} of its energy from renewable sources.',
    category: 'Environment',
  },
  {
    slug: 'countries-with-most-electricity-access',
    title: 'Countries with 100% Electricity Access vs the Least',
    description: 'Access to electricity worldwide — from universal coverage to under 10%.',
    indicatorId: 'EG.ELC.ACCS.ZS',
    count: 25,
    direction: 'bottom',
    intro: 'Nearly 1 billion people still lack electricity. {#1} has the lowest access at {#1_value}.',
    category: 'Infrastructure',
  },

  // HEALTH
  {
    slug: 'countries-with-highest-life-expectancy-female',
    title: 'Countries Where Women Live the Longest (2026)',
    description: 'The 25 countries with the highest female life expectancy. Women outlive men everywhere.',
    indicatorId: 'SP.DYN.LE00.FE.IN',
    count: 25,
    direction: 'top',
    intro: 'Women live longer than men in virtually every country. {#1} has the highest female life expectancy at {#1_value} years.',
    category: 'Health',
  },
  {
    slug: 'countries-with-highest-death-rate',
    title: 'Countries with the Highest Death Rate (2026)',
    description: 'The 25 countries with the highest crude death rate per 1,000 people.',
    indicatorId: 'SP.DYN.CDRT.IN',
    count: 25,
    direction: 'top',
    intro: 'High death rates reflect aging populations or poor health infrastructure. {#1} has the highest crude death rate at {#1_value} per 1,000.',
    category: 'Health',
  },
  {
    slug: 'countries-with-highest-birth-rate',
    title: 'Countries with the Highest Birth Rate (2026)',
    description: 'The 25 countries with the highest crude birth rate per 1,000 people. Fertility and demographics.',
    indicatorId: 'SP.DYN.CBRT.IN',
    count: 25,
    direction: 'top',
    intro: 'High birth rates drive rapid population growth. {#1} has the highest birth rate at {#1_value} per 1,000 people.',
    category: 'Demographics',
  },

  // DEMOGRAPHICS & SOCIAL
  {
    slug: 'most-densely-populated-countries',
    title: 'Most Densely Populated Countries in the World (2026)',
    description: 'The 25 most densely populated countries by people per square kilometer.',
    indicatorId: 'EN.POP.DNST',
    count: 25,
    direction: 'top',
    intro: 'Population density varies from over 20,000/km² in microstates to under 5 in remote nations. {#1} is the most densely populated at {#1_value} people per km².',
    category: 'Demographics',
  },
  {
    slug: 'countries-with-highest-dependency-ratio',
    title: 'Countries with the Highest Dependency Ratio',
    description: 'The 25 countries with the most dependents (children + elderly) per working-age person.',
    indicatorId: 'SP.POP.DPND',
    count: 25,
    direction: 'top',
    intro: 'High dependency ratios strain public services and economic growth. {#1} has the highest ratio at {#1_value}%.',
    category: 'Demographics',
  },
  {
    slug: 'countries-with-highest-old-age-dependency',
    title: 'Countries with the Most Aging Populations (2026)',
    description: 'The 25 countries with the highest old-age dependency ratio. Population aging and pension pressures.',
    indicatorId: 'SP.POP.DPND.OL',
    count: 25,
    direction: 'top',
    intro: 'Population aging is one of the defining demographic trends. {#1} has the highest old-age dependency at {#1_value}%.',
    category: 'Demographics',
  },
  {
    slug: 'countries-with-most-net-immigration',
    title: 'Countries Receiving the Most Immigrants (2026)',
    description: 'The 25 countries with the highest net migration. Where people are moving and why.',
    indicatorId: 'SM.POP.NETM',
    count: 25,
    direction: 'top',
    intro: 'Migration flows reflect economic opportunity and security. {#1} receives the most net immigrants globally.',
    category: 'Demographics',
  },

  // GOVERNANCE
  {
    slug: 'countries-with-strongest-rule-of-law',
    title: 'Countries with the Strongest Rule of Law (2026)',
    description: 'The 25 countries with the best rule of law scores. Justice, property rights, and governance quality.',
    indicatorId: 'RL.EST',
    count: 25,
    direction: 'top',
    intro: 'Strong rule of law underpins economic prosperity. {#1} has the highest rule of law score globally.',
    category: 'Governance',
  },
  {
    slug: 'countries-with-highest-government-spending',
    title: 'Countries with the Highest Government Spending (% GDP)',
    description: 'The 25 countries where government expenditure consumes the most GDP.',
    indicatorId: 'GC.XPN.TOTL.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Government spending reflects the size of the public sector. {#1} spends the most at {#1_value} of GDP.',
    category: 'Fiscal',
  },
  {
    slug: 'countries-with-highest-fiscal-deficit',
    title: 'Countries with the Largest Fiscal Deficits (2026)',
    description: 'The 25 countries running the biggest government budget deficits as % of GDP.',
    indicatorId: 'IMF.GGXCNL_NGDP',
    count: 25,
    direction: 'bottom',
    intro: 'Fiscal deficits mean governments spend more than they earn. {#1} has the largest deficit at {#1_value} of GDP.',
    category: 'Fiscal',
  },
  {
    slug: 'countries-with-highest-investment-rate',
    title: 'Countries with the Highest Investment Rate (% GDP)',
    description: 'The 25 countries investing the most in capital formation. Infrastructure and growth capacity.',
    indicatorId: 'NE.GDI.TOTL.ZS',
    count: 25,
    direction: 'top',
    intro: 'Investment drives future growth. {#1} invests {#1_value} of GDP in gross capital formation — the highest globally.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-savings-rate',
    title: 'Countries with the Highest Savings Rate (2026)',
    description: 'The 25 countries saving the most as % of GDP. Savings fund investment and growth.',
    indicatorId: 'NY.GNS.ICTR.ZS',
    count: 25,
    direction: 'top',
    intro: 'High savings fund domestic investment and reduce dependence on foreign capital. {#1} saves {#1_value} of GNI.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-gdp-ppp',
    title: 'Largest Economies by Purchasing Power Parity (PPP)',
    description: 'The 25 largest economies by GDP adjusted for purchasing power parity.',
    indicatorId: 'IMF.PPPGDP',
    count: 25,
    direction: 'top',
    intro: 'PPP adjusts for price differences across countries. By PPP, {#1} has the world\'s largest economy at {#1_value}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-natural-resource-rents',
    title: 'Countries Most Dependent on Natural Resources (2026)',
    description: 'The 25 countries where natural resource rents form the largest share of GDP.',
    indicatorId: 'NY.GDP.TOTL.RT.ZS',
    count: 25,
    direction: 'top',
    intro: 'Resource-dependent economies face unique challenges. {#1} derives {#1_value} of GDP from natural resource rents.',
    category: 'Economy',
  },

  // ── ROUND 3: 20 MORE LONG-TAIL QUESTION POSTS ──────────────

  {
    slug: 'countries-with-lowest-unemployment',
    title: 'Countries with the Lowest Unemployment Rate (2026)',
    description: 'The 25 countries with the lowest unemployment. Near-full employment and tight labor markets.',
    indicatorId: 'IMF.LUR',
    count: 25,
    direction: 'bottom',
    intro: 'Some economies have achieved near-full employment. {#1} has the world\'s lowest unemployment at {#1_value}.',
    category: 'Labor',
  },
  {
    slug: 'countries-with-highest-gdp-growth-2026',
    title: 'Fastest Growing Economies in 2026',
    description: 'The 25 fastest-growing economies by real GDP growth rate. Emerging markets and recovery stories.',
    indicatorId: 'IMF.NGDP_RPCH',
    count: 25,
    direction: 'top',
    intro: 'The fastest-growing economies often combine demographic advantages with catch-up potential. {#1} leads global growth at {#1_value} in {year}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-gdp-growth',
    title: 'Slowest Growing Economies in 2026',
    description: 'The 25 countries with the slowest or most negative GDP growth. Recession, conflict, and stagnation.',
    indicatorId: 'IMF.NGDP_RPCH',
    count: 25,
    direction: 'bottom',
    intro: 'Economic contraction reflects conflict, policy failure, or structural decline. {#1} has the weakest growth at {#1_value}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-lowest-inflation',
    title: 'Countries with the Lowest Inflation Rate (2026)',
    description: 'The 25 countries with the lowest inflation — including deflation. Price stability and monetary policy success.',
    indicatorId: 'IMF.PCPIPCH',
    count: 25,
    direction: 'bottom',
    intro: 'Ultra-low inflation or deflation presents unique challenges. {#1} has the lowest inflation at {#1_value}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-government-revenue',
    title: 'Countries with the Highest Government Revenue (% GDP)',
    description: 'The 25 countries where government collects the most revenue as a share of GDP.',
    indicatorId: 'GC.REV.XGRT.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Government revenue reflects fiscal capacity. {#1} collects {#1_value} of GDP in revenue — the highest globally.',
    category: 'Fiscal',
  },
  {
    slug: 'countries-with-highest-external-debt',
    title: 'Countries with the Highest External Debt (% of GNI)',
    description: 'The 25 countries with the most external debt relative to national income. Debt sustainability and risk.',
    indicatorId: 'DT.DOD.DECT.GN.ZS',
    count: 25,
    direction: 'top',
    intro: 'High external debt creates vulnerability to capital flight and currency crises. {#1} has external debt of {#1_value} of GNI.',
    category: 'Finance',
  },
  {
    slug: 'countries-with-largest-land-area',
    title: 'Largest Countries in the World by Land Area (2026)',
    description: 'The 25 largest countries by land area in square kilometers. From Russia to Australia.',
    indicatorId: 'AG.LND.TOTL.K2',
    count: 25,
    direction: 'top',
    intro: 'Russia is the world\'s largest country by land area at {#1_value} sq km, spanning 11 time zones.',
    category: 'Geography',
  },
  {
    slug: 'countries-with-highest-bank-nonperforming-loans',
    title: 'Countries with the Most Bank Bad Loans (2026)',
    description: 'The 25 countries with the highest bank nonperforming loan ratios. Financial system health.',
    indicatorId: 'FB.AST.NPER.ZS',
    count: 25,
    direction: 'top',
    intro: 'High nonperforming loans signal banking sector stress. {#1} has {#1_value} bad loan ratio — the highest globally.',
    category: 'Finance',
  },
  {
    slug: 'countries-with-highest-domestic-credit',
    title: 'Countries with the Deepest Financial Markets',
    description: 'The 25 countries with the highest domestic credit to private sector (% of GDP). Financial depth and development.',
    indicatorId: 'FS.AST.PRVT.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Credit depth reflects financial sector development. {#1} provides {#1_value} of GDP in private sector credit.',
    category: 'Finance',
  },
  {
    slug: 'countries-with-highest-broad-money',
    title: 'Countries with the Most Money in Circulation (% GDP)',
    description: 'The 25 countries with the highest broad money supply relative to GDP. Monetary depth and liquidity.',
    indicatorId: 'FM.LBL.BMNY.GD.ZS',
    count: 25,
    direction: 'top',
    intro: 'Broad money relative to GDP measures financial depth. {#1} has the highest ratio at {#1_value}.',
    category: 'Finance',
  },
  {
    slug: 'countries-with-youngest-population',
    title: 'Countries with the Youngest Population (2026)',
    description: 'The 25 countries with the highest share of population under 15. Youth bulge and demographic dividend potential.',
    indicatorId: 'SP.POP.0014.TO.ZS',
    count: 25,
    direction: 'top',
    intro: 'Countries with the youngest populations face both opportunities and challenges. {#1} has {#1_value} of its population under 15.',
    category: 'Demographics',
  },
  {
    slug: 'countries-with-highest-working-age-share',
    title: 'Countries with the Largest Working-Age Population Share',
    description: 'The 25 countries where the working-age population (15-64) forms the highest share of total population.',
    indicatorId: 'SP.POP.1564.TO.ZS',
    count: 25,
    direction: 'top',
    intro: 'A large working-age share can fuel economic growth. {#1} has {#1_value} of its population in the prime working years.',
    category: 'Demographics',
  },
  {
    slug: 'countries-with-highest-oil-dependence',
    title: 'Countries Most Dependent on Oil Revenue (2026)',
    description: 'The 25 countries where oil rents form the largest share of GDP. Petrostates and energy dependence.',
    indicatorId: 'NY.GDP.PETR.RT.ZS',
    count: 25,
    direction: 'top',
    intro: 'Oil-dependent economies face volatile revenue and "Dutch disease" challenges. {#1} derives {#1_value} of GDP from oil.',
    category: 'Energy',
  },
  {
    slug: 'countries-with-lowest-government-debt',
    title: 'Countries with the Lowest Government Debt (2026)',
    description: 'The 25 countries with the lowest government debt to GDP ratio. Fiscal strength and low borrowing.',
    indicatorId: 'IMF.GGXWDG_NGDP',
    count: 25,
    direction: 'bottom',
    intro: 'Some countries have virtually no government debt. {#1} has the lowest debt ratio at {#1_value} of GDP.',
    category: 'Fiscal',
  },
  {
    slug: 'countries-with-highest-lending-rate',
    title: 'Countries with the Highest Interest Rates (2026)',
    description: 'The 25 countries with the highest lending interest rates. Monetary tightening and inflation control.',
    indicatorId: 'FR.INR.LEND',
    count: 25,
    direction: 'top',
    intro: 'High interest rates reflect inflationary pressures or credit risk. {#1} has a lending rate of {#1_value}.',
    category: 'Finance',
  },
  {
    slug: 'countries-with-most-listed-companies',
    title: 'Countries with the Most Stock Market Listed Companies',
    description: 'The 25 countries with the most domestic companies listed on stock exchanges.',
    indicatorId: 'CM.MKT.LDOM.NO',
    count: 25,
    direction: 'top',
    intro: 'Stock market breadth reflects entrepreneurial activity and financial development. {#1} has {#1_value} listed companies.',
    category: 'Finance',
  },
  {
    slug: 'countries-with-highest-industry-share',
    title: 'Countries Where Industry Dominates the Economy',
    description: 'The 25 countries with the highest industry value added as % of GDP. Manufacturing and industrial powerhouses.',
    indicatorId: 'NV.IND.TOTL.ZS',
    count: 25,
    direction: 'top',
    intro: 'Industry-heavy economies are typically in the manufacturing or resource-extraction phase of development. {#1} has industry at {#1_value} of GDP.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-services-share',
    title: 'Countries Where Services Dominate the Economy',
    description: 'The 25 countries with the highest services value added as % of GDP. Post-industrial economies.',
    indicatorId: 'NV.SRV.TOTL.ZS',
    count: 25,
    direction: 'top',
    intro: 'A high services share indicates a mature, post-industrial economy. {#1} has services at {#1_value} of GDP.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-agriculture-share',
    title: 'Countries Where Agriculture Dominates GDP',
    description: 'The 25 countries with the highest agriculture value added as % of GDP. Agrarian economies.',
    indicatorId: 'NV.AGR.TOTL.ZS',
    count: 25,
    direction: 'top',
    intro: 'Agriculture-dominant economies are typically least developed. {#1} has agriculture at {#1_value} of GDP.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-most-foreign-aid',
    title: 'Countries Receiving the Most Foreign Aid (2026)',
    description: 'The 25 countries receiving the most Official Development Assistance (ODA) as % of GNI.',
    indicatorId: 'DT.ODA.ODAT.GN.ZS',
    count: 25,
    direction: 'top',
    intro: 'Foreign aid remains a significant income source for the world\'s poorest countries. {#1} receives ODA equal to {#1_value} of GNI.',
    category: 'Development',
  },

  // ── ROUND 4: 20 MORE POSTS ──────────────────────
  {
    slug: 'countries-with-lowest-life-expectancy',
    title: 'Countries with the Lowest Life Expectancy (2026)',
    description: 'The 25 countries where people live the shortest lives. Health crises and development challenges.',
    indicatorId: 'SP.DYN.LE00.IN',
    count: 25,
    direction: 'bottom',
    intro: 'Life expectancy below 60 reflects severe health, poverty, and conflict challenges. {#1} has the lowest at {#1_value} years.',
    category: 'Health',
  },
  {
    slug: 'countries-with-lowest-fertility-rate',
    title: 'Countries with the Lowest Fertility Rate (2026)',
    description: 'The 25 countries with the lowest birth rates. Demographic crisis and population decline.',
    indicatorId: 'SP.DYN.TFRT.IN',
    count: 25,
    direction: 'bottom',
    intro: 'Below-replacement fertility signals long-term population decline. {#1} has the world\'s lowest fertility at {#1_value} children per woman.',
    category: 'Demographics',
  },
  {
    slug: 'countries-with-most-tourism-revenue',
    title: 'Most Visited Countries in the World (2026)',
    description: 'The 25 most visited countries by international tourist arrivals.',
    indicatorId: 'ST.INT.ARVL',
    count: 25,
    direction: 'top',
    intro: 'International tourism generates over 10% of global GDP. {#1} leads with {#1_value} visitor arrivals annually.',
    category: 'Tourism',
  },
  {
    slug: 'countries-with-highest-manufacturing-share',
    title: 'Countries with the Largest Manufacturing Sectors (2026)',
    description: 'The 25 countries where manufacturing accounts for the most GDP. Industrial powerhouses.',
    indicatorId: 'NV.IND.MANF.ZS',
    count: 25,
    direction: 'top',
    intro: 'Manufacturing drives exports and employment. {#1} has the highest manufacturing share at {#1_value} of GDP.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-household-consumption',
    title: 'Countries with the Highest Consumer Spending (% GDP)',
    description: 'The 25 countries where household consumption accounts for the most GDP.',
    indicatorId: 'NE.CON.PRVT.ZS',
    count: 25,
    direction: 'top',
    intro: 'Consumer spending drives demand-led economies. {#1} has household consumption at {#1_value} of GDP.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-government-consumption',
    title: 'Countries with the Highest Government Consumption (% GDP)',
    description: 'The 25 countries where government spending on goods and services is highest.',
    indicatorId: 'NE.CON.GOVT.ZS',
    count: 25,
    direction: 'top',
    intro: 'Government consumption reflects public sector size. {#1} has the highest at {#1_value} of GDP.',
    category: 'Fiscal',
  },
  {
    slug: 'countries-with-highest-exports-gdp',
    title: 'Most Export-Dependent Economies (% of GDP)',
    description: 'The 25 countries where exports form the highest share of GDP. Trade-dependent economies.',
    indicatorId: 'NE.EXP.GNFS.ZS',
    count: 25,
    direction: 'top',
    intro: 'Export dependence reflects integration with global markets. {#1} exports {#1_value} of GDP — the most globally.',
    category: 'Trade',
  },
  {
    slug: 'countries-with-highest-imports-gdp',
    title: 'Most Import-Dependent Economies (% of GDP)',
    description: 'The 25 countries where imports form the highest share of GDP.',
    indicatorId: 'NE.IMP.GNFS.ZS',
    count: 25,
    direction: 'top',
    intro: 'High import dependence can signal either wealth (consuming global goods) or lack of domestic production. {#1} imports {#1_value} of GDP.',
    category: 'Trade',
  },
  {
    slug: 'countries-with-highest-rural-population',
    title: 'Countries with the Most Rural Population (2026)',
    description: 'The 25 most rural countries by percentage of population living outside cities.',
    indicatorId: 'SP.RUR.TOTL.ZS',
    count: 25,
    direction: 'top',
    intro: 'Highly rural countries depend on agriculture and face urbanization pressures. {#1} has {#1_value} rural population.',
    category: 'Demographics',
  },
  {
    slug: 'countries-with-highest-male-life-expectancy',
    title: 'Countries Where Men Live the Longest (2026)',
    description: 'The 25 countries with the highest male life expectancy.',
    indicatorId: 'SP.DYN.LE00.MA.IN',
    count: 25,
    direction: 'top',
    intro: 'Male life expectancy is 4-7 years shorter than female in most countries. {#1} has the highest male life expectancy at {#1_value} years.',
    category: 'Health',
  },
  {
    slug: 'countries-with-lowest-co2-per-capita',
    title: 'Countries with the Lowest Carbon Footprint per Person',
    description: 'The 25 countries emitting the least CO2 per capita. Many produce near-zero emissions.',
    indicatorId: 'EN.ATM.CO2E.PC',
    count: 25,
    direction: 'bottom',
    intro: 'Some countries emit almost no carbon per person. {#1} emits just {#1_value} metric tons per capita.',
    category: 'Environment',
  },
  {
    slug: 'countries-with-highest-labor-force',
    title: 'Countries with the Largest Labor Force (2026)',
    description: 'The 25 countries with the most workers. Labor supply and economic capacity.',
    indicatorId: 'SL.TLF.TOTL.IN',
    count: 25,
    direction: 'top',
    intro: 'Labor force size determines economic capacity. {#1} has the world\'s largest workforce at {#1_value}.',
    category: 'Labor',
  },
  {
    slug: 'countries-with-highest-labor-participation',
    title: 'Countries with the Highest Labor Force Participation Rate',
    description: 'The 25 countries where the most people of working age are economically active.',
    indicatorId: 'SL.TLF.CACT.ZS',
    count: 25,
    direction: 'top',
    intro: 'High labor participation signals an active workforce. {#1} leads at {#1_value}.',
    category: 'Labor',
  },
  {
    slug: 'countries-with-lowest-debt-to-gdp',
    title: 'Countries with the Least Government Debt (2026)',
    description: 'The 25 countries with the lowest government debt to GDP ratio. Fiscal strength.',
    indicatorId: 'IMF.GGXWDG_NGDP',
    count: 25,
    direction: 'bottom',
    intro: 'Some countries have virtually no government debt. {#1} has the lowest at {#1_value} of GDP.',
    category: 'Fiscal',
  },
  {
    slug: 'countries-with-highest-self-employment',
    title: 'Countries with the Most Self-Employed Workers (2026)',
    description: 'The 25 countries with the highest self-employment rate. Informal economy and entrepreneurship.',
    indicatorId: 'SL.TLF.CACT.NE.ZS',
    count: 25,
    direction: 'top',
    intro: 'High self-employment often reflects large informal economies. {#1} has {#1_value} self-employed workers.',
    category: 'Labor',
  },
  {
    slug: 'countries-with-highest-gdp-deflator',
    title: 'Countries with the Highest GDP Deflator (2026)',
    description: 'The 25 countries with the highest GDP deflator — a broad price-level measure.',
    indicatorId: 'NY.GDP.DEFL.KD.ZG',
    count: 25,
    direction: 'top',
    intro: 'The GDP deflator captures economy-wide price changes. {#1} has the highest at {#1_value}.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-gross-national-savings',
    title: 'Countries that Save the Most (% GDP, 2026)',
    description: 'The 25 countries with the highest gross national savings as % of GDP.',
    indicatorId: 'IMF.NGS_GDP',
    count: 25,
    direction: 'top',
    intro: 'High national savings fund domestic investment and reduce foreign dependence. {#1} saves {#1_value} of GDP.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-total-investment',
    title: 'Countries Investing the Most in Their Future (% GDP)',
    description: 'The 25 countries with the highest total investment (gross fixed capital formation) as % of GDP.',
    indicatorId: 'IMF.NI_GDP',
    count: 25,
    direction: 'top',
    intro: 'Investment builds future productive capacity. {#1} invests {#1_value} of GDP — the highest rate globally.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-world-gdp-share',
    title: 'Countries with the Largest Share of World GDP (PPP)',
    description: 'The 25 countries that account for the most global economic output in PPP terms.',
    indicatorId: 'IMF.PPPSH',
    count: 25,
    direction: 'top',
    intro: 'Global economic power is concentrated. {#1} accounts for {#1_value} of world GDP in PPP terms.',
    category: 'Economy',
  },
  {
    slug: 'countries-with-highest-gdp-per-worker',
    title: 'Countries with the Highest Productivity per Worker (2026)',
    description: 'The 25 most productive countries by GDP per person employed.',
    indicatorId: 'SL.GDP.PCAP.EM.KD',
    count: 25,
    direction: 'top',
    intro: 'Labor productivity drives prosperity. {#1} has the highest GDP per worker at {#1_value}.',
    category: 'Economy',
  },
];

export function getBlogPost(slug: string): BlogPostDef | undefined {
  return BLOG_POSTS.find(p => p.slug === slug);
}
