export interface GlossaryTerm {
  slug: string;
  term: string;
  definition: string;
  explanation: string;
  rankingSlug?: string;
  related: string[]; // other term slugs
  category: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    slug: 'gdp',
    term: 'GDP (Gross Domestic Product)',
    definition: 'The total monetary value of all goods and services produced within a country\'s borders in a given period, usually a year.',
    explanation: 'GDP is the most widely used measure of economic output. It includes consumer spending, government expenditure, business investment, and net exports. GDP can be measured in nominal terms (current prices) or real terms (adjusted for inflation). The United States, China, and Japan have the three largest GDPs in the world.',
    rankingSlug: 'gdp',
    related: ['gdp-per-capita', 'gdp-ppp', 'gdp-growth-rate', 'gni'],
    category: 'Economy',
  },
  {
    slug: 'gdp-per-capita',
    term: 'GDP per Capita',
    definition: 'A country\'s total economic output (GDP) divided by its population, giving a rough measure of average economic output per person.',
    explanation: 'GDP per capita is often used as a proxy for average living standards. A country can have a large GDP but low GDP per capita if its population is large (e.g., India). Conversely, small wealthy nations like Luxembourg or Singapore have very high GDP per capita. It does not account for income distribution — two countries with the same GDP per capita may have very different levels of inequality.',
    rankingSlug: 'gdp-per-capita',
    related: ['gdp', 'gdp-ppp', 'gini-index', 'poverty-rate'],
    category: 'Economy',
  },
  {
    slug: 'gdp-ppp',
    term: 'GDP (PPP) — Purchasing Power Parity',
    definition: 'GDP adjusted for price differences between countries, allowing a fairer comparison of real economic output and living standards.',
    explanation: 'A dollar buys more in India than in Switzerland. PPP adjusts for these price differences using a "basket of goods" comparison. By PPP, China\'s economy is larger than the United States\'. GDP per capita PPP is considered the best single measure for comparing living standards across countries.',
    rankingSlug: 'gdp-ppp',
    related: ['gdp', 'gdp-per-capita', 'purchasing-power-parity'],
    category: 'Economy',
  },
  {
    slug: 'gdp-growth-rate',
    term: 'GDP Growth Rate',
    definition: 'The annual percentage change in a country\'s real GDP, measuring how fast an economy is expanding or contracting.',
    explanation: 'Real GDP growth adjusts for inflation, showing actual increases in economic output. Developing economies often grow faster (5-10%) while advanced economies typically grow 1-3%. Negative growth indicates a recession. The IMF publishes GDP growth estimates and forecasts in its World Economic Outlook.',
    rankingSlug: 'gdp-growth',
    related: ['gdp', 'inflation-rate', 'recession'],
    category: 'Economy',
  },
  {
    slug: 'gni',
    term: 'GNI (Gross National Income)',
    definition: 'The total income earned by a country\'s residents, including income from abroad, minus income sent to other countries.',
    explanation: 'While GDP measures production within borders, GNI measures income earned by nationals regardless of where they work. For countries with large diaspora populations sending remittances home, GNI can differ significantly from GDP. The World Bank uses GNI per capita to classify countries as low-income, middle-income, or high-income.',
    related: ['gdp', 'gdp-per-capita'],
    category: 'Economy',
  },
  {
    slug: 'inflation-rate',
    term: 'Inflation Rate',
    definition: 'The annual percentage increase in the general price level of goods and services in an economy.',
    explanation: 'Inflation erodes purchasing power — if inflation is 10%, something that cost $100 last year costs $110 today. Most central banks target 2% inflation as a healthy level. Hyperinflation (>50% monthly) can collapse economies, as seen historically in Zimbabwe and Venezuela. The CPI (Consumer Price Index) is the most common measure.',
    rankingSlug: 'inflation-rate',
    related: ['cpi', 'monetary-policy', 'central-bank'],
    category: 'Economy',
  },
  {
    slug: 'cpi',
    term: 'CPI (Consumer Price Index)',
    definition: 'A measure that tracks changes in the price of a representative basket of consumer goods and services over time.',
    explanation: 'The CPI is the primary tool for measuring inflation from a consumer\'s perspective. It tracks prices of food, housing, transportation, healthcare, and other essentials. Central banks and governments use CPI to adjust monetary policy, wages, tax brackets, and social benefits. Different countries weight their baskets differently based on local consumption patterns.',
    related: ['inflation-rate', 'monetary-policy', 'purchasing-power-parity'],
    category: 'Economy',
  },
  {
    slug: 'unemployment-rate',
    term: 'Unemployment Rate',
    definition: 'The percentage of the labor force that is actively seeking work but unable to find employment.',
    explanation: 'The unemployment rate only counts people who are actively looking for work. It excludes discouraged workers who have stopped searching and underemployed workers in part-time jobs. A rate below 4-5% is generally considered "full employment." Youth unemployment (ages 15-24) is typically much higher than the overall rate.',
    rankingSlug: 'unemployment-rate',
    related: ['gdp-growth-rate', 'inflation-rate'],
    category: 'Economy',
  },
  {
    slug: 'government-debt-to-gdp',
    term: 'Government Debt-to-GDP Ratio',
    definition: 'Total government debt expressed as a percentage of GDP, indicating a country\'s ability to pay back its obligations.',
    explanation: 'A debt-to-GDP ratio over 100% means a country owes more than its annual economic output. Japan leads the world at over 250%. However, debt sustainability depends on interest rates, currency, and growth — Japan borrows cheaply in yen from domestic lenders, while developing countries borrowing in USD face more risk. The IMF recommends keeping debt below 60% of GDP for emerging markets.',
    rankingSlug: 'government-debt',
    related: ['fiscal-balance', 'sovereign-debt', 'current-account-balance'],
    category: 'Economy',
  },
  {
    slug: 'current-account-balance',
    term: 'Current Account Balance',
    definition: 'The difference between a country\'s total exports and total imports of goods, services, income, and transfers.',
    explanation: 'A current account surplus means a country exports more than it imports (e.g., Germany, China). A deficit means it imports more (e.g., the United States). Persistent large deficits can indicate over-consumption or lack of competitiveness, while persistent surpluses may indicate under-consumption. The current account is one component of the balance of payments.',
    rankingSlug: 'current-account',
    related: ['trade-openness', 'balance-of-payments', 'fdi'],
    category: 'Economy',
  },
  {
    slug: 'fiscal-balance',
    term: 'Fiscal Balance (Budget Surplus/Deficit)',
    definition: 'The difference between a government\'s revenue and its expenditure in a given year, expressed as a percentage of GDP.',
    explanation: 'A positive fiscal balance (surplus) means the government collects more than it spends. A negative balance (deficit) means it borrows to cover the gap. Most governments run deficits, which accumulate into national debt over time. During recessions, deficits tend to widen as tax revenue falls and social spending rises.',
    related: ['government-debt-to-gdp', 'monetary-policy'],
    category: 'Economy',
  },
  {
    slug: 'trade-openness',
    term: 'Trade Openness',
    definition: 'Total trade (exports + imports) as a percentage of GDP, measuring how integrated an economy is with global markets.',
    explanation: 'Highly trade-open economies like Singapore (trade > 300% of GDP) depend heavily on international commerce. Larger economies like the US tend to be less trade-open because domestic consumption drives most GDP. Trade openness has generally increased over time due to globalization, though trade wars and protectionism can reverse this trend.',
    rankingSlug: 'trade-openness',
    related: ['current-account-balance', 'fdi', 'gdp'],
    category: 'Economy',
  },
  {
    slug: 'fdi',
    term: 'FDI (Foreign Direct Investment)',
    definition: 'Investment by a company or individual in one country into business interests in another country, typically involving significant ownership or control.',
    explanation: 'FDI includes building factories, acquiring companies, or establishing joint ventures abroad. It differs from portfolio investment (buying stocks/bonds) because it involves lasting interest and management influence. High FDI inflows signal confidence in an economy. China, the US, and the EU are the world\'s largest FDI destinations.',
    rankingSlug: 'fdi-inflows',
    related: ['trade-openness', 'current-account-balance', 'gdp-growth-rate'],
    category: 'Economy',
  },
  {
    slug: 'gini-index',
    term: 'Gini Index (Gini Coefficient)',
    definition: 'A statistical measure of income inequality within a population, ranging from 0 (perfect equality) to 100 (maximum inequality).',
    explanation: 'A Gini of 0 means everyone earns the same; 100 means one person earns everything. Most countries fall between 25-60. Nordic countries (Sweden, Norway) have low Gini scores (~27), while South Africa and some Latin American countries exceed 50. The Gini index does not capture wealth inequality, which tends to be far more extreme than income inequality.',
    rankingSlug: 'gini-index',
    related: ['poverty-rate', 'gdp-per-capita'],
    category: 'Inequality',
  },
  {
    slug: 'poverty-rate',
    term: 'Poverty Rate (International Poverty Line)',
    definition: 'The percentage of a population living below the international poverty line of $2.15 per day (2017 PPP).',
    explanation: 'The World Bank sets the international poverty line at $2.15/day, updated for purchasing power. By this measure, global extreme poverty has fallen dramatically — from 36% in 1990 to under 10% today. However, higher thresholds ($3.65, $6.85/day) show much more poverty. Sub-Saharan Africa has the highest concentration of extreme poverty.',
    rankingSlug: 'poverty-rate',
    related: ['gini-index', 'gdp-per-capita', 'life-expectancy'],
    category: 'Inequality',
  },
  {
    slug: 'life-expectancy',
    term: 'Life Expectancy at Birth',
    definition: 'The average number of years a newborn is expected to live, based on current mortality rates.',
    explanation: 'Life expectancy is one of the most powerful indicators of development. It reflects healthcare access, nutrition, sanitation, conflict, and poverty. The global average is about 73 years, but ranges from 85+ in Japan and Monaco to under 55 in some sub-Saharan African countries. Women live longer than men in virtually every country.',
    rankingSlug: 'life-expectancy',
    related: ['infant-mortality', 'fertility-rate', 'poverty-rate'],
    category: 'Health',
  },
  {
    slug: 'fertility-rate',
    term: 'Total Fertility Rate',
    definition: 'The average number of children a woman would have over her lifetime based on current birth rates.',
    explanation: 'A fertility rate of 2.1 is the "replacement level" — the rate needed to maintain a stable population without migration. Most developed countries are well below replacement (South Korea is at ~0.7), while sub-Saharan Africa averages over 4.5. Low fertility leads to aging populations, labor shortages, and pension crises.',
    rankingSlug: 'fertility-rate',
    related: ['life-expectancy', 'population-growth', 'infant-mortality'],
    category: 'Demographics',
  },
  {
    slug: 'infant-mortality',
    term: 'Infant Mortality Rate',
    definition: 'The number of deaths of children under age 5 per 1,000 live births.',
    explanation: 'Infant mortality is one of the starkest indicators of development. It reflects access to clean water, nutrition, healthcare, and maternal care. Rates range from under 3 per 1,000 in Scandinavian countries to over 100 in parts of sub-Saharan Africa. Global infant mortality has dropped by over 50% since 1990.',
    rankingSlug: 'infant-mortality',
    related: ['life-expectancy', 'fertility-rate', 'poverty-rate'],
    category: 'Health',
  },
  {
    slug: 'population-growth',
    term: 'Population Growth Rate',
    definition: 'The annual percentage change in a country\'s total population, including births, deaths, and net migration.',
    explanation: 'Population growth is driven by the balance of births minus deaths (natural increase) plus net migration. Many developed countries have near-zero or negative natural growth, sustained only by immigration. The fastest-growing populations are in sub-Saharan Africa, while Eastern European and East Asian countries are shrinking.',
    rankingSlug: 'population-growth',
    related: ['fertility-rate', 'life-expectancy', 'urban-population'],
    category: 'Demographics',
  },
  {
    slug: 'urban-population',
    term: 'Urban Population',
    definition: 'The share of a country\'s population living in urban areas, as defined by national statistical offices.',
    explanation: 'Over 56% of the world\'s population now lives in cities — up from 30% in 1950, projected to reach 68% by 2050. Urbanization drives economic growth through agglomeration effects but also creates challenges: housing, pollution, inequality, and infrastructure strain. The most urbanized countries include city-states like Singapore (100%) and Monaco.',
    rankingSlug: 'urban-population',
    related: ['population-growth', 'gdp-per-capita'],
    category: 'Demographics',
  },
  {
    slug: 'co2-emissions',
    term: 'CO₂ Emissions per Capita',
    definition: 'The total amount of carbon dioxide emitted per person per year, measured in metric tonnes.',
    explanation: 'Per capita CO₂ emissions measure a country\'s climate impact relative to its population. Oil-producing Gulf states have the highest per capita emissions (>30 tonnes), while most African countries emit less than 1 tonne per person. Total emissions are dominated by China and the United States. Reducing per capita emissions is central to meeting Paris Agreement targets.',
    rankingSlug: 'co2-emissions',
    related: ['renewable-energy', 'gdp-per-capita'],
    category: 'Environment',
  },
  {
    slug: 'renewable-energy',
    term: 'Renewable Energy Share',
    definition: 'The percentage of total energy consumption derived from renewable sources: hydro, solar, wind, geothermal, and biomass.',
    explanation: 'Countries like Iceland (nearly 100%) and Norway (>70%) lead in renewable energy thanks to abundant hydropower and geothermal resources. Globally, renewables account for about 18% of final energy consumption. Solar and wind are growing fastest, but fossil fuels still dominate. The energy transition is critical for meeting climate targets.',
    rankingSlug: 'renewable-energy',
    related: ['co2-emissions'],
    category: 'Environment',
  },
  {
    slug: 'purchasing-power-parity',
    term: 'Purchasing Power Parity (PPP)',
    definition: 'A theory and method that adjusts exchange rates to equalize the purchasing power of different currencies.',
    explanation: 'PPP answers the question: "How much does $1 actually buy in different countries?" If a Big Mac costs $5 in the US but $2.50 in India, the PPP exchange rate is 2:1, meaning India\'s prices are half of US prices. The World Bank and IMF use PPP-adjusted figures to compare economies more fairly than market exchange rates allow.',
    related: ['gdp-ppp', 'gdp-per-capita', 'cpi'],
    category: 'Economy',
  },
  {
    slug: 'monetary-policy',
    term: 'Monetary Policy',
    definition: 'Actions by a central bank to manage the money supply and interest rates to influence economic activity.',
    explanation: 'Monetary policy has two main tools: interest rates and quantitative easing/tightening. Raising rates slows inflation but can reduce growth; cutting rates stimulates growth but risks inflation. The US Federal Reserve, European Central Bank, and Bank of Japan are the most influential central banks. "Hawkish" policy means tightening; "dovish" means easing.',
    related: ['inflation-rate', 'central-bank', 'cpi'],
    category: 'Economy',
  },
  {
    slug: 'central-bank',
    term: 'Central Bank',
    definition: 'A national institution responsible for managing a country\'s currency, money supply, and interest rates.',
    explanation: 'Central banks like the Federal Reserve (US), ECB (Europe), and Bank of Japan control monetary policy, regulate commercial banks, and act as lenders of last resort. Their interest rate decisions impact everything from mortgage rates to stock markets. Independence from political pressure is considered crucial for maintaining price stability.',
    related: ['monetary-policy', 'inflation-rate'],
    category: 'Economy',
  },
  {
    slug: 'credit-rating',
    term: 'Sovereign Credit Rating',
    definition: 'An assessment by rating agencies (S&P, Moody\'s, Fitch) of a government\'s ability and willingness to repay its debts.',
    explanation: 'Ratings range from AAA (highest quality, lowest risk) to D (default). Higher ratings mean lower borrowing costs. A downgrade can increase interest payments by billions. The US, Germany, and Singapore hold top ratings, while countries in default or near-default receive the lowest. Ratings are controversial — agencies were criticized for failing to predict the 2008 financial crisis.',
    related: ['government-debt-to-gdp', 'sovereign-debt', 'fiscal-balance'],
    category: 'Economy',
  },
  {
    slug: 'sovereign-debt',
    term: 'Sovereign Debt',
    definition: 'The total amount of money a national government has borrowed, including domestic and foreign-denominated bonds.',
    explanation: 'Sovereign debt is issued through government bonds (e.g., US Treasuries, Japanese Government Bonds). It can be denominated in domestic currency (lower risk, can be inflated away) or foreign currency (higher risk, can lead to debt crises). The global sovereign debt market exceeds $70 trillion. A sovereign debt crisis occurs when a government cannot service its obligations.',
    related: ['government-debt-to-gdp', 'credit-rating', 'fiscal-balance'],
    category: 'Economy',
  },
  {
    slug: 'balance-of-payments',
    term: 'Balance of Payments',
    definition: 'A comprehensive record of all economic transactions between a country\'s residents and the rest of the world.',
    explanation: 'The balance of payments has three components: the current account (trade in goods/services), the capital account (asset transfers), and the financial account (investment flows). By definition, the overall balance of payments must equal zero — a current account deficit must be financed by a financial account surplus (capital inflows). Persistent imbalances can signal economic vulnerabilities.',
    related: ['current-account-balance', 'trade-openness', 'fdi'],
    category: 'Economy',
  },
  {
    slug: 'hdi',
    term: 'HDI (Human Development Index)',
    definition: 'A composite index measuring average achievement in three dimensions: health (life expectancy), education, and standard of living (GNI per capita).',
    explanation: 'Created by the UNDP, the HDI ranges from 0 to 1. Countries above 0.8 are "very high human development" (Norway, Switzerland, Iceland lead). The HDI is useful because it goes beyond pure economic output to include health and education outcomes. However, it doesn\'t capture inequality, sustainability, or political freedom.',
    related: ['life-expectancy', 'gdp-per-capita', 'gini-index'],
    category: 'Development',
  },
  {
    slug: 'recession',
    term: 'Recession',
    definition: 'A significant, widespread, and prolonged decline in economic activity, commonly defined as two consecutive quarters of negative GDP growth.',
    explanation: 'Recessions are characterized by falling output, rising unemployment, declining consumer spending, and reduced business investment. The 2008 Global Financial Crisis and the 2020 COVID-19 downturn are recent examples. Central banks respond with rate cuts and stimulus, while governments increase spending. The NBER (US) officially declares recessions, often months after they begin.',
    related: ['gdp-growth-rate', 'unemployment-rate', 'monetary-policy'],
    category: 'Economy',
  },
  {
    slug: 'nominal-gdp',
    term: 'Nominal GDP',
    definition: 'GDP measured at current market prices without adjusting for inflation. Expressed in a common currency (usually US dollars) for international comparison.',
    explanation: 'Nominal GDP reflects both changes in real output and changes in prices. When comparing countries, nominal GDP in US dollars is affected by exchange rate movements — a country\'s GDP can shrink in dollar terms even while its domestic economy grows, simply because its currency weakened. Despite this limitation, nominal GDP is the standard measure for comparing the size of national economies.',
    rankingSlug: 'gdp',
    related: ['gdp', 'gdp-ppp', 'real-gdp'],
    category: 'Economy',
  },
  {
    slug: 'real-gdp',
    term: 'Real GDP',
    definition: 'GDP adjusted for inflation, measuring the actual quantity of goods and services produced. Changes in real GDP represent actual growth in economic output.',
    explanation: 'Real GDP removes the effect of price changes, isolating genuine changes in production. If nominal GDP grows 7% but inflation is 4%, real GDP growth is roughly 3%. This makes real GDP essential for tracking actual economic performance over time. Central banks and policymakers focus on real GDP when assessing economic health.',
    related: ['gdp', 'nominal-gdp', 'gdp-growth-rate', 'inflation'],
    category: 'Economy',
  },
  {
    slug: 'central-bank',
    term: 'Central Bank',
    definition: 'A national institution responsible for monetary policy, currency issuance, and financial system stability. Examples: the Federal Reserve (US), ECB (Europe), Bank of Japan.',
    explanation: 'Central banks control interest rates, manage inflation, and serve as lenders of last resort to commercial banks. The US Federal Reserve is the world\'s most influential central bank because the dollar is the global reserve currency. Central bank independence from political interference is considered essential for credible monetary policy. Key tools include policy interest rates, open market operations, and quantitative easing.',
    related: ['monetary-policy', 'inflation', 'interest-rate'],
    category: 'Economy',
  },
  {
    slug: 'interest-rate',
    term: 'Interest Rate (Policy Rate)',
    definition: 'The rate set by a central bank at which commercial banks can borrow money, which in turn influences all other interest rates in the economy.',
    explanation: 'When a central bank raises interest rates, borrowing becomes more expensive, slowing spending and investment — which helps control inflation. When rates are cut, borrowing is cheaper, stimulating economic activity. The US federal funds rate, ECB deposit rate, and Bank of England base rate are the most watched policy rates globally. Near-zero or negative interest rates were common in the 2010s but were abandoned during the post-pandemic inflation surge.',
    related: ['central-bank', 'monetary-policy', 'inflation'],
    category: 'Economy',
  },
  {
    slug: 'exchange-rate',
    term: 'Exchange Rate',
    definition: 'The price at which one currency can be exchanged for another. Determines the international value of a nation\'s money.',
    explanation: 'Exchange rates are either floating (determined by market forces, like USD/EUR) or fixed/pegged (set by the government, like the Saudi riyal). A strong currency makes imports cheaper but exports more expensive. Currency depreciation can boost exports but increases the cost of imported goods and foreign debt repayment. Major currency pairs include EUR/USD, USD/JPY, and GBP/USD.',
    related: ['gdp', 'trade-balance', 'monetary-policy'],
    category: 'Economy',
  },
  {
    slug: 'trade-balance',
    term: 'Trade Balance',
    definition: 'The difference between a country\'s exports and imports. A surplus means exports exceed imports; a deficit means the opposite.',
    explanation: 'Germany, China, and Japan typically run large trade surpluses, while the US and UK run deficits. A trade surplus isn\'t inherently "good" — it can reflect weak domestic demand. A trade deficit isn\'t inherently "bad" — it can reflect strong consumer spending and investment. The trade balance is a major component of the current account, which includes all international transactions.',
    rankingSlug: 'current-account',
    related: ['current-account-balance', 'gdp', 'exchange-rate'],
    category: 'Trade',
  },
  {
    slug: 'quantitative-easing',
    term: 'Quantitative Easing (QE)',
    definition: 'A monetary policy tool where a central bank purchases government bonds or other financial assets to inject money into the economy and lower long-term interest rates.',
    explanation: 'QE was pioneered by the Bank of Japan in 2001 and used extensively by the Federal Reserve, ECB, and Bank of England after the 2008 financial crisis and during COVID-19. By buying bonds, central banks push down yields, making borrowing cheaper and encouraging investment. Critics argue QE inflates asset prices (stocks, real estate) and benefits the wealthy disproportionately. The reverse process — "quantitative tightening" — involves selling bonds to drain money from the financial system.',
    related: ['central-bank', 'monetary-policy', 'interest-rate'],
    category: 'Economy',
  },
  {
    slug: 'fiscal-policy',
    term: 'Fiscal Policy',
    definition: 'Government decisions about taxation and spending used to influence the economy. Expansionary fiscal policy involves increased spending or tax cuts; contractionary involves the opposite.',
    explanation: 'Fiscal policy is the responsibility of elected governments, unlike monetary policy which is managed by central banks. During recessions, governments typically increase spending and cut taxes to stimulate demand (Keynesian economics). The challenge is that fiscal stimulus often increases government debt. The balance between fiscal stimulus and debt sustainability is one of the central debates in economics.',
    related: ['government-debt', 'gdp-growth-rate', 'monetary-policy', 'recession'],
    category: 'Economy',
  },
  {
    slug: 'demographic-dividend',
    term: 'Demographic Dividend',
    definition: 'The economic growth boost that occurs when a country\'s working-age population grows faster than its dependent population (children and elderly).',
    explanation: 'The demographic dividend occurs during the transition from high to low fertility rates. For a period, the share of working-age adults increases relative to dependents, potentially boosting savings, investment, and GDP growth. East Asia\'s rapid growth from 1970-2010 is partly attributed to this dividend. India and parts of Africa are currently in their dividend phase. However, the dividend is not automatic — it requires productive employment for the growing workforce.',
    related: ['population-growth-rate', 'fertility-rate', 'life-expectancy'],
    category: 'Demographics',
  },
  {
    slug: 'sanctions',
    term: 'Economic Sanctions',
    definition: 'Penalties imposed by one country or group of countries on another, restricting trade, financial transactions, or other economic activity, typically to achieve foreign policy or security objectives.',
    explanation: 'Sanctions range from targeted measures (freezing specific individuals\' assets) to comprehensive trade embargoes. Russia, Iran, North Korea, and Venezuela are among the most heavily sanctioned countries. The effectiveness of sanctions is debated: they can constrain economies but often hurt civilian populations and may push countries toward alternative trading partners (e.g., Russia pivoting to China). SWIFT disconnection — removing a country from the global banking messaging system — is one of the most powerful sanctions tools.',
    related: ['trade-balance', 'gdp', 'exchange-rate'],
    category: 'Geopolitics',
  },
  {
    slug: 'middle-income-trap',
    term: 'Middle-Income Trap',
    definition: 'The phenomenon where a country\'s growth stalls after reaching middle-income status, unable to compete with low-wage economies in manufacturing or with advanced economies in innovation.',
    explanation: 'Countries that industrialize quickly through low-cost manufacturing often struggle to transition to higher-value production as wages rise. Only a handful of economies have successfully escaped the trap: South Korea, Taiwan, Singapore, and a few others. China is currently testing whether the world\'s largest middle-income country can break through. Latin American countries like Brazil and Mexico have been stuck at middle-income levels for decades.',
    related: ['gdp-per-capita', 'gdp-growth-rate'],
    category: 'Development',
  },
  // ── ROUND 2: 25 MORE TERMS ──────────────────────
  {
    slug: 'purchasing-power-parity',
    term: 'Purchasing Power Parity (PPP)',
    definition: 'An economic theory and measurement that adjusts exchange rates to equalize the purchasing power of different currencies.',
    explanation: 'PPP conversion factors are calculated by the International Comparison Program (ICP), which surveys prices of thousands of goods across countries. The "Big Mac Index" popularized by The Economist is a simplified PPP measure. PPP is essential for comparing living standards because $1 buys very different amounts in different countries. In PPP terms, China\'s economy surpasses America\'s.',
    related: ['gdp-ppp', 'gdp-per-capita', 'exchange-rate'],
    category: 'Economy',
  },
  {
    slug: 'recession',
    term: 'Recession',
    definition: 'A significant decline in economic activity lasting more than a few months, typically identified by two consecutive quarters of negative GDP growth.',
    explanation: 'Recessions are characterized by falling GDP, rising unemployment, declining consumer spending, and reduced business investment. The NBER (National Bureau of Economic Research) officially dates US recessions. Major global recessions include 2008-09 (Global Financial Crisis) and 2020 (COVID-19). Central banks typically respond by cutting interest rates, and governments increase spending to stimulate the economy.',
    related: ['gdp-growth-rate', 'unemployment-rate', 'central-bank'],
    category: 'Economy',
  },
  {
    slug: 'stagflation',
    term: 'Stagflation',
    definition: 'An economic condition combining stagnant growth, high unemployment, and high inflation — a situation that standard economic tools struggle to address.',
    explanation: 'Stagflation was first identified during the 1970s oil crises when OPEC embargoes caused energy prices to spike, simultaneously raising inflation and causing recession. It\'s a policy nightmare because the standard response to inflation (higher interest rates) worsens unemployment, while the standard response to recession (lower rates) worsens inflation. Turkey and Argentina have experienced stagflation-like conditions in recent years.',
    related: ['inflation-rate', 'gdp-growth-rate', 'unemployment-rate'],
    category: 'Economy',
  },
  {
    slug: 'sovereign-wealth-fund',
    term: 'Sovereign Wealth Fund',
    definition: 'A state-owned investment fund financed by government revenue, typically from commodity exports, used to invest in global assets for future generations.',
    explanation: 'The world\'s largest sovereign wealth fund is Norway\'s Government Pension Fund Global ($1.7T+), funded by oil revenue. Other major funds include Abu Dhabi Investment Authority, China Investment Corporation, and Saudi Arabia\'s Public Investment Fund. SWFs serve as stabilization buffers and intergenerational wealth transfer mechanisms. They collectively manage over $10 trillion globally.',
    related: ['gdp', 'fiscal-policy'],
    category: 'Finance',
  },
  {
    slug: 'current-account-balance',
    term: 'Current Account Balance',
    definition: 'The difference between a country\'s total exports and total imports of goods, services, income, and transfers. A surplus means a country earns more from abroad than it spends.',
    explanation: 'Germany, China, Japan, and Gulf states run large surpluses (they export more than they import). The United States runs the world\'s largest deficit (~$800B annually), financed by selling financial assets to foreign investors. Persistent large deficits can indicate a country is living beyond its means, while persistent surpluses may reflect suppressed domestic consumption.',
    rankingSlug: 'current-account',
    related: ['trade-balance', 'gdp', 'exchange-rate'],
    category: 'Trade',
  },
  {
    slug: 'foreign-direct-investment',
    term: 'Foreign Direct Investment (FDI)',
    definition: 'Investment from a company or individual in one country into business operations or assets in another country, involving lasting management interest (typically 10%+ ownership).',
    explanation: 'FDI differs from portfolio investment (buying stocks/bonds) because it represents a lasting commitment to operating in the host country. FDI brings capital, technology, and management practices. The United States, China, and Singapore are among the largest FDI recipients. FDI inflows as a percentage of GDP are tracked by the World Bank.',
    related: ['gdp-growth-rate', 'trade-balance'],
    category: 'Trade',
  },
  {
    slug: 'gini-index',
    term: 'Gini Index (Gini Coefficient)',
    definition: 'A statistical measure of income inequality on a scale from 0 (perfect equality) to 100 (perfect inequality).',
    explanation: 'The Gini index is calculated from the Lorenz curve, which plots cumulative income share against cumulative population share. Nordic countries score 25-30 (low inequality), the US and China score 35-40 (moderate), and South Africa scores ~63 (extreme inequality). The index captures income but not wealth inequality, which is typically much more extreme.',
    rankingSlug: 'gini-index',
    related: ['gdp-per-capita', 'poverty-rate'],
    category: 'Social',
  },
  {
    slug: 'poverty-rate',
    term: 'Poverty Rate (International Poverty Line)',
    definition: 'The share of a country\'s population living below the World Bank\'s international poverty line of $2.15 per day in 2017 PPP terms.',
    explanation: 'Global extreme poverty has fallen from 36% in 1990 to under 9% today, driven by China\'s and India\'s economic growth. Sub-Saharan Africa now accounts for 60%+ of the world\'s extreme poor. The World Bank also tracks higher thresholds: $3.65/day (lower-middle-income) and $6.85/day (upper-middle-income). By the $6.85 threshold, nearly half the world is poor.',
    rankingSlug: 'poverty-rate',
    related: ['gini-index', 'gdp-per-capita', 'life-expectancy'],
    category: 'Social',
  },
  {
    slug: 'labor-force-participation',
    term: 'Labor Force Participation Rate',
    definition: 'The percentage of the working-age population (typically 15-64) that is either employed or actively seeking employment.',
    explanation: 'This rate captures both employed and unemployed workers — people who have left the workforce entirely (retirees, students, discouraged workers) are excluded. Female labor force participation varies enormously — from above 80% in Nordic countries to below 20% in some Middle Eastern nations. Low participation can mask true employment problems better than the headline unemployment rate.',
    related: ['unemployment-rate', 'gdp-per-capita'],
    category: 'Labor',
  },
  {
    slug: 'human-development-index',
    term: 'Human Development Index (HDI)',
    definition: 'A composite index of life expectancy, education (mean and expected years of schooling), and per capita income, published by the UN Development Programme.',
    explanation: 'HDI was developed by economist Mahbub ul Haq as an alternative to GDP for measuring national development. It ranges from 0 to 1. Norway, Switzerland, and Iceland consistently rank highest. HDI reveals disparities invisible in GDP — Saudi Arabia has high income but lower education and health metrics, while Cuba has high health/education but low income.',
    related: ['gdp-per-capita', 'life-expectancy'],
    category: 'Development',
  },
  {
    slug: 'debt-to-gdp-ratio',
    term: 'Debt-to-GDP Ratio',
    definition: 'A country\'s total government debt expressed as a percentage of its gross domestic product, measuring fiscal sustainability.',
    explanation: 'Japan leads at 250%+ of GDP, followed by Greece, Italy, and the United States (120%+). Whether high debt is dangerous depends on interest rates, growth rates, currency, and institutional credibility. The US can sustain high debt because of dollar reserve status; Greece needed bailouts at similar levels. The IMF considers 60% a common benchmark for advanced economies.',
    rankingSlug: 'government-debt',
    related: ['gdp', 'fiscal-policy', 'interest-rate'],
    category: 'Fiscal',
  },
  {
    slug: 'consumer-price-index',
    term: 'Consumer Price Index (CPI)',
    definition: 'A measure of the average change over time in the prices paid by consumers for a representative basket of goods and services.',
    explanation: 'CPI is the most widely used measure of inflation. Statistical agencies survey prices of hundreds of goods and services (food, housing, transportation, healthcare) and weight them by consumption patterns. Core CPI excludes volatile food and energy prices. CPI is used to adjust wages, pensions, tax brackets, and government benefits for inflation.',
    related: ['inflation-rate', 'central-bank'],
    category: 'Economy',
  },
  {
    slug: 'yield-curve',
    term: 'Yield Curve',
    definition: 'A graph showing the relationship between bond yields and their maturities, typically for government bonds. A normal curve slopes upward; an inverted curve signals recession risk.',
    explanation: 'When short-term rates exceed long-term rates (inversion), it historically precedes recessions with high accuracy — the 2/10 spread (2-year vs 10-year Treasury) has inverted before every US recession since 1955. The yield curve reflects market expectations for growth, inflation, and central bank policy. A steep curve suggests optimism; a flat or inverted curve suggests caution.',
    related: ['interest-rate', 'recession', 'central-bank'],
    category: 'Finance',
  },
  {
    slug: 'reserve-currency',
    term: 'Reserve Currency',
    definition: 'A currency held in significant quantities by central banks and institutions worldwide as part of their foreign exchange reserves.',
    explanation: 'The US dollar is the dominant reserve currency (~58% of global reserves), followed by the euro (~20%), yen, and pound. Reserve currency status gives the US "exorbitant privilege" — the ability to borrow cheaply and run large deficits because global demand for dollars is built into the system. China\'s renminbi remains a small share (~2.5%) despite China\'s economic size, reflecting capital controls and limited convertibility.',
    related: ['exchange-rate', 'central-bank', 'current-account-balance'],
    category: 'Finance',
  },
  {
    slug: 'supply-chain',
    term: 'Supply Chain',
    definition: 'The network of organizations, people, activities, information, and resources involved in producing and delivering a product from raw materials to the end consumer.',
    explanation: 'Global supply chains became a mainstream topic during COVID-19 when disruptions caused shortages of everything from semiconductors to toilet paper. "Nearshoring" (moving production closer to consumers), "friend-shoring" (sourcing from allied countries), and diversification away from China have become major trends. The semiconductor supply chain — concentrated in Taiwan (TSMC) and South Korea (Samsung) — is considered the most strategically vulnerable.',
    related: ['trade-balance', 'foreign-direct-investment'],
    category: 'Trade',
  },
  {
    slug: 'monetary-policy',
    term: 'Monetary Policy',
    definition: 'Actions by a central bank to control the money supply and interest rates to achieve macroeconomic objectives like price stability and full employment.',
    explanation: 'Central banks use interest rate changes as their primary tool — raising rates to fight inflation (making borrowing expensive) and lowering rates to stimulate growth (making borrowing cheap). Quantitative easing (QE) — buying government bonds to inject money into the economy — became standard after 2008. The Fed, ECB, and Bank of Japan are the most influential central banks globally.',
    related: ['central-bank', 'interest-rate', 'inflation-rate', 'quantitative-easing'],
    category: 'Fiscal',
  },
  {
    slug: 'balance-of-payments',
    term: 'Balance of Payments',
    definition: 'A comprehensive record of all economic transactions between residents of a country and the rest of the world during a specific period.',
    explanation: 'The balance of payments has two main components: the current account (trade in goods and services, income, transfers) and the capital/financial account (investment flows, reserve assets). By definition, the balance of payments always balances — a current account deficit must be financed by a capital account surplus (foreign investment inflows). Countries in crisis often face "balance of payments crises" when they cannot finance their current account deficits.',
    related: ['current-account-balance', 'trade-balance', 'foreign-direct-investment'],
    category: 'Trade',
  },
  {
    slug: 'credit-rating',
    term: 'Sovereign Credit Rating',
    definition: 'An assessment by rating agencies (S&P, Moody\'s, Fitch) of a government\'s ability and willingness to repay its debt obligations.',
    explanation: 'Ratings range from AAA (highest quality, lowest risk) to D (default). Countries with high ratings borrow at low interest rates; those with low ratings pay higher premiums. The US, Germany, and Singapore maintain AAA ratings. Rating downgrades (like the US losing its AAA from S&P in 2011) can increase borrowing costs and signal fiscal deterioration. Emerging market ratings significantly affect capital flows.',
    related: ['debt-to-gdp-ratio', 'interest-rate', 'fiscal-policy'],
    category: 'Finance',
  },
  {
    slug: 'informal-economy',
    term: 'Informal Economy (Shadow Economy)',
    definition: 'Economic activity that is not regulated, taxed, or monitored by the government, including unregistered businesses, cash-only transactions, and subsistence activities.',
    explanation: 'In many developing countries, the informal economy employs 50-80% of workers and can represent 30-60% of GDP. Nigeria, India, and many African nations have enormous informal sectors. GDP statistics undercount informal activity, meaning official GDP figures may significantly underestimate true economic output. The informal economy provides livelihoods but offers no worker protections, benefits, or tax revenue.',
    related: ['gdp', 'unemployment-rate', 'poverty-rate'],
    category: 'Development',
  },
  {
    slug: 'dutch-disease',
    term: 'Dutch Disease',
    definition: 'The phenomenon where a boom in natural resource exports causes the domestic currency to appreciate, making other export sectors (manufacturing, agriculture) less competitive.',
    explanation: 'Named after the Netherlands\' experience with North Sea gas in the 1960s, Dutch Disease explains why resource-rich countries often have weak manufacturing sectors. Oil-exporting nations are particularly susceptible — when oil revenues flood in, the currency strengthens, imports become cheap, and domestic manufacturers cannot compete. Norway has managed this through its sovereign wealth fund; Nigeria and Venezuela have not.',
    related: ['exchange-rate', 'trade-balance', 'gdp'],
    category: 'Economy',
  },
  {
    slug: 'nearshoring',
    term: 'Nearshoring',
    definition: 'The practice of relocating business operations or manufacturing to a nearby country, typically to reduce supply chain risks while maintaining cost advantages.',
    explanation: 'Nearshoring accelerated after COVID-19 supply chain disruptions and US-China trade tensions. Mexico is the primary nearshoring beneficiary for the US market, attracting massive automotive and electronics manufacturing investment. Poland, Romania, and Turkey benefit from European nearshoring. Vietnam and India benefit from "China+1" strategies where companies maintain Chinese operations but diversify production.',
    related: ['supply-chain', 'foreign-direct-investment', 'trade-balance'],
    category: 'Trade',
  },
  {
    slug: 'dollarization',
    term: 'Dollarization',
    definition: 'When a country officially adopts the US dollar (or another foreign currency) as legal tender, replacing or supplementing its domestic currency.',
    explanation: 'Ecuador, El Salvador, and Panama use the US dollar as their official currency. Argentina has experienced unofficial dollarization as citizens hold savings in dollars to protect against peso devaluation. Dollarization eliminates exchange rate risk and can stabilize prices, but removes monetary policy flexibility — the country cannot adjust interest rates or print money to respond to economic shocks.',
    related: ['exchange-rate', 'inflation-rate', 'central-bank'],
    category: 'Fiscal',
  },
  {
    slug: 'brain-drain',
    term: 'Brain Drain',
    definition: 'The emigration of highly educated or skilled individuals from developing to developed countries, depleting the origin country\'s human capital.',
    explanation: 'Brain drain affects countries like India, Nigeria, the Philippines, and Eastern Europe, where educated professionals — doctors, engineers, IT workers — emigrate for higher wages and better opportunities. The US, UK, Canada, and Australia are major recipients. Remittances partially offset the loss, and "brain circulation" (emigrants returning with skills and capital) can eventually benefit origin countries. India\'s IT sector benefited from returning diaspora talent.',
    related: ['gdp-per-capita', 'labor-force-participation'],
    category: 'Demographics',
  },
  {
    slug: 'hyperinflation',
    term: 'Hyperinflation',
    definition: 'Extremely rapid inflation, typically defined as exceeding 50% per month (or ~13,000% annually), causing the currency to lose value so fast that normal economic activity breaks down.',
    explanation: 'Historical cases include Germany (1923), Zimbabwe (2008, peaking at 79.6 billion percent monthly), and Venezuela (2018-2019). Hyperinflation is always caused by governments printing money to finance spending they cannot fund through taxation. It destroys savings, forces barter, and typically ends only through radical monetary reform — new currency, independent central bank, or dollarization.',
    related: ['inflation-rate', 'central-bank', 'exchange-rate'],
    category: 'Economy',
  },
  {
    slug: 'trade-deficit',
    term: 'Trade Deficit',
    definition: 'When a country imports more goods and services than it exports, resulting in a negative trade balance.',
    explanation: 'The United States has run the world\'s largest trade deficit for decades (~$800B annually), importing far more consumer goods, oil, and manufactured products than it exports. A trade deficit is not necessarily bad — it can reflect strong domestic demand and consumer purchasing power. However, persistent deficits funded by borrowing can be unsustainable. Germany, China, and Japan typically run surpluses.',
    related: ['current-account-balance', 'trade-balance', 'exchange-rate'],
    category: 'Trade',
  },

  // ── ROUND 3: 20 MORE TERMS ──────────────────────
  {
    slug: 'austerity', term: 'Austerity',
    definition: 'Government policy of reducing budget deficits through spending cuts, tax increases, or both, typically during or after a fiscal crisis.',
    explanation: 'Austerity measures are controversial. Proponents argue they restore fiscal credibility and reduce debt; critics argue they deepen recessions by cutting demand when the economy is already weak. Greece, Spain, Portugal, and the UK implemented austerity after the 2008 crisis with mixed results.',
    related: ['fiscal-policy', 'debt-to-gdp-ratio', 'recession'], category: 'Fiscal',
  },
  {
    slug: 'capital-flight', term: 'Capital Flight',
    definition: 'Rapid outflow of financial assets from a country, typically triggered by political instability, currency devaluation fears, or loss of investor confidence.',
    explanation: 'Capital flight can trigger or worsen currency crises — as money leaves, the currency falls, which triggers more flight. Argentina, Turkey, and Russia have experienced severe capital flight episodes. Controls on capital outflows can slow flight but signal panic to markets.',
    related: ['exchange-rate', 'current-account-balance', 'inflation-rate'], category: 'Finance',
  },
  {
    slug: 'commodity-trap', term: 'Commodity Trap (Resource Curse)',
    definition: 'The paradox where countries rich in natural resources often have slower economic growth, more corruption, and weaker institutions than resource-poor countries.',
    explanation: 'Also called the "resource curse" — resource wealth can crowd out manufacturing (Dutch Disease), fund patronage and corruption, reduce incentives for institutional reform, and create volatility as commodity prices swing. Nigeria, Venezuela, and many African oil states illustrate the trap. Norway and Botswana are notable exceptions.',
    related: ['dutch-disease', 'gdp-growth-rate', 'corruption-by-country'], category: 'Development',
  },
  {
    slug: 'contagion', term: 'Financial Contagion',
    definition: 'The spread of a financial crisis from one country or market to others, through trade links, investor sentiment, or shared vulnerabilities.',
    explanation: 'The 1997 Asian Financial Crisis spread from Thailand to Indonesia, South Korea, and Malaysia in weeks. The 2008 crisis spread from US subprime mortgages to global banking. Contagion occurs through trade channels (one country\'s recession reduces demand for another\'s exports), financial channels (shared creditors pull money from all similar markets), and sentiment (investors flee all emerging markets regardless of fundamentals).',
    related: ['recession', 'capital-flight', 'exchange-rate'], category: 'Finance',
  },
  {
    slug: 'deflation', term: 'Deflation',
    definition: 'A sustained decrease in the general price level — the opposite of inflation. Prices fall, often accompanied by falling wages and economic stagnation.',
    explanation: 'Japan experienced deflation from the late 1990s to 2010s, creating a "lost decades" of stagnant growth. Deflation is dangerous because consumers delay purchases (expecting lower prices tomorrow), debtors face rising real debt burdens, and monetary policy hits the "zero lower bound" (can\'t cut rates below zero). Central banks fear deflation more than moderate inflation.',
    related: ['inflation-rate', 'central-bank', 'monetary-policy'], category: 'Economy',
  },
  {
    slug: 'emerging-market', term: 'Emerging Market',
    definition: 'A country transitioning from low-income to middle-income status, with developing institutions, growing financial markets, and rapid economic change.',
    explanation: 'The term was coined by IFC economist Antoine van Agtmael in 1981. Major emerging markets include China, India, Brazil, Mexico, Indonesia, and Turkey. They offer higher growth potential but greater risk than developed markets — currency volatility, political instability, and weaker institutions. MSCI maintains the most widely used EM index.',
    related: ['gdp-growth-rate', 'foreign-direct-investment', 'middle-income-trap'], category: 'Development',
  },
  {
    slug: 'fiscal-cliff', term: 'Fiscal Cliff',
    definition: 'A sudden, sharp reduction in government spending or increase in taxation that could tip an economy into recession, typically caused by expiring legislation.',
    explanation: 'The term gained prominence during the US fiscal crisis of late 2012, when simultaneous spending cuts and tax increases threatened to contract the economy. More broadly, it describes any abrupt fiscal tightening — scheduled subsidy removals, debt ceiling crises, or post-stimulus austerity can all create fiscal cliffs.',
    related: ['fiscal-policy', 'austerity', 'recession'], category: 'Fiscal',
  },
  {
    slug: 'soft-landing', term: 'Soft Landing',
    definition: 'An economic scenario where a central bank raises interest rates enough to slow growth and reduce inflation without triggering a recession.',
    explanation: 'Soft landings are historically rare — most hiking cycles end in recession. The Federal Reserve attempted a soft landing in 2023-2024 after raising rates from 0% to 5.5% to combat post-pandemic inflation. Success depends on precise calibration: tighten too much and you cause recession; too little and inflation persists.',
    related: ['central-bank', 'interest-rate', 'inflation-rate', 'recession'], category: 'Economy',
  },
  {
    slug: 'twin-deficits', term: 'Twin Deficits',
    definition: 'When a country runs both a fiscal deficit (government spending exceeds revenue) and a current account deficit (imports exceed exports) simultaneously.',
    explanation: 'The United States is the classic twin-deficit economy — the government borrows heavily (fiscal deficit) while the country imports far more than it exports (current account deficit). The twin deficits are linked through national accounting: when government saves less, the country must borrow from abroad. Twin deficits are sustainable for reserve currency issuers but dangerous for emerging markets.',
    related: ['fiscal-policy', 'current-account-balance', 'trade-deficit'], category: 'Economy',
  },
  {
    slug: 'debt-trap-diplomacy', term: 'Debt-Trap Diplomacy',
    definition: 'The allegation that a creditor country extends excessive loans to developing nations to gain strategic leverage when borrowers cannot repay.',
    explanation: 'The term is primarily associated with Chinese Belt and Road Initiative lending. Critics point to Sri Lanka\'s Hambantota Port (leased to China for 99 years after default) and debt distress in several African countries. China disputes the characterization, arguing it fills financing gaps that Western institutions won\'t. The debate reflects broader US-China geopolitical competition.',
    related: ['external-debt-by-country', 'foreign-direct-investment'], category: 'Geopolitics',
  },
  {
    slug: 'petrodollar', term: 'Petrodollar',
    definition: 'US dollars earned through oil exports, particularly by OPEC nations. The petrodollar system refers to the global practice of pricing and trading oil in US dollars.',
    explanation: 'Since the 1970s Saudi-US agreement, oil has been priced and traded globally in US dollars. This creates permanent demand for dollars, supporting reserve currency status. Saudi Arabia, UAE, Kuwait, and other exporters accumulate petrodollar surpluses that are recycled into US Treasury bonds and global investments. Challenges to this system (China buying oil in yuan) are closely watched.',
    related: ['reserve-currency', 'exchange-rate', 'sovereign-wealth-fund'], category: 'Finance',
  },
  {
    slug: 'demographic-transition', term: 'Demographic Transition',
    definition: 'The shift from high birth rates and death rates (pre-industrial) to low birth rates and death rates (post-industrial), with rapid population growth during the transition.',
    explanation: 'Every country undergoes this transition as it develops. Europe completed it over 150 years; East Asia did it in 50. Sub-Saharan Africa is in the middle. The transition creates a "demographic dividend" (falling dependency ratio) followed by aging challenges. Understanding where a country is in the transition is crucial for economic forecasting.',
    related: ['fertility-rate', 'life-expectancy', 'population-growth-rate'], category: 'Demographics',
  },
  {
    slug: 'misery-index', term: 'Misery Index',
    definition: 'The sum of a country\'s unemployment rate and inflation rate — a simple measure of economic distress felt by ordinary citizens.',
    explanation: 'Invented by economist Arthur Okun and popularized during the 1970s stagflation. A misery index above 20 indicates severe economic distress. Venezuela, Argentina, and Turkey have had some of the world\'s highest misery indices. The US peaked at 21.9 in 1980. Low misery indices (under 10) indicate comfortable economic conditions.',
    related: ['inflation-rate', 'unemployment-rate', 'stagflation'], category: 'Economy',
  },
  {
    slug: 'basket-of-goods', term: 'Basket of Goods',
    definition: 'A fixed set of consumer products and services used to calculate the Consumer Price Index (CPI) and measure inflation.',
    explanation: 'Statistical agencies survey prices of hundreds of items — food, housing, energy, transportation, clothing, healthcare, education — weighted by how much a typical household spends on each category. The basket is updated periodically to reflect changing consumption patterns (e.g., streaming services replacing cable TV). Different baskets can produce different inflation rates.',
    related: ['consumer-price-index', 'inflation-rate', 'purchasing-power-parity'], category: 'Economy',
  },
  {
    slug: 'structural-adjustment', term: 'Structural Adjustment Program (SAP)',
    definition: 'Economic reforms — typically including privatization, deregulation, trade liberalization, and fiscal austerity — required by the IMF or World Bank as conditions for lending.',
    explanation: 'SAPs were widely imposed on developing countries in the 1980s-90s, particularly in Africa and Latin America. They remain highly controversial: proponents say they correct unsustainable policies; critics argue they impose pain on the poor and override national sovereignty. Modern IMF programs use less prescriptive language but similar conditionality.',
    related: ['austerity', 'debt-to-gdp-ratio', 'poverty-rate'], category: 'Development',
  },
  {
    slug: 'currency-peg', term: 'Currency Peg (Fixed Exchange Rate)',
    definition: 'A monetary policy where a country fixes its exchange rate to another currency (usually the US dollar or euro), rather than allowing it to float freely.',
    explanation: 'Gulf states (Saudi Arabia, UAE, Qatar) peg to the dollar, providing stability for oil-denominated trade. Hong Kong maintains a dollar peg. Pegs provide predictability but remove monetary policy flexibility — the country must follow the anchor country\'s interest rate policy. Pegs can collapse spectacularly when economic conditions diverge (the Argentine peso board collapse in 2001).',
    related: ['exchange-rate', 'central-bank', 'dollarization'], category: 'Fiscal',
  },
  {
    slug: 'value-added-tax', term: 'Value-Added Tax (VAT)',
    definition: 'A consumption tax levied at each stage of production on the value added to goods and services, ultimately borne by the end consumer.',
    explanation: 'VAT is the most common form of consumption tax globally — over 160 countries use it. Rates range from 5% (Japan, Canada) to 27% (Hungary, the EU\'s highest). The US is the only major economy without a national VAT/GST. VAT is efficient (hard to evade compared to income tax) but regressive (takes a higher share of income from the poor). It typically generates 20-30% of government revenue.',
    related: ['tax-revenue-by-country', 'fiscal-policy'], category: 'Fiscal',
  },
  {
    slug: 'special-economic-zone', term: 'Special Economic Zone (SEZ)',
    definition: 'A geographic area within a country that operates under different economic regulations — typically lower taxes, lighter regulation, and streamlined customs — to attract foreign investment.',
    explanation: 'China\'s Shenzhen SEZ, established in 1980, is the most famous success story — transforming a fishing village into a $400B tech metropolis. SEZs now exist in over 140 countries with 5,000+ zones worldwide. They work best when they create genuine comparative advantage (infrastructure, skills) rather than just tax giveaways. Ethiopia, Vietnam, and Bangladesh have used SEZs to jumpstart manufacturing.',
    related: ['foreign-direct-investment', 'nearshoring', 'gdp-growth-rate'], category: 'Trade',
  },
  {
    slug: 'green-bond', term: 'Green Bond',
    definition: 'A fixed-income financial instrument specifically earmarked to fund climate and environmental projects — renewable energy, energy efficiency, clean transportation, and sustainable infrastructure.',
    explanation: 'The green bond market has grown from $3 billion in 2012 to over $500 billion annually. The EU, World Bank, and major corporations are leading issuers. Green bonds typically offer similar returns to conventional bonds but attract ESG-focused investors. Certification standards (Climate Bonds Initiative, EU Green Bond Standard) prevent "greenwashing." Sovereign green bonds have been issued by France, Germany, and the UK.',
    related: ['renewable-energy-by-country', 'co2-emissions-by-country', 'sovereign-wealth-fund'], category: 'Finance',
  },
  {
    slug: 'gig-economy', term: 'Gig Economy',
    definition: 'A labor market characterized by short-term, flexible, freelance, or independent contractor work rather than traditional permanent employment.',
    explanation: 'Platform companies like Uber, DoorDash, Upwork, and Fiverr have expanded the gig economy in developed countries. In developing countries, informal work has always dominated — the formal gig economy is layered on top. The gig economy offers flexibility but typically lacks benefits, job security, and career progression. Regulatory responses vary: the EU is pushing for platform worker protections, while the US remains more laissez-faire.',
    related: ['unemployment-rate', 'labor-force-participation'], category: 'Labor',
  },
];

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY_TERMS.find(t => t.slug === slug);
}
