export interface GlossaryTerm {
  slug: string;
  term: string;
  definition: string;
  explanation: string;
  rankingSlug?: string;
  related: string[]; // other term slugs
  category: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    slug: 'gdp',
    term: 'GDP (Gross Domestic Product)',
    definition: 'The total monetary value of all goods and services produced within a country\'s borders in a given period, usually a year.',
    explanation: 'GDP is the most widely used measure of economic output. It includes consumer spending, government expenditure, business investment, and net exports. GDP can be measured in nominal terms (current prices) or real terms (adjusted for inflation). The United States, China, and Japan have the three largest GDPs in the world.',
    rankingSlug: 'gdp',
    related: ['gdp-per-capita', 'gdp-ppp', 'gdp-growth-rate', 'gni'],
    category: 'Economy',
  },
  {
    slug: 'gdp-per-capita',
    term: 'GDP per Capita',
    definition: 'A country\'s total economic output (GDP) divided by its population, giving a rough measure of average economic output per person.',
    explanation: 'GDP per capita is often used as a proxy for average living standards. A country can have a large GDP but low GDP per capita if its population is large (e.g., India). Conversely, small wealthy nations like Luxembourg or Singapore have very high GDP per capita. It does not account for income distribution — two countries with the same GDP per capita may have very different levels of inequality.',
    rankingSlug: 'gdp-per-capita',
    related: ['gdp', 'gdp-ppp', 'gini-index', 'poverty-rate'],
    category: 'Economy',
  },
  {
    slug: 'gdp-ppp',
    term: 'GDP (PPP) — Purchasing Power Parity',
    definition: 'GDP adjusted for price differences between countries, allowing a fairer comparison of real economic output and living standards.',
    explanation: 'A dollar buys more in India than in Switzerland. PPP adjusts for these price differences using a "basket of goods" comparison. By PPP, China\'s economy is larger than the United States\'. GDP per capita PPP is considered the best single measure for comparing living standards across countries.',
    rankingSlug: 'gdp-ppp',
    related: ['gdp', 'gdp-per-capita', 'purchasing-power-parity'],
    category: 'Economy',
  },
  {
    slug: 'gdp-growth-rate',
    term: 'GDP Growth Rate',
    definition: 'The annual percentage change in a country\'s real GDP, measuring how fast an economy is expanding or contracting.',
    explanation: 'Real GDP growth adjusts for inflation, showing actual increases in economic output. Developing economies often grow faster (5-10%) while advanced economies typically grow 1-3%. Negative growth indicates a recession. The IMF publishes GDP growth estimates and forecasts in its World Economic Outlook.',
    rankingSlug: 'gdp-growth',
    related: ['gdp', 'inflation-rate', 'recession'],
    category: 'Economy',
  },
  {
    slug: 'gni',
    term: 'GNI (Gross National Income)',
    definition: 'The total income earned by a country\'s residents, including income from abroad, minus income sent to other countries.',
    explanation: 'While GDP measures production within borders, GNI measures income earned by nationals regardless of where they work. For countries with large diaspora populations sending remittances home, GNI can differ significantly from GDP. The World Bank uses GNI per capita to classify countries as low-income, middle-income, or high-income.',
    related: ['gdp', 'gdp-per-capita'],
    category: 'Economy',
  },
  {
    slug: 'inflation-rate',
    term: 'Inflation Rate',
    definition: 'The annual percentage increase in the general price level of goods and services in an economy.',
    explanation: 'Inflation erodes purchasing power — if inflation is 10%, something that cost $100 last year costs $110 today. Most central banks target 2% inflation as a healthy level. Hyperinflation (>50% monthly) can collapse economies, as seen historically in Zimbabwe and Venezuela. The CPI (Consumer Price Index) is the most common measure.',
    rankingSlug: 'inflation-rate',
    related: ['cpi', 'monetary-policy', 'central-bank'],
    category: 'Economy',
  },
  {
    slug: 'cpi',
    term: 'CPI (Consumer Price Index)',
    definition: 'A measure that tracks changes in the price of a representative basket of consumer goods and services over time.',
    explanation: 'The CPI is the primary tool for measuring inflation from a consumer\'s perspective. It tracks prices of food, housing, transportation, healthcare, and other essentials. Central banks and governments use CPI to adjust monetary policy, wages, tax brackets, and social benefits. Different countries weight their baskets differently based on local consumption patterns.',
    related: ['inflation-rate', 'monetary-policy', 'purchasing-power-parity'],
    category: 'Economy',
  },
  {
    slug: 'unemployment-rate',
    term: 'Unemployment Rate',
    definition: 'The percentage of the labor force that is actively seeking work but unable to find employment.',
    explanation: 'The unemployment rate only counts people who are actively looking for work. It excludes discouraged workers who have stopped searching and underemployed workers in part-time jobs. A rate below 4-5% is generally considered "full employment." Youth unemployment (ages 15-24) is typically much higher than the overall rate.',
    rankingSlug: 'unemployment-rate',
    related: ['gdp-growth-rate', 'inflation-rate'],
    category: 'Economy',
  },
  {
    slug: 'government-debt-to-gdp',
    term: 'Government Debt-to-GDP Ratio',
    definition: 'Total government debt expressed as a percentage of GDP, indicating a country\'s ability to pay back its obligations.',
    explanation: 'A debt-to-GDP ratio over 100% means a country owes more than its annual economic output. Japan leads the world at over 250%. However, debt sustainability depends on interest rates, currency, and growth — Japan borrows cheaply in yen from domestic lenders, while developing countries borrowing in USD face more risk. The IMF recommends keeping debt below 60% of GDP for emerging markets.',
    rankingSlug: 'government-debt',
    related: ['fiscal-balance', 'sovereign-debt', 'current-account-balance'],
    category: 'Economy',
  },
  {
    slug: 'current-account-balance',
    term: 'Current Account Balance',
    definition: 'The difference between a country\'s total exports and total imports of goods, services, income, and transfers.',
    explanation: 'A current account surplus means a country exports more than it imports (e.g., Germany, China). A deficit means it imports more (e.g., the United States). Persistent large deficits can indicate over-consumption or lack of competitiveness, while persistent surpluses may indicate under-consumption. The current account is one component of the balance of payments.',
    rankingSlug: 'current-account',
    related: ['trade-openness', 'balance-of-payments', 'fdi'],
    category: 'Economy',
  },
  {
    slug: 'fiscal-balance',
    term: 'Fiscal Balance (Budget Surplus/Deficit)',
    definition: 'The difference between a government\'s revenue and its expenditure in a given year, expressed as a percentage of GDP.',
    explanation: 'A positive fiscal balance (surplus) means the government collects more than it spends. A negative balance (deficit) means it borrows to cover the gap. Most governments run deficits, which accumulate into national debt over time. During recessions, deficits tend to widen as tax revenue falls and social spending rises.',
    related: ['government-debt-to-gdp', 'monetary-policy'],
    category: 'Economy',
  },
  {
    slug: 'trade-openness',
    term: 'Trade Openness',
    definition: 'Total trade (exports + imports) as a percentage of GDP, measuring how integrated an economy is with global markets.',
    explanation: 'Highly trade-open economies like Singapore (trade > 300% of GDP) depend heavily on international commerce. Larger economies like the US tend to be less trade-open because domestic consumption drives most GDP. Trade openness has generally increased over time due to globalization, though trade wars and protectionism can reverse this trend.',
    rankingSlug: 'trade-openness',
    related: ['current-account-balance', 'fdi', 'gdp'],
    category: 'Economy',
  },
  {
    slug: 'fdi',
    term: 'FDI (Foreign Direct Investment)',
    definition: 'Investment by a company or individual in one country into business interests in another country, typically involving significant ownership or control.',
    explanation: 'FDI includes building factories, acquiring companies, or establishing joint ventures abroad. It differs from portfolio investment (buying stocks/bonds) because it involves lasting interest and management influence. High FDI inflows signal confidence in an economy. China, the US, and the EU are the world\'s largest FDI destinations.',
    rankingSlug: 'fdi-inflows',
    related: ['trade-openness', 'current-account-balance', 'gdp-growth-rate'],
    category: 'Economy',
  },
  {
    slug: 'gini-index',
    term: 'Gini Index (Gini Coefficient)',
    definition: 'A statistical measure of income inequality within a population, ranging from 0 (perfect equality) to 100 (maximum inequality).',
    explanation: 'A Gini of 0 means everyone earns the same; 100 means one person earns everything. Most countries fall between 25-60. Nordic countries (Sweden, Norway) have low Gini scores (~27), while South Africa and some Latin American countries exceed 50. The Gini index does not capture wealth inequality, which tends to be far more extreme than income inequality.',
    rankingSlug: 'gini-index',
    related: ['poverty-rate', 'gdp-per-capita'],
    category: 'Inequality',
  },
  {
    slug: 'poverty-rate',
    term: 'Poverty Rate (International Poverty Line)',
    definition: 'The percentage of a population living below the international poverty line of $2.15 per day (2017 PPP).',
    explanation: 'The World Bank sets the international poverty line at $2.15/day, updated for purchasing power. By this measure, global extreme poverty has fallen dramatically — from 36% in 1990 to under 10% today. However, higher thresholds ($3.65, $6.85/day) show much more poverty. Sub-Saharan Africa has the highest concentration of extreme poverty.',
    rankingSlug: 'poverty-rate',
    related: ['gini-index', 'gdp-per-capita', 'life-expectancy'],
    category: 'Inequality',
  },
  {
    slug: 'life-expectancy',
    term: 'Life Expectancy at Birth',
    definition: 'The average number of years a newborn is expected to live, based on current mortality rates.',
    explanation: 'Life expectancy is one of the most powerful indicators of development. It reflects healthcare access, nutrition, sanitation, conflict, and poverty. The global average is about 73 years, but ranges from 85+ in Japan and Monaco to under 55 in some sub-Saharan African countries. Women live longer than men in virtually every country.',
    rankingSlug: 'life-expectancy',
    related: ['infant-mortality', 'fertility-rate', 'poverty-rate'],
    category: 'Health',
  },
  {
    slug: 'fertility-rate',
    term: 'Total Fertility Rate',
    definition: 'The average number of children a woman would have over her lifetime based on current birth rates.',
    explanation: 'A fertility rate of 2.1 is the "replacement level" — the rate needed to maintain a stable population without migration. Most developed countries are well below replacement (South Korea is at ~0.7), while sub-Saharan Africa averages over 4.5. Low fertility leads to aging populations, labor shortages, and pension crises.',
    rankingSlug: 'fertility-rate',
    related: ['life-expectancy', 'population-growth', 'infant-mortality'],
    category: 'Demographics',
  },
  {
    slug: 'infant-mortality',
    term: 'Infant Mortality Rate',
    definition: 'The number of deaths of children under age 5 per 1,000 live births.',
    explanation: 'Infant mortality is one of the starkest indicators of development. It reflects access to clean water, nutrition, healthcare, and maternal care. Rates range from under 3 per 1,000 in Scandinavian countries to over 100 in parts of sub-Saharan Africa. Global infant mortality has dropped by over 50% since 1990.',
    rankingSlug: 'infant-mortality',
    related: ['life-expectancy', 'fertility-rate', 'poverty-rate'],
    category: 'Health',
  },
  {
    slug: 'population-growth',
    term: 'Population Growth Rate',
    definition: 'The annual percentage change in a country\'s total population, including births, deaths, and net migration.',
    explanation: 'Population growth is driven by the balance of births minus deaths (natural increase) plus net migration. Many developed countries have near-zero or negative natural growth, sustained only by immigration. The fastest-growing populations are in sub-Saharan Africa, while Eastern European and East Asian countries are shrinking.',
    rankingSlug: 'population-growth',
    related: ['fertility-rate', 'life-expectancy', 'urban-population'],
    category: 'Demographics',
  },
  {
    slug: 'urban-population',
    term: 'Urban Population',
    definition: 'The share of a country\'s population living in urban areas, as defined by national statistical offices.',
    explanation: 'Over 56% of the world\'s population now lives in cities — up from 30% in 1950, projected to reach 68% by 2050. Urbanization drives economic growth through agglomeration effects but also creates challenges: housing, pollution, inequality, and infrastructure strain. The most urbanized countries include city-states like Singapore (100%) and Monaco.',
    rankingSlug: 'urban-population',
    related: ['population-growth', 'gdp-per-capita'],
    category: 'Demographics',
  },
  {
    slug: 'co2-emissions',
    term: 'CO₂ Emissions per Capita',
    definition: 'The total amount of carbon dioxide emitted per person per year, measured in metric tonnes.',
    explanation: 'Per capita CO₂ emissions measure a country\'s climate impact relative to its population. Oil-producing Gulf states have the highest per capita emissions (>30 tonnes), while most African countries emit less than 1 tonne per person. Total emissions are dominated by China and the United States. Reducing per capita emissions is central to meeting Paris Agreement targets.',
    rankingSlug: 'co2-emissions',
    related: ['renewable-energy', 'gdp-per-capita'],
    category: 'Environment',
  },
  {
    slug: 'renewable-energy',
    term: 'Renewable Energy Share',
    definition: 'The percentage of total energy consumption derived from renewable sources: hydro, solar, wind, geothermal, and biomass.',
    explanation: 'Countries like Iceland (nearly 100%) and Norway (>70%) lead in renewable energy thanks to abundant hydropower and geothermal resources. Globally, renewables account for about 18% of final energy consumption. Solar and wind are growing fastest, but fossil fuels still dominate. The energy transition is critical for meeting climate targets.',
    rankingSlug: 'renewable-energy',
    related: ['co2-emissions'],
    category: 'Environment',
  },
  {
    slug: 'purchasing-power-parity',
    term: 'Purchasing Power Parity (PPP)',
    definition: 'A theory and method that adjusts exchange rates to equalize the purchasing power of different currencies.',
    explanation: 'PPP answers the question: "How much does $1 actually buy in different countries?" If a Big Mac costs $5 in the US but $2.50 in India, the PPP exchange rate is 2:1, meaning India\'s prices are half of US prices. The World Bank and IMF use PPP-adjusted figures to compare economies more fairly than market exchange rates allow.',
    related: ['gdp-ppp', 'gdp-per-capita', 'cpi'],
    category: 'Economy',
  },
  {
    slug: 'monetary-policy',
    term: 'Monetary Policy',
    definition: 'Actions by a central bank to manage the money supply and interest rates to influence economic activity.',
    explanation: 'Monetary policy has two main tools: interest rates and quantitative easing/tightening. Raising rates slows inflation but can reduce growth; cutting rates stimulates growth but risks inflation. The US Federal Reserve, European Central Bank, and Bank of Japan are the most influential central banks. "Hawkish" policy means tightening; "dovish" means easing.',
    related: ['inflation-rate', 'central-bank', 'cpi'],
    category: 'Economy',
  },
  {
    slug: 'central-bank',
    term: 'Central Bank',
    definition: 'A national institution responsible for managing a country\'s currency, money supply, and interest rates.',
    explanation: 'Central banks like the Federal Reserve (US), ECB (Europe), and Bank of Japan control monetary policy, regulate commercial banks, and act as lenders of last resort. Their interest rate decisions impact everything from mortgage rates to stock markets. Independence from political pressure is considered crucial for maintaining price stability.',
    related: ['monetary-policy', 'inflation-rate'],
    category: 'Economy',
  },
  {
    slug: 'credit-rating',
    term: 'Sovereign Credit Rating',
    definition: 'An assessment by rating agencies (S&P, Moody\'s, Fitch) of a government\'s ability and willingness to repay its debts.',
    explanation: 'Ratings range from AAA (highest quality, lowest risk) to D (default). Higher ratings mean lower borrowing costs. A downgrade can increase interest payments by billions. The US, Germany, and Singapore hold top ratings, while countries in default or near-default receive the lowest. Ratings are controversial — agencies were criticized for failing to predict the 2008 financial crisis.',
    related: ['government-debt-to-gdp', 'sovereign-debt', 'fiscal-balance'],
    category: 'Economy',
  },
  {
    slug: 'sovereign-debt',
    term: 'Sovereign Debt',
    definition: 'The total amount of money a national government has borrowed, including domestic and foreign-denominated bonds.',
    explanation: 'Sovereign debt is issued through government bonds (e.g., US Treasuries, Japanese Government Bonds). It can be denominated in domestic currency (lower risk, can be inflated away) or foreign currency (higher risk, can lead to debt crises). The global sovereign debt market exceeds $70 trillion. A sovereign debt crisis occurs when a government cannot service its obligations.',
    related: ['government-debt-to-gdp', 'credit-rating', 'fiscal-balance'],
    category: 'Economy',
  },
  {
    slug: 'balance-of-payments',
    term: 'Balance of Payments',
    definition: 'A comprehensive record of all economic transactions between a country\'s residents and the rest of the world.',
    explanation: 'The balance of payments has three components: the current account (trade in goods/services), the capital account (asset transfers), and the financial account (investment flows). By definition, the overall balance of payments must equal zero — a current account deficit must be financed by a financial account surplus (capital inflows). Persistent imbalances can signal economic vulnerabilities.',
    related: ['current-account-balance', 'trade-openness', 'fdi'],
    category: 'Economy',
  },
  {
    slug: 'hdi',
    term: 'HDI (Human Development Index)',
    definition: 'A composite index measuring average achievement in three dimensions: health (life expectancy), education, and standard of living (GNI per capita).',
    explanation: 'Created by the UNDP, the HDI ranges from 0 to 1. Countries above 0.8 are "very high human development" (Norway, Switzerland, Iceland lead). The HDI is useful because it goes beyond pure economic output to include health and education outcomes. However, it doesn\'t capture inequality, sustainability, or political freedom.',
    related: ['life-expectancy', 'gdp-per-capita', 'gini-index'],
    category: 'Development',
  },
  {
    slug: 'recession',
    term: 'Recession',
    definition: 'A significant, widespread, and prolonged decline in economic activity, commonly defined as two consecutive quarters of negative GDP growth.',
    explanation: 'Recessions are characterized by falling output, rising unemployment, declining consumer spending, and reduced business investment. The 2008 Global Financial Crisis and the 2020 COVID-19 downturn are recent examples. Central banks respond with rate cuts and stimulus, while governments increase spending. The NBER (US) officially declares recessions, often months after they begin.',
    related: ['gdp-growth-rate', 'unemployment-rate', 'monetary-policy'],
    category: 'Economy',
  },
  {
    slug: 'nominal-gdp',
    term: 'Nominal GDP',
    definition: 'GDP measured at current market prices without adjusting for inflation. Expressed in a common currency (usually US dollars) for international comparison.',
    explanation: 'Nominal GDP reflects both changes in real output and changes in prices. When comparing countries, nominal GDP in US dollars is affected by exchange rate movements — a country\'s GDP can shrink in dollar terms even while its domestic economy grows, simply because its currency weakened. Despite this limitation, nominal GDP is the standard measure for comparing the size of national economies.',
    rankingSlug: 'gdp',
    related: ['gdp', 'gdp-ppp', 'real-gdp'],
    category: 'Economy',
  },
  {
    slug: 'real-gdp',
    term: 'Real GDP',
    definition: 'GDP adjusted for inflation, measuring the actual quantity of goods and services produced. Changes in real GDP represent actual growth in economic output.',
    explanation: 'Real GDP removes the effect of price changes, isolating genuine changes in production. If nominal GDP grows 7% but inflation is 4%, real GDP growth is roughly 3%. This makes real GDP essential for tracking actual economic performance over time. Central banks and policymakers focus on real GDP when assessing economic health.',
    related: ['gdp', 'nominal-gdp', 'gdp-growth-rate', 'inflation'],
    category: 'Economy',
  },
  {
    slug: 'central-bank',
    term: 'Central Bank',
    definition: 'A national institution responsible for monetary policy, currency issuance, and financial system stability. Examples: the Federal Reserve (US), ECB (Europe), Bank of Japan.',
    explanation: 'Central banks control interest rates, manage inflation, and serve as lenders of last resort to commercial banks. The US Federal Reserve is the world\'s most influential central bank because the dollar is the global reserve currency. Central bank independence from political interference is considered essential for credible monetary policy. Key tools include policy interest rates, open market operations, and quantitative easing.',
    related: ['monetary-policy', 'inflation', 'interest-rate'],
    category: 'Economy',
  },
  {
    slug: 'interest-rate',
    term: 'Interest Rate (Policy Rate)',
    definition: 'The rate set by a central bank at which commercial banks can borrow money, which in turn influences all other interest rates in the economy.',
    explanation: 'When a central bank raises interest rates, borrowing becomes more expensive, slowing spending and investment — which helps control inflation. When rates are cut, borrowing is cheaper, stimulating economic activity. The US federal funds rate, ECB deposit rate, and Bank of England base rate are the most watched policy rates globally. Near-zero or negative interest rates were common in the 2010s but were abandoned during the post-pandemic inflation surge.',
    related: ['central-bank', 'monetary-policy', 'inflation'],
    category: 'Economy',
  },
  {
    slug: 'exchange-rate',
    term: 'Exchange Rate',
    definition: 'The price at which one currency can be exchanged for another. Determines the international value of a nation\'s money.',
    explanation: 'Exchange rates are either floating (determined by market forces, like USD/EUR) or fixed/pegged (set by the government, like the Saudi riyal). A strong currency makes imports cheaper but exports more expensive. Currency depreciation can boost exports but increases the cost of imported goods and foreign debt repayment. Major currency pairs include EUR/USD, USD/JPY, and GBP/USD.',
    related: ['gdp', 'trade-balance', 'monetary-policy'],
    category: 'Economy',
  },
  {
    slug: 'trade-balance',
    term: 'Trade Balance',
    definition: 'The difference between a country\'s exports and imports. A surplus means exports exceed imports; a deficit means the opposite.',
    explanation: 'Germany, China, and Japan typically run large trade surpluses, while the US and UK run deficits. A trade surplus isn\'t inherently "good" — it can reflect weak domestic demand. A trade deficit isn\'t inherently "bad" — it can reflect strong consumer spending and investment. The trade balance is a major component of the current account, which includes all international transactions.',
    rankingSlug: 'current-account',
    related: ['current-account-balance', 'gdp', 'exchange-rate'],
    category: 'Trade',
  },
  {
    slug: 'quantitative-easing',
    term: 'Quantitative Easing (QE)',
    definition: 'A monetary policy tool where a central bank purchases government bonds or other financial assets to inject money into the economy and lower long-term interest rates.',
    explanation: 'QE was pioneered by the Bank of Japan in 2001 and used extensively by the Federal Reserve, ECB, and Bank of England after the 2008 financial crisis and during COVID-19. By buying bonds, central banks push down yields, making borrowing cheaper and encouraging investment. Critics argue QE inflates asset prices (stocks, real estate) and benefits the wealthy disproportionately. The reverse process — "quantitative tightening" — involves selling bonds to drain money from the financial system.',
    related: ['central-bank', 'monetary-policy', 'interest-rate'],
    category: 'Economy',
  },
  {
    slug: 'fiscal-policy',
    term: 'Fiscal Policy',
    definition: 'Government decisions about taxation and spending used to influence the economy. Expansionary fiscal policy involves increased spending or tax cuts; contractionary involves the opposite.',
    explanation: 'Fiscal policy is the responsibility of elected governments, unlike monetary policy which is managed by central banks. During recessions, governments typically increase spending and cut taxes to stimulate demand (Keynesian economics). The challenge is that fiscal stimulus often increases government debt. The balance between fiscal stimulus and debt sustainability is one of the central debates in economics.',
    related: ['government-debt', 'gdp-growth-rate', 'monetary-policy', 'recession'],
    category: 'Economy',
  },
  {
    slug: 'demographic-dividend',
    term: 'Demographic Dividend',
    definition: 'The economic growth boost that occurs when a country\'s working-age population grows faster than its dependent population (children and elderly).',
    explanation: 'The demographic dividend occurs during the transition from high to low fertility rates. For a period, the share of working-age adults increases relative to dependents, potentially boosting savings, investment, and GDP growth. East Asia\'s rapid growth from 1970-2010 is partly attributed to this dividend. India and parts of Africa are currently in their dividend phase. However, the dividend is not automatic — it requires productive employment for the growing workforce.',
    related: ['population-growth-rate', 'fertility-rate', 'life-expectancy'],
    category: 'Demographics',
  },
  {
    slug: 'sanctions',
    term: 'Economic Sanctions',
    definition: 'Penalties imposed by one country or group of countries on another, restricting trade, financial transactions, or other economic activity, typically to achieve foreign policy or security objectives.',
    explanation: 'Sanctions range from targeted measures (freezing specific individuals\' assets) to comprehensive trade embargoes. Russia, Iran, North Korea, and Venezuela are among the most heavily sanctioned countries. The effectiveness of sanctions is debated: they can constrain economies but often hurt civilian populations and may push countries toward alternative trading partners (e.g., Russia pivoting to China). SWIFT disconnection — removing a country from the global banking messaging system — is one of the most powerful sanctions tools.',
    related: ['trade-balance', 'gdp', 'exchange-rate'],
    category: 'Geopolitics',
  },
  {
    slug: 'middle-income-trap',
    term: 'Middle-Income Trap',
    definition: 'The phenomenon where a country\'s growth stalls after reaching middle-income status, unable to compete with low-wage economies in manufacturing or with advanced economies in innovation.',
    explanation: 'Countries that industrialize quickly through low-cost manufacturing often struggle to transition to higher-value production as wages rise. Only a handful of economies have successfully escaped the trap: South Korea, Taiwan, Singapore, and a few others. China is currently testing whether the world\'s largest middle-income country can break through. Latin American countries like Brazil and Mexico have been stuck at middle-income levels for decades.',
    related: ['gdp-per-capita', 'gdp-growth-rate'],
    category: 'Development',
  },
];

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return GLOSSARY_TERMS.find(t => t.slug === slug);
}
