import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Singapore Economy 2026 — GDP, Trade, Finance & Key Data', description: 'Singapore economy in 2026: GDP, growth, trade, financial hub status, and key indicators. One of the world\'s wealthiest countries per capita. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/singapore-economy' } };
export default async function SingaporeEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('SGP');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Singapore Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Singapore's GDP per capita?`, acceptedAnswer: { '@type': 'Answer', text: `Singapore's GDP per capita is approximately ${formatValue(gdpPerCapita?.value, 'currency')} — among the highest in the world. For a city-state with zero natural resources, this represents one of the most remarkable development achievements in history. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/singapore" className="hover:text-gray-600 transition">Singapore</Link><span className="mx-2">/</span><span className="text-gray-600">Singapore Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Singapore Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">World&apos;s most competitive small economy · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Singapore Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Singapore is perhaps the most improbable economic success story in modern history. A city-state of 6 million people with zero natural resources, no hinterland, and no agricultural capacity, it has one of the world&apos;s highest GDP per capita figures at {formatValue(gdpPerCapita?.value, 'currency')}. This transformation from a colonial trading post to a first-world economy in a single generation was achieved through visionary governance, strategic investment in education, relentless focus on rule of law and <Link href="/corruption-by-country" className="text-[#0066cc] hover:underline">anti-corruption</Link>, and positioning as Asia&apos;s premier business hub.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Singapore&apos;s economy is built on three pillars: financial services (Asia&apos;s second-largest financial center after Hong Kong/Shanghai, with $4T+ in assets under management), <Link href="/trade-by-country" className="text-[#0066cc] hover:underline">trade</Link> and logistics (the world&apos;s busiest container port and a critical oil refining hub), and high-tech manufacturing (a major node in the global semiconductor supply chain). Changi Airport is consistently rated the world&apos;s best, reflecting Singapore&apos;s obsession with infrastructure quality.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include high cost of living, an aging population, income inequality (high for a developed Asian economy), and overreliance on imported labor. Singapore&apos;s <Link href="/life-expectancy-by-country" className="text-[#0066cc] hover:underline">life expectancy</Link> at {lifeExp?.value ? Number(lifeExp.value).toFixed(1) : '84'} years is among the world&apos;s highest. The city-state competes directly with <Link href="/switzerland-economy" className="text-[#0066cc] hover:underline">Switzerland</Link> and Hong Kong as a global wealth management hub.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/singapore', label: 'Full Profile →' }, { href: '/asean-economy', label: 'ASEAN Economy' }, { href: '/switzerland-economy', label: 'Switzerland Economy' }, { href: '/richest-countries', label: 'Richest Countries' }, { href: '/safest-countries', label: 'Safest Countries' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
