import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'New Zealand Economy 2026 — GDP, Agriculture, Tourism & Key Data', description: 'New Zealand economy in 2026: GDP, growth, inflation, dairy exports, tourism, and key indicators. A high-income OECD economy with 5M people. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/new-zealand-economy' } };
export default async function NewZealandEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('NZL');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `New Zealand Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is New Zealand's GDP?`, acceptedAnswer: { '@type': 'Answer', text: `New Zealand's GDP is approximately ${formatValue(gdp?.value, 'currency')} in ${year}. Despite a small population of ~5 million, NZ is a high-income OECD economy powered by dairy (world's largest exporter), tourism, and agriculture. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/new-zealand" className="hover:text-gray-600 transition">New Zealand</Link><span className="mx-2">/</span><span className="text-gray-600">New Zealand Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The New Zealand Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">High-income OECD economy · 5M people · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">New Zealand Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">New Zealand is a small, open, high-income economy with a <Link href="/population-by-country" className="text-[#0066cc] hover:underline">population</Link> of just 5 million that consistently ranks among the world&apos;s best for ease of doing business, <Link href="/corruption-by-country" className="text-[#0066cc] hover:underline">low corruption</Link>, and quality of life. The economy is built on agriculture (dairy giant Fonterra is the world&apos;s largest dairy exporter), <Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">tourism</Link> (pre-COVID NZ hosted ~4 million visitors — nearly matching its population), and increasingly, technology and film production (Weta Workshop, the &quot;Wellywood&quot; film industry).</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">New Zealand shares many economic characteristics with <Link href="/australia-economy" className="text-[#0066cc] hover:underline">Australia</Link> — both are English-speaking, resource-oriented, commodity-exporting former British colonies in the South Pacific with strong institutions and high living standards. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is slightly below Australia&apos;s. NZ&apos;s Reserve Bank was a pioneer of inflation targeting (the first central bank to adopt it in 1990), a framework now used worldwide.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include a severe housing affordability crisis (Auckland house prices relative to income are among the world&apos;s highest), geographic isolation from major markets (raising trade costs), heavy dairy dependence making the economy vulnerable to commodity price swings and <Link href="/china-economy" className="text-[#0066cc] hover:underline">Chinese</Link> import demand, and a persistent current account deficit. <Link href="/life-expectancy-by-country" className="text-[#0066cc] hover:underline">Life expectancy</Link> at {lifeExp?.value ? Number(lifeExp.value).toFixed(1) : '82'} years reflects excellent healthcare and quality of life.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/new-zealand', label: 'Full Profile →' }, { href: '/australia-economy', label: 'Australia Economy' }, { href: '/singapore-economy', label: 'Singapore Economy' }, { href: '/richest-countries', label: 'Richest Countries' }, { href: '/safest-countries', label: 'Safest Countries' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
