import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Ethiopia Economy 2026 — GDP, Growth, BRICS & Key Data', description: 'Ethiopia economy in 2026: GDP, growth, inflation, manufacturing, and key indicators. Africa\'s fastest-growing large economy and newest BRICS member. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/ethiopia-economy' } };
export default async function EthiopiaEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('ETH');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Ethiopia Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `How fast has Ethiopia been growing?`, acceptedAnswer: { '@type': 'Answer', text: `Ethiopia averaged over 9% GDP growth from 2010-2019 — one of the fastest growth rates in the world. Growth was driven by massive infrastructure investment (roads, rail, dams, industrial parks), agricultural modernization, and a government-directed development model. However, civil conflict in 2020-2022 severely disrupted the economy. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/ethiopia" className="hover:text-gray-600 transition">Ethiopia</Link><span className="mx-2">/</span><span className="text-gray-600">Ethiopia Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Ethiopia Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Africa&apos;s fastest-growing large economy · <Link href="/brics-economy" className="text-[#64748b] hover:text-gray-600">BRICS</Link> member · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Ethiopia Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Ethiopia is Africa&apos;s second most populous country (120M+ people) and was the continent&apos;s fastest-growing large economy, averaging over 9% GDP growth from 2010-2019 — a rate that rivaled <Link href="/china-economy" className="text-[#0066cc] hover:underline">China&apos;s</Link> during its industrial takeoff. This growth was driven by a state-directed development model: massive infrastructure investment (the Grand Ethiopian Renaissance Dam on the Nile, a Chinese-built railway to Djibouti, new roads and industrial parks), agricultural modernization, and a push into manufacturing through Chinese-style special economic zones.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Ethiopia has been called Africa&apos;s &quot;<Link href="/china-economy" className="text-[#0066cc] hover:underline">China</Link>&quot; for its development ambitions. The government invested heavily in industrial parks to attract garment and shoe manufacturers looking for alternatives to Asian factories. Coffee — Ethiopia is its birthplace and the continent&apos;s largest producer — remains the top export. Ethiopian Airlines is Africa&apos;s largest and most profitable airline, serving as a critical connectivity hub for the continent.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The devastating civil conflict in Tigray (2020-2022) severely disrupted the growth trajectory, causing humanitarian crisis and economic damage. Ethiopia joined <Link href="/brics-economy" className="text-[#0066cc] hover:underline">BRICS</Link> in 2024, gaining diplomatic and economic backing from the bloc. Challenges include very low GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} (among the world&apos;s lowest), high <Link href="/inflation-by-country" className="text-[#0066cc] hover:underline">inflation</Link>, foreign exchange shortages, and the need to restart the growth engine while managing post-conflict reconstruction. The <Link href="/population-by-country" className="text-[#0066cc] hover:underline">population</Link> is extremely young (median age ~19), presenting an enormous labor market challenge.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/ethiopia', label: 'Full Profile →' }, { href: '/kenya-economy', label: 'Kenya Economy' }, { href: '/nigeria-economy', label: 'Nigeria Economy' }, { href: '/brics-economy', label: 'BRICS Economy' }, { href: '/poorest-countries', label: 'Poorest Countries' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
