import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Vietnam Economy 2026 — GDP, Manufacturing, Growth & Key Data', description: 'Vietnam economy in 2026: GDP, growth, trade, FDI, and key indicators. One of the fastest-growing economies in the world. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/vietnam-economy' } };
export default async function VietnamEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('VNM');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Vietnam Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Vietnam's GDP growth rate?`, acceptedAnswer: { '@type': 'Answer', text: `Vietnam's GDP growth rate is ${formatValue(gdpGrowth?.value, 'percent', 1)} in ${year}. Vietnam has been one of the world's fastest-growing economies, averaging 6-7% annual growth for over two decades. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/vietnam" className="hover:text-gray-600 transition">Vietnam</Link><span className="mx-2">/</span><span className="text-gray-600">Vietnam Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Vietnam Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">One of the world&apos;s fastest-growing economies · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Vietnam Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Vietnam has been one of the world&apos;s fastest-growing economies for over two decades, averaging 6-7% annual GDP growth since the Doi Moi (renovation) reforms of 1986. This growth has been driven by manufacturing exports, foreign direct investment, and integration into global supply chains. Samsung&apos;s largest factory complex in the world is near Hanoi, and Vietnam has become a major producer of electronics, textiles, footwear, and furniture. The country is a prime beneficiary of supply chain diversification away from <Link href="/china-economy" className="text-[#0066cc] hover:underline">China</Link>.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Vietnam&apos;s 100 million people, young demographics (median age ~30), competitive labor costs, and an extensive network of free trade agreements (CPTPP, RCEP, EU-Vietnam FTA) make it one of the most attractive manufacturing destinations globally. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} has roughly quadrupled since 2000 but remains low relative to <Link href="/thailand-economy" className="text-[#0066cc] hover:underline">Thailand</Link> and Malaysia, reflecting the enormous room for catch-up growth.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include infrastructure bottlenecks (ports, roads, power grid struggling to keep pace with industrial growth), a workforce that needs upskilling for higher-value manufacturing, corruption, and environmental pressures from rapid industrialization. Vietnam&apos;s state-capitalist model — Communist Party political control with market-oriented economic policy — mirrors <Link href="/china-economy" className="text-[#0066cc] hover:underline">China&apos;s</Link> approach with a 20-year lag.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/vietnam', label: 'Full Profile →' }, { href: '/indonesia-economy', label: 'Indonesia Economy' }, { href: '/thailand-economy', label: 'Thailand Economy' }, { href: '/asean-economy', label: 'ASEAN Economy' }, { href: '/china-economy', label: 'China Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
