import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Colombia Economy 2026 — GDP, Growth, Coffee & Key Data', description: 'Colombia economy in 2026: GDP, growth, inflation, trade, and key indicators. Latin America\'s 4th largest economy. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/colombia-economy' } };
export default async function ColombiaEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('COL');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Colombia Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Colombia's GDP?`, acceptedAnswer: { '@type': 'Answer', text: `Colombia's GDP is approximately ${formatValue(gdp?.value, 'currency')} in ${year}, making it Latin America's 4th largest economy after Brazil, Mexico, and Argentina. Colombia has diversified beyond coffee and oil into financial services, tech, and tourism. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/colombia" className="hover:text-gray-600 transition">Colombia</Link><span className="mx-2">/</span><span className="text-gray-600">Colombia Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Colombia Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Latin America&apos;s 4th largest economy · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Colombia Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Colombia is Latin America&apos;s fourth-largest economy with a population of 52 million and one of the region&apos;s most diversified economic bases. While historically known for coffee (the world&apos;s third-largest producer) and oil (its top export), Colombia has developed significant financial services, technology, and tourism sectors. Bogotá has emerged as a regional tech hub, and Medellín&apos;s transformation from one of the world&apos;s most dangerous cities to an innovation center is one of urban development&apos;s greatest success stories.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Colombia joined the OECD in 2020, reflecting its progress on institutional reform, economic openness, and governance improvements over the past two decades. The 2016 peace agreement with FARC guerrillas opened previously conflict-affected regions to investment and development. The country has maintained relatively prudent fiscal policy and inflation targeting, earning it investment-grade credit ratings — unusual in a region prone to macro instability.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include high <Link href="/gini-index-by-country" className="text-[#0066cc] hover:underline">inequality</Link> (Gini coefficient above 50 — among the world&apos;s highest), informal employment affecting roughly 60% of workers, and vulnerability to commodity price swings. The transition away from oil dependence is a strategic priority as global energy markets shift. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} reflects Colombia&apos;s upper-middle-income status with significant room for growth. The Pacific Alliance trade bloc (with <Link href="/mexico-economy" className="text-[#0066cc] hover:underline">Mexico</Link>, Peru, and <Link href="/chile-economy" className="text-[#0066cc] hover:underline">Chile</Link>) has deepened regional integration.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/colombia', label: 'Full Profile →' }, { href: '/brazil-economy', label: 'Brazil Economy' }, { href: '/mexico-economy', label: 'Mexico Economy' }, { href: '/argentina-economy', label: 'Argentina Economy' }, { href: '/gdp-by-country', label: 'GDP by Country' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
