import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Hungary Economy 2026 — GDP, Manufacturing, EV & Key Data', description: 'Hungary economy in 2026: GDP, growth, inflation, EV battery manufacturing, and key indicators. Central Europe\'s EV battery hub. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/hungary-economy' } };
export default async function HungaryEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('HUN');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Hungary Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Hungary's economy known for?`, acceptedAnswer: { '@type': 'Answer', text: `Hungary has become Europe's largest EV battery manufacturing hub, with CATL, Samsung SDI, and SK Innovation building mega-factories. The automotive sector (Audi, Mercedes, Suzuki) accounts for ~30% of manufacturing. Hungary also has a strong pharmaceutical sector and is a major food exporter. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/hungary" className="hover:text-gray-600 transition">Hungary</Link><span className="mx-2">/</span><span className="text-gray-600">Hungary Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Hungary Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Europe&apos;s EV battery hub · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Hungary Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Hungary has positioned itself as Central Europe&apos;s manufacturing hub through aggressive foreign investment incentives, competitive labor costs, and a strategic location in the heart of the <Link href="/eu-economy" className="text-[#0066cc] hover:underline">EU</Link>. The country has become Europe&apos;s largest electric vehicle battery manufacturing center, with Chinese giant CATL, <Link href="/south-korea-economy" className="text-[#0066cc] hover:underline">South Korean</Link> firms Samsung SDI and SK Innovation, and others building massive battery plants. Traditional automotive (Audi, Mercedes-Benz, Suzuki) accounts for roughly 30% of manufacturing output.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Hungary&apos;s economic model under Prime Minister Orbán combines low flat taxes (15% personal, 9% corporate — the EU&apos;s lowest), generous investment subsidies for foreign manufacturers, and an increasingly state-directed economic approach. This has attracted record FDI but also created political tensions with <Link href="/eu-economy" className="text-[#0066cc] hover:underline">Brussels</Link> over rule of law, media freedom, and the use of EU funds. Hungary has experienced higher <Link href="/inflation-by-country" className="text-[#0066cc] hover:underline">inflation</Link> than EU peers (peaking at 25%+ in 2023).</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} has been converging toward Western European levels but remains well below the EU average. The forint has been volatile. Beyond manufacturing, Hungary has strengths in pharmaceuticals (Richter Gedeon), IT services, and agriculture (a major grain and wine producer). Challenges include demographic decline, brain drain to Western Europe, and over-dependence on <Link href="/germany-economy" className="text-[#0066cc] hover:underline">German</Link> automotive demand.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/hungary', label: 'Full Profile →' }, { href: '/poland-economy', label: 'Poland Economy' }, { href: '/czech-republic-economy', label: 'Czech Republic' }, { href: '/romania-economy', label: 'Romania Economy' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
