// Shared ticker lists — must match scripts/fetch_sp500_quotes.py

export const COMPANY_NAMES: Record<string, string> = {
  // S&P 500 / NASDAQ 100
  AAPL:'Apple',ABBV:'AbbVie',ABT:'Abbott Labs',ACN:'Accenture',ADBE:'Adobe',ADI:'Analog Devices',
  ADM:'Archer-Daniels',ADP:'ADP',ADSK:'Autodesk',AEE:'Ameren',AEP:'American Electric Power',
  AES:'AES Corp',AFL:'Aflac',AIG:'AIG',AIZ:'Assurant',AJG:'Arthur J. Gallagher',AKAM:'Akamai',
  ALB:'Albemarle',ALGN:'Align Technology',ALK:'Alaska Air',ALL:'Allstate',ALLE:'Allegion',
  AMAT:'Applied Materials',AMCR:'Amcor',AMD:'AMD',AME:'Ametek',AMGN:'Amgen',AMP:'Ameriprise',
  AMT:'American Tower',AMZN:'Amazon',ANET:'Arista Networks',ANSS:'Ansys',AON:'Aon',AOS:'A.O. Smith',
  APA:'APA Corp',APD:'Air Products',APH:'Amphenol',APTV:'Aptiv',ARE:'Alexandria RE',ATO:'Atmos Energy',
  ATVI:'Activision',AVB:'AvalonBay',AVGO:'Broadcom',AVY:'Avery Dennison',AWK:'American Water Works',
  AXP:'American Express',AZO:'AutoZone',BA:'Boeing',BAC:'Bank of America',BAX:'Baxter',
  BBWI:'Bath & Body Works',BBY:'Best Buy',BDX:'Becton Dickinson',BEN:'Franklin Templeton',
  'BF.B':'Brown-Forman',BIIB:'Biogen',BIO:'Bio-Rad',BK:'BNY Mellon',BKNG:'Booking Holdings',
  BKR:'Baker Hughes',BLK:'BlackRock',BMY:'Bristol-Myers Squibb',BR:'Broadridge',
  'BRK.B':'Berkshire Hathaway',BRO:'Brown & Brown',BSX:'Boston Scientific',BWA:'BorgWarner',
  BXP:'BXP Inc',C:'Citigroup',CAG:'Conagra',CAH:'Cardinal Health',CARR:'Carrier Global',
  CAT:'Caterpillar',CB:'Chubb',CBOE:'Cboe Global',CBRE:'CBRE Group',CCI:'Crown Castle',
  CCL:'Carnival',CDAY:'Ceridian',CDNS:'Cadence Design',CDW:'CDW Corp',CE:'Celanese',
  CEG:'Constellation Energy',CF:'CF Industries',CFG:'Citizens Financial',CHD:'Church & Dwight',
  CHRW:'C.H. Robinson',CHTR:'Charter Communications',CI:'Cigna',CINF:'Cincinnati Financial',
  CL:'Colgate-Palmolive',CLX:'Clorox',CMA:'Comerica',CMCSA:'Comcast',CME:'CME Group',
  CMG:'Chipotle',CMI:'Cummins',CMS:'CMS Energy',CNC:'Centene',CNP:'CenterPoint Energy',
  COF:'Capital One',COO:'CooperCompanies',COP:'ConocoPhillips',COST:'Costco',CPB:'Campbell Soup',
  CPRT:'Copart',CPT:'Camden Property',CRL:'Charles River Labs',CRM:'Salesforce',CSCO:'Cisco',
  CSGP:'CoStar Group',CSX:'CSX Corp',CTAS:'Cintas',CTLT:'Catalent',CTRA:'Coterra Energy',
  CTSH:'Cognizant',CTVA:'Corteva',CVS:'CVS Health',CVX:'Chevron',CZR:'Caesars Entertainment',
  D:'Dominion Energy',DAL:'Delta Air Lines',DD:'DuPont',DE:'Deere & Co',DFS:'Discover Financial',
  DG:'Dollar General',DGX:'Quest Diagnostics',DHI:'D.R. Horton',DHR:'Danaher',DIS:'Walt Disney',
  DISH:'DISH Network',DLR:'Digital Realty',DLTR:'Dollar Tree',DOV:'Dover Corp',DOW:'Dow Inc',
  DPZ:'Domino\'s Pizza',DRI:'Darden Restaurants',DTE:'DTE Energy',DUK:'Duke Energy',
  DVA:'DaVita',DVN:'Devon Energy',DXC:'DXC Technology',DXCM:'DexCom',EA:'Electronic Arts',
  EBAY:'eBay',ECL:'Ecolab',ED:'Consolidated Edison',EFX:'Equifax',EIX:'Edison International',
  EL:'Estée Lauder',EMN:'Eastman Chemical',EMR:'Emerson Electric',ENPH:'Enphase Energy',
  EOG:'EOG Resources',EPAM:'EPAM Systems',EQIX:'Equinix',EQR:'Equity Residential',
  EQT:'EQT Corp',ESS:'Essex Property',ETN:'Eaton Corp',ETR:'Entergy',EVRG:'Evergy',
  EW:'Edwards Lifesciences',EXC:'Exelon',EXPD:'Expeditors Intl',EXPE:'Expedia',EXR:'Extra Space Storage',
  F:'Ford',FANG:'Diamondback Energy',FAST:'Fastenal',FBHS:'Fortune Brands',FCX:'Freeport-McMoRan',
  FDS:'FactSet',FDX:'FedEx',FE:'FirstEnergy',FFIV:'F5 Networks',FIS:'Fidelity National Info',
  FISV:'Fiserv',FITB:'Fifth Third Bancorp',FLT:'Fleetcor',FMC:'FMC Corp',FOX:'Fox Corp B',
  FOXA:'Fox Corp A',FRC:'First Republic',FRT:'Federal Realty',FTNT:'Fortinet',FTV:'Fortive',
  GD:'General Dynamics',GE:'GE Aerospace',GILD:'Gilead Sciences',GIS:'General Mills',
  GL:'Globe Life',GLW:'Corning',GM:'General Motors',GNRC:'Generac',GOOG:'Alphabet C',
  GOOGL:'Alphabet A',GPC:'Genuine Parts',GPN:'Global Payments',GRMN:'Garmin',GS:'Goldman Sachs',
  GWW:'W.W. Grainger',HAL:'Halliburton',HAS:'Hasbro',HBAN:'Huntington Bancshares',
  HCA:'HCA Healthcare',HD:'Home Depot',HOLX:'Hologic',HON:'Honeywell',HPE:'HPE',HPQ:'HP Inc',
  HRL:'Hormel Foods',HSIC:'Henry Schein',HST:'Host Hotels',HSY:'Hershey',HUM:'Humana',
  HWM:'Howmet Aerospace',IBM:'IBM',ICE:'Intercontinental Exchange',IDXX:'Idexx Labs',
  IEX:'IDEX Corp',IFF:'IFF',ILMN:'Illumina',INCY:'Incyte',INTC:'Intel',INTU:'Intuit',
  INVH:'Invitation Homes',IP:'International Paper',IPG:'Interpublic',IQV:'IQVIA',IR:'Ingersoll Rand',
  IRM:'Iron Mountain',ISRG:'Intuitive Surgical',IT:'Gartner',ITW:'Illinois Tool Works',
  IVZ:'Invesco',J:'Jacobs Solutions',JBHT:'J.B. Hunt',JCI:'Johnson Controls',JKHY:'Jack Henry',
  JNJ:'Johnson & Johnson',JNPR:'Juniper Networks',JPM:'JPMorgan Chase',K:'Kellogg',
  KDP:'Keurig Dr Pepper',KEY:'KeyCorp',KEYS:'Keysight',KHC:'Kraft Heinz',KIM:'Kimco Realty',
  KLAC:'KLA Corp',KMB:'Kimberly-Clark',KMI:'Kinder Morgan',KMX:'CarMax',KO:'Coca-Cola',
  KR:'Kroger',L:'Loews Corp',LDOS:'Leidos',LEN:'Lennar',LH:'Labcorp',LHX:'L3Harris',
  LIN:'Linde',LKQ:'LKQ Corp',LLY:'Eli Lilly',LMT:'Lockheed Martin',LNC:'Lincoln National',
  LNT:'Alliant Energy',LOW:'Lowe\'s',LRCX:'Lam Research',LUMN:'Lumen Technologies',
  LUV:'Southwest Airlines',LVS:'Las Vegas Sands',LW:'Lamb Weston',LYB:'LyondellBasell',
  LYV:'Live Nation',MA:'Mastercard',MAA:'Mid-America Apartment',MAR:'Marriott',MAS:'Masco',
  MCD:'McDonald\'s',MCHP:'Microchip Technology',MCK:'McKesson',MCO:'Moody\'s',MDLZ:'Mondelez',
  MDT:'Medtronic',MET:'MetLife',META:'Meta Platforms',MGM:'MGM Resorts',MHK:'Mohawk Industries',
  MKC:'McCormick',MKTX:'MarketAxess',MLM:'Martin Marietta',MMC:'Marsh McLennan',MMM:'3M',
  MNST:'Monster Beverage',MO:'Altria',MOH:'Molina Healthcare',MOS:'Mosaic',MPC:'Marathon Petroleum',
  MPWR:'Monolithic Power',MRK:'Merck',MRNA:'Moderna',MRO:'Marathon Oil',MS:'Morgan Stanley',
  MSCI:'MSCI Inc',MSFT:'Microsoft',MSI:'Motorola Solutions',MTB:'M&T Bank',MTCH:'Match Group',
  MTD:'Mettler-Toledo',MU:'Micron',NCLH:'Norwegian Cruise',NDAQ:'Nasdaq Inc',NDSN:'Nordson',
  NEE:'NextEra Energy',NEM:'Newmont',NFLX:'Netflix',NI:'NiSource',NKE:'Nike',NOC:'Northrop Grumman',
  NOW:'ServiceNow',NRG:'NRG Energy',NSC:'Norfolk Southern',NTAP:'NetApp',NTRS:'Northern Trust',
  NUE:'Nucor',NVDA:'Nvidia',NVR:'NVR Inc',NWL:'Newell Brands',NWS:'News Corp B',NWSA:'News Corp A',
  NXPI:'NXP Semiconductors',O:'Realty Income',ODFL:'Old Dominion Freight',OGN:'Organon',
  OKE:'Oneok',OMC:'Omnicom',ON:'ON Semiconductor',ORCL:'Oracle',ORLY:'O\'Reilly Auto',
  OTIS:'Otis Worldwide',OXY:'Occidental Petroleum',PARA:'Paramount',PAYC:'Paycom',PAYX:'Paychex',
  PCAR:'Paccar',PCG:'PG&E',PEAK:'Healthpeak',PEG:'PSEG',PEP:'PepsiCo',PFE:'Pfizer',
  PFG:'Principal Financial',PG:'Procter & Gamble',PGR:'Progressive',PH:'Parker Hannifin',
  PHM:'PulteGroup',PKG:'Packaging Corp',PKI:'PerkinElmer',PLD:'Prologis',PM:'Philip Morris',
  PNC:'PNC Financial',PNR:'Pentair',PNW:'Pinnacle West',POOL:'Pool Corp',PPG:'PPG Industries',
  PPL:'PPL Corp',PRU:'Prudential',PSA:'Public Storage',PSX:'Phillips 66',PTC:'PTC Inc',
  PVH:'PVH Corp',PWR:'Quanta Services',PXD:'Pioneer Natural',PYPL:'PayPal',QCOM:'Qualcomm',
  QRVO:'Qorvo',RCL:'Royal Caribbean',RE:'Everest Re',REG:'Regency Centers',REGN:'Regeneron',
  RF:'Regions Financial',RHI:'Robert Half',RJF:'Raymond James',RL:'Ralph Lauren',RMD:'ResMed',
  ROK:'Rockwell Automation',ROL:'Rollins',ROP:'Roper Technologies',ROST:'Ross Stores',
  RSG:'Republic Services',RTX:'RTX Corp',SBAC:'SBA Communications',SBNY:'Signature Bank',
  SBUX:'Starbucks',SCHW:'Charles Schwab',SEE:'Sealed Air',SHW:'Sherwin-Williams',
  SIVB:'SVB Financial',SJM:'J.M. Smucker',SLB:'Schlumberger',SNA:'Snap-on',SNPS:'Synopsys',
  SO:'Southern Company',SPG:'Simon Property',SPGI:'S&P Global',SRE:'Sempra',STE:'Steris',
  STT:'State Street',STX:'Seagate',STZ:'Constellation Brands',SWK:'Stanley Black & Decker',
  SWKS:'Skyworks',SYF:'Synchrony',SYK:'Stryker',SYY:'Sysco',T:'AT&T',TAP:'Molson Coors',
  TDG:'TransDigm',TDY:'Teledyne',TECH:'Bio-Techne',TEL:'TE Connectivity',TER:'Teradyne',
  TFC:'Truist Financial',TFX:'Teleflex',TGT:'Target',TJX:'TJX Companies',TMO:'Thermo Fisher',
  TMUS:'T-Mobile',TPR:'Tapestry',TRGP:'Targa Resources',TRMB:'Trimble',TROW:'T. Rowe Price',
  TRV:'Travelers',TSCO:'Tractor Supply',TSLA:'Tesla',TSN:'Tyson Foods',TT:'Trane Technologies',
  TTWO:'Take-Two Interactive',TXN:'Texas Instruments',TXT:'Textron',TYL:'Tyler Technologies',
  UAL:'United Airlines',UDR:'UDR Inc',UHS:'Universal Health',ULTA:'Ulta Beauty',UNH:'UnitedHealth',
  UNP:'Union Pacific',UPS:'UPS',URI:'United Rentals',USB:'U.S. Bancorp',V:'Visa',
  VFC:'VF Corp',VICI:'Vici Properties',VLO:'Valero Energy',VMC:'Vulcan Materials',VNO:'Vornado',
  VRSK:'Verisk Analytics',VRSN:'VeriSign',VRTX:'Vertex Pharma',VTR:'Ventas',VTRS:'Viatris',
  VZ:'Verizon',WAB:'Wabtec',WAT:'Waters Corp',WBA:'Walgreens',WBD:'Warner Bros Discovery',
  WDC:'Western Digital',WEC:'WEC Energy',WELL:'Welltower',WFC:'Wells Fargo',WHR:'Whirlpool',
  WM:'Waste Management',WMB:'Williams Companies',WMT:'Walmart',WRB:'Berkley Corp',
  WRK:'WestRock',WST:'West Pharma',WTW:'Willis Towers Watson',WY:'Weyerhaeuser',
  WYNN:'Wynn Resorts',XEL:'Xcel Energy',XOM:'ExxonMobil',XRAY:'Dentsply Sirona',XYL:'Xylem',
  YUM:'Yum! Brands',ZBH:'Zimmer Biomet',ZBRA:'Zebra Technologies',ZION:'Zions Bancorp',ZTS:'Zoetis',
  // NASDAQ 100 extras
  ABNB:'Airbnb',APP:'AppLovin',ARM:'Arm Holdings',ASML:'ASML',AZN:'AstraZeneca',CCEP:'Coca-Cola Europacific',
  CRWD:'CrowdStrike',DASH:'DoorDash',DDOG:'Datadog',GEHC:'GE HealthCare',GFS:'GlobalFoundries',
  LULU:'Lululemon',MDB:'MongoDB',MELI:'MercadoLibre',MRVL:'Marvell',PANW:'Palo Alto Networks',
  PDD:'PDD Holdings',SMCI:'Super Micro',SPLK:'Splunk',TEAM:'Atlassian',TTD:'Trade Desk',
  WDAY:'Workday',ZS:'Zscaler',
  // TSX 60
  'RY.TO':'Royal Bank','TD.TO':'TD Bank','BNS.TO':'Bank of Nova Scotia','BMO.TO':'BMO',
  'CM.TO':'CIBC','ENB.TO':'Enbridge','CNR.TO':'CN Rail','CP.TO':'CP Kansas City',
  'TRP.TO':'TC Energy','SU.TO':'Suncor','CNQ.TO':'Canadian Natural','MFC.TO':'Manulife',
  'SLF.TO':'Sun Life','BCE.TO':'BCE','T.TO':'Telus','ABX.TO':'Barrick Gold',
  'NTR.TO':'Nutrien','FNV.TO':'Franco-Nevada','CSU.TO':'Constellation Software',
  'SHOP.TO':'Shopify','ATD.TO':'Alimentation Couche-Tard','WCN.TO':'Waste Connections',
  'IFC.TO':'Intact Financial','QSR.TO':'Restaurant Brands','DOL.TO':'Dollarama',
  'SAP.TO':'Saputo','GIB-A.TO':'CGI Group','WSP.TO':'WSP Global','CCO.TO':'Cameco',
  'TRI.TO':'Thomson Reuters','BAM.TO':'Brookfield Asset Mgmt','BN.TO':'Brookfield Corp',
  'POW.TO':'Power Corp','FFH.TO':'Fairfax Financial','GWO.TO':'Great-West Lifeco',
  'IAG.TO':'iA Financial','NA.TO':'National Bank','EMA.TO':'Emera','FTS.TO':'Fortis',
  'AQN.TO':'Algonquin Power','H.TO':'Hydro One','MG.TO':'Magna','L.TO':'Loblaw',
  'CTC-A.TO':'Canadian Tire','WPM.TO':'Wheaton Precious','AEM.TO':'Agnico Eagle',
  'K.TO':'Kinross Gold','FM.TO':'First Quantum','IMO.TO':'Imperial Oil','CVE.TO':'Cenovus',
  'HSE.TO':'Husky Energy','PPL.TO':'Pembina Pipeline','IPL.TO':'Inter Pipeline',
  'KEY.TO':'Keyera','GFL.TO':'GFL Environmental','TFII.TO':'TFI International',
  'STN.TO':'Stantec','OTEX.TO':'Open Text','BB.TO':'BlackBerry','LSPD.TO':'Lightspeed',
  // FTSE 100
  'III.L':'3i Group','ADM.L':'Admiral Group','AAF.L':'Airtel Africa','AAL.L':'Anglo American',
  'ANTO.L':'Antofagasta','AHT.L':'Ashtead','ABF.L':'Associated British Foods','AZN.L':'AstraZeneca',
  'AUTO.L':'Auto Trader','AVV.L':'AVEVA','AV.L':'Aviva','BME.L':'B&M European',
  'BA.L':'BAE Systems','BARC.L':'Barclays','BDEV.L':'Barratt Developments','BEZ.L':'Beazley',
  'BKG.L':'Berkeley Group','BP.L':'BP','BATS.L':'British American Tobacco','BLND.L':'British Land',
  'BT-A.L':'BT Group','BNZL.L':'Bunzl','BRBY.L':'Burberry','CCH.L':'Coca-Cola HBC',
  'CPG.L':'Compass Group','CNA.L':'Centrica','CRH.L':'CRH','CRDA.L':'Croda',
  'DCC.L':'DCC','DGE.L':'Diageo','DPLM.L':'Diploma','EDV.L':'Endeavour Mining',
  'ENT.L':'Entain','EXPN.L':'Experian','FCIT.L':'F&C Investment Trust','FRAS.L':'Frasers Group',
  'FRES.L':'Fresnillo','GLEN.L':'Glencore','GSK.L':'GSK','HLN.L':'Haleon',
  'HLMA.L':'Halma','HSBA.L':'HSBC','IHG.L':'InterContinental Hotels','IMB.L':'Imperial Brands',
  'INF.L':'Informa','ITV.L':'ITV','JD.L':'JD Sports','KGF.L':'Kingfisher',
  'LAND.L':'Land Securities','LGEN.L':'Legal & General','LLOY.L':'Lloyds Banking',
  'LSEG.L':'London Stock Exchange','MNG.L':'M&G','MRO.L':'Melrose Industries',
  'MNDI.L':'Mondi','NG.L':'National Grid','NWG.L':'NatWest','NXT.L':'Next',
  'OCDO.L':'Ocado','PSON.L':'Pearson','PSH.L':'Pershing Square','PSN.L':'Persimmon',
  'PHNX.L':'Phoenix Group','PRU.L':'Prudential','RKT.L':'Reckitt','REL.L':'RELX',
  'RIO.L':'Rio Tinto','RMV.L':'Rightmove','RR.L':'Rolls-Royce','RS1.L':'RS Group',
  'RTO.L':'Rentokil Initial','SAG.L':'Sage Group','SBRY.L':'Sainsbury\'s','SDR.L':'Schroders',
  'SGE.L':'Sage Group','SGRO.L':'Segro','SHEL.L':'Shell','SJP.L':'St. James\'s Place',
  'SKG.L':'Smurfit Kappa','SMDS.L':'Smith DS','SMIN.L':'Smiths Group','SMT.L':'Scottish Mortgage',
  'SN.L':'Smith & Nephew','SPX.L':'Spirax-Sarco','SSE.L':'SSE','STAN.L':'Standard Chartered',
  'STJ.L':'St James Place','SVT.L':'Severn Trent','TSCO.L':'Tesco','TW.L':'Taylor Wimpey',
  'ULVR.L':'Unilever','UTG.L':'Unite Group','UU.L':'United Utilities','VOD.L':'Vodafone',
  'WEIR.L':'Weir Group','WPP.L':'WPP','WTB.L':'Whitbread',
};

export const SP500 = [
  "AAPL","ABBV","ABT","ACN","ADBE","ADI","ADM","ADP","ADSK","AEE","AEP","AES","AFL","AIG","AIZ",
  "AJG","AKAM","ALB","ALGN","ALK","ALL","ALLE","AMAT","AMCR","AMD","AME","AMGN","AMP","AMT","AMZN",
  "ANET","ANSS","AON","AOS","APA","APD","APH","APTV","ARE","ATO","ATVI","AVB","AVGO","AVY","AWK",
  "AXP","AZO","BA","BAC","BAX","BBWI","BBY","BDX","BEN","BF.B","BIIB","BIO","BK","BKNG","BKR",
  "BLK","BMY","BR","BRK.B","BRO","BSX","BWA","BXP","C","CAG","CAH","CARR","CAT","CB","CBOE",
  "CBRE","CCI","CCL","CDAY","CDNS","CDW","CE","CEG","CF","CFG","CHD","CHRW","CHTR","CI","CINF",
  "CL","CLX","CMA","CMCSA","CME","CMG","CMI","CMS","CNC","CNP","COF","COO","COP","COST","CPB",
  "CPRT","CPT","CRL","CRM","CSCO","CSGP","CSX","CTAS","CTLT","CTRA","CTSH","CTVA","CVS","CVX",
  "CZR","D","DAL","DD","DE","DFS","DG","DGX","DHI","DHR","DIS","DISH","DLR","DLTR","DOV",
  "DOW","DPZ","DRI","DTE","DUK","DVA","DVN","DXC","DXCM","EA","EBAY","ECL","ED","EFX","EIX",
  "EL","EMN","EMR","ENPH","EOG","EPAM","EQIX","EQR","EQT","ESS","ETN","ETR","EVRG","EW",
  "EXC","EXPD","EXPE","EXR","F","FANG","FAST","FBHS","FCX","FDS","FDX","FE","FFIV","FIS","FISV",
  "FITB","FLT","FMC","FOX","FOXA","FRC","FRT","FTNT","FTV","GD","GE","GILD","GIS","GL","GLW",
  "GM","GNRC","GOOG","GOOGL","GPC","GPN","GRMN","GS","GWW","HAL","HAS","HBAN","HCA","HD","HOLX",
  "HON","HPE","HPQ","HRL","HSIC","HST","HSY","HUM","HWM","IBM","ICE","IDXX","IEX","IFF","ILMN",
  "INCY","INTC","INTU","INVH","IP","IPG","IQV","IR","IRM","ISRG","IT","ITW","IVZ","J","JBHT",
  "JCI","JKHY","JNJ","JNPR","JPM","K","KDP","KEY","KEYS","KHC","KIM","KLAC","KMB","KMI","KMX",
  "KO","KR","L","LDOS","LEN","LH","LHX","LIN","LKQ","LLY","LMT","LNC","LNT","LOW","LRCX",
  "LUMN","LUV","LVS","LW","LYB","LYV","MA","MAA","MAR","MAS","MCD","MCHP","MCK","MCO","MDLZ",
  "MDT","MET","META","MGM","MHK","MKC","MKTX","MLM","MMC","MMM","MNST","MO","MOH","MOS","MPC",
  "MPWR","MRK","MRNA","MRO","MS","MSCI","MSFT","MSI","MTB","MTCH","MTD","MU","NCLH","NDAQ",
  "NDSN","NEE","NEM","NFLX","NI","NKE","NOC","NOW","NRG","NSC","NTAP","NTRS","NUE","NVDA",
  "NVR","NWL","NWS","NWSA","NXPI","O","ODFL","OGN","OKE","OMC","ON","ORCL","ORLY","OTIS","OXY",
  "PARA","PAYC","PAYX","PCAR","PCG","PEAK","PEG","PEP","PFE","PFG","PG","PGR","PH","PHM","PKG",
  "PKI","PLD","PM","PNC","PNR","PNW","POOL","PPG","PPL","PRU","PSA","PSX","PTC","PVH","PWR",
  "PXD","PYPL","QCOM","QRVO","RCL","RE","REG","REGN","RF","RHI","RJF","RL","RMD","ROK","ROL",
  "ROP","ROST","RSG","RTX","SBAC","SBNY","SBUX","SCHW","SEE","SHW","SIVB","SJM","SLB","SNA",
  "SNPS","SO","SPG","SPGI","SRE","STE","STT","STX","STZ","SWK","SWKS","SYF","SYK","SYY",
  "T","TAP","TDG","TDY","TECH","TEL","TER","TFC","TFX","TGT","TJX","TMO","TMUS","TPR","TRGP",
  "TRMB","TROW","TRV","TSCO","TSLA","TSN","TT","TTWO","TXN","TXT","TYL","UAL","UDR","UHS",
  "ULTA","UNH","UNP","UPS","URI","USB","V","VFC","VICI","VLO","VMC","VNO","VRSK","VRSN","VRTX",
  "VTR","VTRS","VZ","WAB","WAT","WBA","WBD","WDC","WEC","WELL","WFC","WHR","WM","WMB","WMT",
  "WRB","WRK","WST","WTW","WY","WYNN","XEL","XOM","XRAY","XYL","YUM","ZBH","ZBRA","ZION","ZTS",
];

export const NASDAQ100 = [
  "AAPL","ABNB","ADBE","ADI","ADP","ADSK","AEP","AMAT","AMD","AMGN","AMZN","ANSS","APP","ARM",
  "ASML","AVGO","AZN","BIIB","BKNG","BKR","CCEP","CDNS","CDW","CEG","CHTR","CMCSA","COST",
  "CPRT","CRWD","CSCO","CSGP","CTAS","CTSH","DASH","DDOG","DLTR","DXCM","EA","EXC","FANG",
  "FAST","FTNT","GEHC","GFS","GILD","GOOG","GOOGL","HON","IDXX","ILMN","INTC","INTU","ISRG",
  "KDP","KHC","KLAC","LIN","LRCX","LULU","MAR","MCHP","MDB","MDLZ","MELI","META","MNST",
  "MRNA","MRVL","MSFT","MU","NFLX","NVDA","NXPI","ODFL","ON","ORLY","PANW","PAYX","PCAR",
  "PDD","PEP","PYPL","QCOM","REGN","ROST","SBUX","SMCI","SNPS","SPLK","TEAM","TMUS","TSLA",
  "TTD","TTWO","TXN","VRSK","VRTX","WBD","WDAY","XEL","ZS",
];

export const TSX60 = [
  "RY.TO","TD.TO","BNS.TO","BMO.TO","CM.TO","ENB.TO","CNR.TO","CP.TO","TRP.TO","SU.TO",
  "CNQ.TO","MFC.TO","SLF.TO","BCE.TO","T.TO","ABX.TO","NTR.TO","FNV.TO","CSU.TO","SHOP.TO",
  "ATD.TO","WCN.TO","IFC.TO","QSR.TO","DOL.TO","SAP.TO","GIB-A.TO","WSP.TO","CCO.TO","TRI.TO",
  "BAM.TO","BN.TO","POW.TO","FFH.TO","GWO.TO","IAG.TO","NA.TO","EMA.TO","FTS.TO","AQN.TO",
  "H.TO","MG.TO","L.TO","CTC-A.TO","WPM.TO","AEM.TO","K.TO","FM.TO","IMO.TO","CVE.TO",
  "HSE.TO","PPL.TO","IPL.TO","KEY.TO","GFL.TO","TFII.TO","STN.TO","OTEX.TO","BB.TO","LSPD.TO",
];

export const FTSE100 = [
  "III.L","ADM.L","AAF.L","AAL.L","ANTO.L","AHT.L","ABF.L","AZN.L","AUTO.L","AVV.L",
  "AV.L","BME.L","BA.L","BARC.L","BDEV.L","BEZ.L","BKG.L","BP.L","BATS.L","BLND.L",
  "BT-A.L","BNZL.L","BRBY.L","CCH.L","CPG.L","CNA.L","CRH.L","CRDA.L","DCC.L","DGE.L",
  "DPLM.L","EDV.L","ENT.L","EXPN.L","FCIT.L","FRAS.L","FRES.L","GLEN.L","GSK.L","HLN.L",
  "HLMA.L","HSBA.L","IHG.L","IMB.L","INF.L","ITV.L","JD.L","KGF.L","LAND.L",
  "LGEN.L","LLOY.L","LSEG.L","MNG.L","MRO.L","MNDI.L","NG.L","NWG.L","NXT.L","OCDO.L",
  "PSON.L","PSH.L","PSN.L","PHNX.L","PRU.L","RKT.L","REL.L","RIO.L","RMV.L","RR.L",
  "RS1.L","RTO.L","SAG.L","SBRY.L","SDR.L","SGE.L","SGRO.L","SHEL.L","SJP.L","SKG.L",
  "SMDS.L","SMIN.L","SMT.L","SN.L","SPX.L","SSE.L","STAN.L","STJ.L","SVT.L","TSCO.L",
  "TW.L","ULVR.L","UTG.L","UU.L","VOD.L","WEIR.L","WPP.L","WTB.L",
];
