import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Malaysia Economy 2026 — GDP, Trade, Semiconductors & Key Data', description: 'Malaysia economy in 2026: GDP, growth, inflation, trade, and key indicators. A major semiconductor and palm oil exporter in Southeast Asia. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/malaysia-economy' } };
export default async function MalaysiaEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('MYS');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Malaysia Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Malaysia's GDP in ${year}?`, acceptedAnswer: { '@type': 'Answer', text: `Malaysia's GDP is approximately ${formatValue(gdp?.value, 'currency')} in ${year}. Malaysia is ASEAN's 3rd largest economy after Indonesia and Thailand, and a critical node in the global semiconductor supply chain. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/malaysia" className="hover:text-gray-600 transition">Malaysia</Link><span className="mx-2">/</span><span className="text-gray-600">Malaysia Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Malaysia Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">ASEAN&apos;s 3rd largest economy · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Malaysia Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Malaysia is one of Southeast Asia&apos;s most developed economies and a critical node in the global semiconductor supply chain. The country performs over 13% of the world&apos;s chip packaging and testing, making it indispensable to electronics manufacturing. Penang is known as the &quot;Silicon Valley of the East,&quot; hosting Intel, AMD, Broadcom, and dozens of other semiconductor firms. Beyond chips, Malaysia is the world&apos;s second-largest palm oil producer, a significant oil and gas exporter (Petronas is one of Asia&apos;s largest energy companies), and has a growing Islamic finance sector — Kuala Lumpur is the global hub for sukuk (Islamic bonds).</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Malaysia&apos;s GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} places it as an upper-middle-income country approaching the high-income threshold. The government&apos;s Shared Prosperity Vision aims to achieve developed-nation status by 2030. However, Malaysia faces the &quot;middle-income trap&quot; challenge — wages have risen enough to lose low-cost manufacturing competitiveness against <Link href="/vietnam-economy" className="text-[#0066cc] hover:underline">Vietnam</Link> and Cambodia, but not enough to compete with <Link href="/singapore-economy" className="text-[#0066cc] hover:underline">Singapore</Link> and <Link href="/south-korea-economy" className="text-[#0066cc] hover:underline">South Korea</Link> in high-value services.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]"><Link href="/trade-by-country" className="text-[#0066cc] hover:underline">Trade</Link> openness exceeds 130% of GDP, reflecting deep integration into global supply chains. <Link href="/china-economy" className="text-[#0066cc] hover:underline">China</Link> is Malaysia&apos;s largest trading partner, followed by <Link href="/singapore-economy" className="text-[#0066cc] hover:underline">Singapore</Link> and the <Link href="/us-economy" className="text-[#0066cc] hover:underline">United States</Link>. The country&apos;s multi-ethnic society (Malay, Chinese, Indian) and strategic location along the Strait of Malacca — one of the world&apos;s busiest shipping lanes — give it unique economic and geopolitical significance within <Link href="/asean-economy" className="text-[#0066cc] hover:underline">ASEAN</Link>.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/malaysia', label: 'Full Profile →' }, { href: '/singapore-economy', label: 'Singapore Economy' }, { href: '/indonesia-economy', label: 'Indonesia Economy' }, { href: '/thailand-economy', label: 'Thailand Economy' }, { href: '/asean-economy', label: 'ASEAN Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
