import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Romania Economy 2026 — GDP, Growth, IT Sector & Key Data', description: 'Romania economy in 2026: GDP, growth, inflation, IT sector boom, and key indicators. One of the EU\'s fastest-growing economies. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/romania-economy' } };
export default async function RomaniaEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('ROU');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Romania Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `How fast is Romania's economy growing?`, acceptedAnswer: { '@type': 'Answer', text: `Romania has been one of the EU's fastest-growing economies, averaging 4-5% GDP growth since joining in 2007. The IT sector is a particular strength — Romania has more IT workers per capita than most Western European countries, with Bucharest and Cluj-Napoca emerging as tech hubs. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/romania" className="hover:text-gray-600 transition">Romania</Link><span className="mx-2">/</span><span className="text-gray-600">Romania Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Romania Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">EU&apos;s fastest-growing large economy · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Romania Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Romania has been one of the <Link href="/eu-economy" className="text-[#0066cc] hover:underline">EU&apos;s</Link> fastest-growing economies since accession in 2007, with GDP roughly tripling in nominal terms. With 19 million people, it is the EU&apos;s 6th most populous member and has undergone rapid modernization. The IT and software sector is a standout — Romania has more IT professionals per capita than most Western European countries, fueled by strong mathematics education, competitive wages, and a flat 10% income tax that attracts talent. Bucharest and Cluj-Napoca have become genuine European tech hubs.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Romania&apos;s economy is diversified across automotive manufacturing (Dacia/Renault is the country&apos;s largest industrial employer, Ford also has a major plant), agriculture (one of Europe&apos;s largest grain producers), energy (significant oil, gas, and Black Sea offshore reserves), and services. The country has the fastest internet speeds in Europe — a quirk of late infrastructure development that allowed direct fiber deployment.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include significant brain drain (millions of Romanians have emigrated to Western Europe for higher wages), <Link href="/corruption-by-country" className="text-[#0066cc] hover:underline">corruption</Link> (improving but still above EU average), rural poverty, and infrastructure gaps. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is converging toward the EU average but remains roughly 30% below. Romania has not yet adopted the euro and maintains the Romanian leu. EU structural funds are a significant investment driver.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/romania', label: 'Full Profile →' }, { href: '/poland-economy', label: 'Poland Economy' }, { href: '/czech-republic-economy', label: 'Czech Republic' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/gdp-growth-by-country', label: 'GDP Growth' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
