import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Algeria Economy 2026 — GDP, Oil, Gas & Key Data', description: 'Algeria economy in 2026: GDP, growth, oil & gas exports, and key indicators. Africa\'s largest country and a major energy exporter to Europe. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/algeria-economy' } };
export default async function AlgeriaEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('DZA');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Algeria Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Algeria's economy based on?`, acceptedAnswer: { '@type': 'Answer', text: `Algeria's economy is heavily dependent on oil and natural gas, which account for 95% of export revenue and ~60% of government income. Algeria has Africa's largest natural gas reserves and is a key pipeline supplier to Southern Europe (Italy, Spain). Diversification away from hydrocarbons has been limited. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/algeria" className="hover:text-gray-600 transition">Algeria</Link><span className="mx-2">/</span><span className="text-gray-600">Algeria Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Algeria Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Africa&apos;s largest country by area · Major gas exporter · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Algeria Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Algeria is Africa&apos;s largest country by land area and one of the continent&apos;s top economies, powered almost entirely by hydrocarbons. Oil and natural gas account for 95% of export revenue and roughly 60% of government income. Algeria has Africa&apos;s largest proven natural gas reserves and is a critical pipeline supplier to Southern Europe — <Link href="/italy-economy" className="text-[#0066cc] hover:underline">Italy</Link> and <Link href="/spain-economy" className="text-[#0066cc] hover:underline">Spain</Link> depend heavily on Algerian gas, a dependency that increased after Europe cut Russian gas imports in 2022.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Algeria&apos;s economy has struggled to diversify beyond hydrocarbons despite decades of stated ambition to do so. The state controls most economic activity through Sonatrach (the national oil company, Africa&apos;s largest), and a heavy regulatory environment has deterred foreign investment outside the energy sector. Government subsidies on fuel, food, and housing consume a large share of the budget, making fiscal policy highly vulnerable to oil price swings.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">With a <Link href="/population-by-country" className="text-[#0066cc] hover:underline">population</Link> of 46 million (median age ~28), Algeria faces a youth employment crisis — <Link href="/unemployment-by-country" className="text-[#0066cc] hover:underline">unemployment</Link> is high, particularly among young people, and the economy doesn&apos;t create enough jobs to absorb new labor market entrants. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} places Algeria as a lower-middle-income country. Government <Link href="/debt-by-country" className="text-[#0066cc] hover:underline">debt</Link> is relatively low thanks to oil revenue, but foreign exchange reserves have declined significantly from their 2014 peak.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/algeria', label: 'Full Profile →' }, { href: '/morocco-economy', label: 'Morocco Economy' }, { href: '/egypt-economy', label: 'Egypt Economy' }, { href: '/saudi-arabia-economy', label: 'Saudi Arabia' }, { href: '/co2-emissions-by-country', label: 'CO2 Emissions' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
