import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Austria Economy 2026 — GDP, Tourism, Industry & Key Data', description: 'Austria economy in 2026: GDP, growth, inflation, tourism, and key indicators. A wealthy Alpine economy at the heart of Europe. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/austria-economy' } };
export default async function AustriaEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('AUT');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Austria Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Austria's GDP per capita?`, acceptedAnswer: { '@type': 'Answer', text: `Austria's GDP per capita is approximately ${formatValue(gdpPerCapita?.value, 'currency')} — among the highest in the EU. Austria benefits from its central European location, strong manufacturing, world-class tourism (Vienna, Alps), and close economic ties with Germany. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/austria" className="hover:text-gray-600 transition">Austria</Link><span className="mx-2">/</span><span className="text-gray-600">Austria Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Austria Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Wealthy Alpine economy · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Austria Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Austria is a wealthy, highly developed economy at the geographic and economic heart of Europe. With GDP per capita of {formatValue(gdpPerCapita?.value, 'currency')}, it ranks among the EU&apos;s wealthiest members. The economy combines German-style industrial strength with Alpine <Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">tourism</Link> — Vienna, Salzburg, and ski resorts attract over 30 million visitors annually, making tourism roughly 8% of GDP. Austria&apos;s manufacturing sector is deeply integrated with <Link href="/germany-economy" className="text-[#0066cc] hover:underline">Germany&apos;s</Link> supply chains, particularly in automotive components, machinery, and steel.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Austria hosts several major international organizations in Vienna (UN, OPEC, OSCE, IAEA), giving it outsized diplomatic significance. The banking sector has historically served as a bridge between Western and Eastern Europe, with Austrian banks (Raiffeisen, Erste Group) being among the largest lenders in Central and Eastern Europe. Red Bull, headquartered in Fuschl am See, is Austria&apos;s most globally recognized brand.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include dependence on <Link href="/germany-economy" className="text-[#0066cc] hover:underline">German</Link> economic performance (Germany is by far the largest trade partner), exposure to Eastern European economic risks through banking, an aging population, and the need to decarbonize while maintaining industrial competitiveness. Austria generates roughly 80% of electricity from <Link href="/renewable-energy-by-country" className="text-[#0066cc] hover:underline">renewables</Link> (primarily hydroelectric), one of the highest shares in the <Link href="/eu-economy" className="text-[#0066cc] hover:underline">EU</Link>. <Link href="/life-expectancy-by-country" className="text-[#0066cc] hover:underline">Life expectancy</Link> at {lifeExp?.value ? Number(lifeExp.value).toFixed(1) : '82'} years reflects excellent healthcare and quality of life.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/austria', label: 'Full Profile →' }, { href: '/germany-economy', label: 'Germany Economy' }, { href: '/switzerland-economy', label: 'Switzerland Economy' }, { href: '/czech-republic-economy', label: 'Czech Republic' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
