import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Forest Coverage by Country 2026 — Forest Area Rankings', description: 'Forest coverage by country: all countries ranked by % of land area covered by forest. From Suriname (95%+) to desert nations (<1%). Source: World Bank / FAO.', alternates: { canonical: 'https://statisticsoftheworld.com/forest-coverage-by-country' } };
export default async function ForestCoverageByCountryPage() {
  const data = await getIndicatorForAllCountries('AG.LND.FRST.ZS');
  const year = data[0]?.year || '2024';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `Forest Coverage by Country ${year}`, description: `Forest area as % of land for ${data.length} countries. Source: World Bank / FAO.`, url: 'https://statisticsoftheworld.com/forest-coverage-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Which country has the most forest?', acceptedAnswer: { '@type': 'Answer', text: `${data[0]?.country} has the highest forest coverage at ${formatValue(data[0]?.value, 'percent', 0)} of land area. By absolute forest area, Russia, Brazil, Canada, and the US have the most. Global forest cover has declined from 31.6% in 1990 to ~31% today, with tropical deforestation partially offset by temperate reforestation.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">Forest Coverage by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">Forest Coverage by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · % of land area · Source: World Bank / FAO · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Global Forest Cover</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Forests cover approximately 31% of the world&apos;s land area and are critical for carbon sequestration, biodiversity, water cycling, and the livelihoods of 1.6 billion people. Deforestation is concentrated in the tropics — <Link href="/brazil-economy" className="text-[#0066cc] hover:underline">Brazil</Link>, <Link href="/indonesia-economy" className="text-[#0066cc] hover:underline">Indonesia</Link>, and the DR Congo lose the most forest annually. <Link href="/china-economy" className="text-[#0066cc] hover:underline">China</Link> and <Link href="/india-economy" className="text-[#0066cc] hover:underline">India</Link> have increased forest cover through massive reforestation programs. <Link href="/co2-emissions-by-country" className="text-[#0066cc] hover:underline">CO2 emissions</Link> from deforestation account for ~10% of global emissions.</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">Forest %</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/forest-area`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]"><span className={(d.value || 0) > 50 ? 'text-green-600' : 'text-[#0d1b2a]'}>{formatValue(d.value, 'percent', 0)}</span></td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/co2-emissions-by-country', label: 'CO2 Emissions' }, { href: '/renewable-energy-by-country', label: 'Renewable Energy' }, { href: '/brazil-economy', label: 'Brazil Economy' }, { href: '/indonesia-economy', label: 'Indonesia Economy' }, { href: '/population-density-by-country', label: 'Pop. Density' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
