import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Savings Rate by Country 2026 — Gross National Savings Ranked', description: 'Savings rate by country: all countries ranked by gross national savings as % of GNI. High savers fund investment; low savers depend on foreign capital. Source: World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/savings-rate-by-country' } };
export default async function SavingsRateByCountryPage() {
  const data = await getIndicatorForAllCountries('NY.GNS.ICTR.ZS');
  const year = data[0]?.year || '2024';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `Savings Rate by Country ${year}`, description: `Gross savings as % of GNI for ${data.length} countries. Source: World Bank.`, url: 'https://statisticsoftheworld.com/savings-rate-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Which countries save the most?', acceptedAnswer: { '@type': 'Answer', text: `${data[0]?.country} has the highest savings rate at ${formatValue(data[0]?.value, 'percent', 1)} of GNI. East Asian and Gulf economies tend to save 30-50% of income, while some African and Caribbean nations save under 5%. High savings fund domestic investment without relying on foreign capital.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">Savings Rate by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">Savings Rate by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · Gross savings % of GNI · Source: World Bank</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Global Savings Patterns</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Savings rates vary enormously. East Asian economies — <Link href="/china-economy" className="text-[#0066cc] hover:underline">China</Link> (~45%), <Link href="/singapore-economy" className="text-[#0066cc] hover:underline">Singapore</Link>, <Link href="/south-korea-economy" className="text-[#0066cc] hover:underline">South Korea</Link> — save 30-50% of income, funding massive domestic investment. Gulf oil exporters save even more when oil prices are high. The <Link href="/us-economy" className="text-[#0066cc] hover:underline">US</Link> saves roughly 18% — below the global average — relying on foreign capital inflows to fund its <Link href="/investment-rate-by-country" className="text-[#0066cc] hover:underline">investment</Link>. Savings drive the current account balance: high savers run surpluses, low savers run deficits.</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">Savings (% GNI)</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/gross-savings`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]">{formatValue(d.value, 'percent', 1)}</td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/investment-rate-by-country', label: 'Investment Rate' }, { href: '/gdp-growth-by-country', label: 'GDP Growth' }, { href: '/gdp-per-capita-by-country', label: 'GDP per Capita' }, { href: '/china-economy', label: 'China Economy' }, { href: '/singapore-economy', label: 'Singapore Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
