import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Finland Economy 2026 — GDP, Nokia, Education & Key Data', description: 'Finland economy in 2026: GDP, growth, inflation, education system, and key indicators. The world\'s happiest country with a high-tech, export-driven economy. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/finland-economy' } };
export default async function FinlandEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('FIN');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Finland Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Finland known for economically?`, acceptedAnswer: { '@type': 'Answer', text: `Finland is known for its world-class education system (consistently top PISA scores), Nokia (which still leads in telecom infrastructure), a thriving gaming industry (Supercell, Rovio), forestry/paper exports, and one of the world's strongest welfare states. Finland joined NATO in 2023. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/finland" className="hover:text-gray-600 transition">Finland</Link><span className="mx-2">/</span><span className="text-gray-600">Finland Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Finland Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">World&apos;s happiest country · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Finland Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Finland is a Nordic high-income economy of 5.5 million people that consistently ranks #1 globally for happiness, <Link href="/education-spending-by-country" className="text-[#0066cc] hover:underline">education</Link> quality, and government transparency. The Finnish education system — with no standardized testing before age 16, minimal homework, and highly trained teachers — produces top PISA scores and is studied worldwide. This human capital foundation supports a knowledge-intensive economy strong in technology, engineering, and design.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Nokia remains Finland&apos;s largest company, having pivoted from mobile phones to telecom infrastructure (5G network equipment, competing with Ericsson and Huawei). Finland&apos;s gaming industry punches far above its weight — Supercell (Clash of Clans) and Rovio (Angry Birds) established Helsinki as a global gaming hub. The forestry and paper industry (UPM, Stora Enso) is a traditional pillar, now transitioning toward bioplastics and sustainable materials. Finland also has significant mining potential in Europe-critical minerals.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Finland joined NATO in 2023, ending decades of military non-alignment, fundamentally reshaping its geopolitical position. The economy shares a 1,340km border with <Link href="/russia-economy" className="text-[#0066cc] hover:underline">Russia</Link> — the longest of any <Link href="/eu-economy" className="text-[#0066cc] hover:underline">EU</Link> member — and Russian trade cessation after 2022 required economic adjustment. Challenges include an aging population, high structural <Link href="/unemployment-by-country" className="text-[#0066cc] hover:underline">unemployment</Link> relative to Nordic peers, and a small domestic market that makes export competitiveness essential. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is among the world&apos;s highest.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/finland', label: 'Full Profile →' }, { href: '/denmark-economy', label: 'Denmark Economy' }, { href: '/norway-economy', label: 'Norway Economy' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/education-spending-by-country', label: 'Education Spending' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
