import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Ukraine Economy 2026 — GDP, War Impact, Reconstruction & Key Data', description: 'Ukraine economy in 2026: GDP, war impact, reconstruction, agriculture, and key indicators. Europe\'s largest agricultural exporter rebuilding from conflict. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/ukraine-economy' } };
export default async function UkraineEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('UKR');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Ukraine Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `How has the war affected Ukraine's economy?`, acceptedAnswer: { '@type': 'Answer', text: `Russia's full-scale invasion in 2022 caused Ukraine's GDP to contract by roughly 30% — one of the largest wartime economic collapses in modern history. Infrastructure damage exceeds $150 billion. Despite this, Ukraine's economy has shown remarkable resilience, with partial recovery driven by Western financial support, agricultural exports, and the IT sector continuing to operate remotely. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/ukraine" className="hover:text-gray-600 transition">Ukraine</Link><span className="mx-2">/</span><span className="text-gray-600">Ukraine Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Ukraine Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Rebuilding from conflict · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Ukraine Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]"><Link href="/russia-economy" className="text-[#0066cc] hover:underline">Russia&apos;s</Link> full-scale invasion in February 2022 caused one of the largest wartime economic collapses in modern history — Ukraine&apos;s GDP contracted by roughly 30% in 2022. Infrastructure damage has been estimated at over $150 billion by the World Bank. Millions of Ukrainians became refugees, the industrial east was devastated, and Black Sea ports — critical for grain exports — were blockaded. The economic toll is comparable to the Great Depression in severity.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Despite this, Ukraine&apos;s economy has shown remarkable resilience. GDP partially recovered in 2023-2024, supported by over $100 billion in Western financial assistance, the reopening of grain export corridors, and a thriving IT sector that continued operating remotely through the conflict. Ukraine is one of the world&apos;s largest grain and sunflower oil exporters — the &quot;breadbasket of Europe&quot; — and agricultural exports resumed through a Black Sea corridor agreement and overland routes through <Link href="/poland-economy" className="text-[#0066cc] hover:underline">Poland</Link> and <Link href="/romania-economy" className="text-[#0066cc] hover:underline">Romania</Link>.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The reconstruction effort ahead will be massive — estimates range from $400 billion to over $1 trillion, potentially the largest rebuild since the Marshall Plan. Ukraine has EU candidate status and is working to align its institutions with <Link href="/eu-economy" className="text-[#0066cc] hover:underline">EU</Link> standards. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} reflects the wartime devastation — it was approximately $4,000 pre-war. The country&apos;s pre-war strengths in aerospace, IT, agriculture, and heavy industry provide a foundation for recovery if peace is achieved.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/ukraine', label: 'Full Profile →' }, { href: '/russia-economy', label: 'Russia Economy' }, { href: '/poland-economy', label: 'Poland Economy' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/military-spending-by-country', label: 'Military Spending' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
