import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Investment Rate by Country 2026 — Gross Capital Formation Ranked', description: 'Investment rate by country: all countries ranked by gross capital formation as % of GDP. Which economies invest the most in infrastructure and capacity? Source: World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/investment-rate-by-country' } };
export default async function InvestmentRateByCountryPage() {
  const data = await getIndicatorForAllCountries('NE.GDI.TOTL.ZS');
  const year = data[0]?.year || '2024';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `Investment Rate by Country ${year}`, description: `Gross capital formation as % of GDP for ${data.length} countries. Source: World Bank.`, url: 'https://statisticsoftheworld.com/investment-rate-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Which country invests the most?', acceptedAnswer: { '@type': 'Answer', text: `${data[0]?.country} has the highest investment rate at ${formatValue(data[0]?.value, 'percent', 1)} of GDP. China and Ethiopia have historically invested 40%+ of GDP in infrastructure and capital. High investment rates drive future economic growth but require funding from domestic savings or foreign capital.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">Investment Rate by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">Investment Rate by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · Gross capital formation % GDP · Source: World Bank</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Global Investment Patterns</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Investment (gross capital formation) — spending on infrastructure, factories, machinery, and housing — drives future <Link href="/gdp-growth-by-country" className="text-[#0066cc] hover:underline">economic growth</Link>. <Link href="/china-economy" className="text-[#0066cc] hover:underline">China&apos;s</Link> investment rate of ~42% of GDP is exceptionally high, reflecting massive infrastructure and industrial capacity building. <Link href="/ethiopia-economy" className="text-[#0066cc] hover:underline">Ethiopia</Link> and other fast-growing economies also invest heavily. Advanced economies typically invest 20-25% of GDP. Investment must be funded by either domestic <Link href="/savings-rate-by-country" className="text-[#0066cc] hover:underline">savings</Link> or foreign capital inflows.</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">Investment (% GDP)</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/gross-capital-formation`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]">{formatValue(d.value, 'percent', 1)}</td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/savings-rate-by-country', label: 'Savings Rate' }, { href: '/gdp-growth-by-country', label: 'GDP Growth' }, { href: '/fdi-by-country', label: 'FDI Inflows' }, { href: '/china-economy', label: 'China Economy' }, { href: '/ethiopia-economy', label: 'Ethiopia Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
