import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Kuwait Economy 2026 — GDP, Oil, Sovereign Wealth & Key Data', description: 'Kuwait economy in 2026: GDP, oil revenue, sovereign wealth fund, and key indicators. One of the world\'s richest petrostates. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/kuwait-economy' } };
export default async function KuwaitEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('KWT');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Kuwait Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Kuwait's GDP per capita?`, acceptedAnswer: { '@type': 'Answer', text: `Kuwait's GDP per capita is approximately ${formatValue(gdpPerCapita?.value, 'currency')} — among the world's highest. Kuwait sits atop roughly 6% of global oil reserves and its sovereign wealth fund (Kuwait Investment Authority, est. 1953) is one of the world's oldest and largest at $800B+. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/kuwait" className="hover:text-gray-600 transition">Kuwait</Link><span className="mx-2">/</span><span className="text-gray-600">Kuwait Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Kuwait Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Oil-rich Gulf state · Home of the world&apos;s oldest SWF · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">{[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}</div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Kuwait Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Kuwait is a small but wealthy Gulf petrostate with approximately 6% of the world&apos;s proven oil reserves. Oil accounts for over 90% of government revenue and 95% of export earnings, making Kuwait one of the most oil-dependent economies on Earth. The Kuwait Investment Authority (KIA), established in 1953, is the world&apos;s oldest sovereign wealth fund with assets exceeding $800 billion — roughly $180,000 per citizen.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Kuwait&apos;s economy provides a generous welfare state for its ~1.5 million citizens (out of ~4.5 million total population — the rest are expatriate workers): no income tax, subsidized housing, free education and healthcare, and guaranteed government employment for nationals. This model creates low labor productivity incentives and a heavily segmented labor market where citizens work in the public sector and expatriates dominate the private sector.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Diversification has been slower than in <Link href="/uae-economy" className="text-[#0066cc] hover:underline">UAE</Link> or <Link href="/saudi-arabia-economy" className="text-[#0066cc] hover:underline">Saudi Arabia</Link>, partly due to a more politically complex parliamentary system that can block reform. Kuwait&apos;s parliament is the most powerful legislature in the Gulf, frequently clashing with the government over privatization and subsidy reform. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} ranks among the world&apos;s highest.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/country/kuwait', label: 'Full Profile →' }, { href: '/saudi-arabia-economy', label: 'Saudi Arabia' }, { href: '/uae-economy', label: 'UAE Economy' }, { href: '/qatar-economy', label: 'Qatar Economy' }, { href: '/richest-countries', label: 'Richest Countries' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}</div></div>
      </section><Footer /></main>);
}
