import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'UAE Economy 2026 — GDP, Dubai, Oil, Diversification & Key Data', description: 'UAE economy in 2026: GDP, growth, oil revenue, Dubai\'s diversification, tourism, and key indicators. The Gulf\'s most diversified economy. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/uae-economy' } };
export default async function UAEEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('ARE');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `UAE Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `How has Dubai diversified from oil?`, acceptedAnswer: { '@type': 'Answer', text: `Dubai has successfully diversified — oil now accounts for less than 5% of its GDP. Tourism (25M+ visitors), real estate, aviation (Emirates airline), logistics (Jebel Ali — the Middle East's largest port), finance (DIFC), and retail drive the economy. Abu Dhabi remains more oil-dependent but is diversifying through sovereign wealth fund investments.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/uae" className="hover:text-gray-600 transition">UAE</Link><span className="mx-2">/</span><span className="text-gray-600">UAE Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The UAE Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Gulf&apos;s most diversified economy · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">UAE Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The United Arab Emirates is a federation of seven emirates — Abu Dhabi and Dubai being by far the most economically significant — that has transformed from a desert trading post to one of the world&apos;s wealthiest and most connected economies in just five decades. Abu Dhabi holds the vast majority of the UAE&apos;s oil reserves and the Abu Dhabi Investment Authority (ADIA) is one of the world&apos;s largest sovereign wealth funds. Dubai has built a fundamentally different model based on <Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">tourism</Link>, aviation, logistics, real estate, and finance.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Dubai&apos;s diversification is genuinely remarkable: oil now accounts for less than 5% of its GDP. Emirates airline connects Dubai to over 150 destinations, making Dubai International the world&apos;s busiest airport for international passengers. Jebel Ali is the Middle East&apos;s largest container port. The Dubai International Financial Centre (DIFC) hosts over 4,000 firms. Tourism exceeds 25 million visitors annually. This model has made Dubai a global city on par with <Link href="/singapore-economy" className="text-[#0066cc] hover:underline">Singapore</Link>, Hong Kong, and London in connectivity.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The UAE population is roughly 90% expatriate — one of the highest foreign-born ratios in the world — reflecting a labor market model dependent on imported talent and workers at all skill levels. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is high but unevenly distributed between Emirati citizens and the large migrant workforce. The UAE is a member of <Link href="/brics-economy" className="text-[#0066cc] hover:underline">BRICS</Link> (joined 2024) and increasingly positions itself as a neutral ground between Western and non-Western economic blocs.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/uae', label: 'Full Profile →' }, { href: '/saudi-arabia-economy', label: 'Saudi Arabia Economy' }, { href: '/singapore-economy', label: 'Singapore Economy' }, { href: '/brics-economy', label: 'BRICS Economy' }, { href: '/richest-countries', label: 'Richest Countries' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
