import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Bangladesh Economy 2026 — GDP, Garments, Growth & Key Data', description: 'Bangladesh economy in 2026: GDP, growth, garment exports, and key indicators. The world\'s 2nd largest garment exporter with 170M+ people. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/bangladesh-economy' } };
export default async function BangladeshEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('BGD');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Bangladesh Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `How fast is Bangladesh growing?`, acceptedAnswer: { '@type': 'Answer', text: `Bangladesh has averaged 6-7% GDP growth over the past decade, making it one of the fastest-growing economies in Asia. The garment sector drives exports while remittances and microfinance have reduced poverty dramatically. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/bangladesh" className="hover:text-gray-600 transition">Bangladesh</Link><span className="mx-2">/</span><span className="text-gray-600">Bangladesh Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Bangladesh Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">World&apos;s 2nd largest garment exporter · 170M+ people · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Bangladesh Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Bangladesh is one of the world&apos;s most remarkable development success stories. Once dismissed by Henry Kissinger as a &quot;basket case,&quot; it has grown into a $450B+ economy with GDP growth averaging 6-7% annually for over a decade. The ready-made garment (RMG) sector is the engine: Bangladesh is the world&apos;s second-largest garment exporter after <Link href="/china-economy" className="text-[#0066cc] hover:underline">China</Link>, supplying H&M, Zara, Walmart, and nearly every global fashion brand. Garments account for over 80% of export earnings.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Bangladesh&apos;s development gains extend beyond GDP. <Link href="/life-expectancy-by-country" className="text-[#0066cc] hover:underline">Life expectancy</Link> now exceeds <Link href="/india-economy" className="text-[#0066cc] hover:underline">India&apos;s</Link> despite lower per capita income — a testament to effective public health programs, NGO networks (BRAC, Grameen Bank), and female empowerment initiatives. The <Link href="/fertility-rate-by-country" className="text-[#0066cc] hover:underline">fertility rate</Link> has fallen from 7 in the 1970s to around 2, and female labor force participation in garment factories has transformed gender dynamics. Microfinance, pioneered by Grameen Bank, has reached tens of millions of rural households.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include extreme vulnerability to climate change (much of the country is low-lying delta, at risk from rising sea levels and flooding), infrastructure bottlenecks, governance issues, and the need to diversify beyond garments. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} remains low, and the country is scheduled to graduate from UN Least Developed Country status, which will reduce trade preferences. Moving up the value chain into electronics, pharmaceuticals, and IT services is the key strategic priority.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/bangladesh', label: 'Full Profile →' }, { href: '/india-economy', label: 'India Economy' }, { href: '/vietnam-economy', label: 'Vietnam Economy' }, { href: '/population-by-country', label: 'Population' }, { href: '/gdp-growth-by-country', label: 'GDP Growth' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
