import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Portugal Economy 2026 — GDP, Tourism, Tech & Key Data', description: 'Portugal economy in 2026: GDP, growth, tourism, tech startups, golden visa, and key indicators. Southern Europe\'s turnaround story. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/portugal-economy' } };
export default async function PortugalEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('PRT');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Portugal Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `How has Portugal's economy recovered?`, acceptedAnswer: { '@type': 'Answer', text: `Portugal has undergone a remarkable economic turnaround since its 2011 debt crisis and bailout. Tourism has boomed (30M+ visitors), Lisbon has become a European tech hub (Web Summit relocated there), and the startup ecosystem attracted significant investment. Growth has consistently exceeded eurozone averages. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/portugal" className="hover:text-gray-600 transition">Portugal</Link><span className="mx-2">/</span><span className="text-gray-600">Portugal Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Portugal Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Southern Europe&apos;s turnaround story · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Portugal Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Portugal has undergone one of the most impressive economic turnarounds in the <Link href="/eu-economy" className="text-[#0066cc] hover:underline">European Union</Link>. After a severe debt crisis in 2011 that required a &euro;78 billion bailout from the EU and IMF, Portugal implemented structural reforms while also investing in <Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">tourism</Link> and technology. The results have been remarkable: tourism has surged to over 30 million visitors annually (triple the population), Lisbon has become a European tech hub after attracting Web Summit, and the startup ecosystem has flourished.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Portugal&apos;s economy is diversified across tourism, automotive manufacturing (Volkswagen&apos;s Autoeuropa plant is one of the largest employers), textiles, cork (Portugal produces over 50% of the world&apos;s cork), wine, and increasingly, renewable energy — the country regularly generates 60%+ of electricity from <Link href="/renewable-energy-by-country" className="text-[#0066cc] hover:underline">renewables</Link>. The golden visa program and Non-Habitual Resident tax regime attracted wealthy immigrants and digital nomads, though some programs have been scaled back due to housing pressures.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include high government <Link href="/debt-by-country" className="text-[#0066cc] hover:underline">debt</Link> (still above 100% of GDP despite rapid reduction), an aging population with one of Europe&apos;s lowest <Link href="/fertility-rate-by-country" className="text-[#0066cc] hover:underline">fertility rates</Link>, brain drain of educated young people to higher-paying Northern European countries, and GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} — still below the EU average. Housing affordability in Lisbon and Porto has become a political flashpoint.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/portugal', label: 'Full Profile →' }, { href: '/spain-economy', label: 'Spain Economy' }, { href: '/greece-economy', label: 'Greece Economy' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/tourism-by-country', label: 'Tourism' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
