import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Thailand Economy 2026 — GDP, Tourism, Manufacturing & Key Data', description: 'Thailand economy in 2026: GDP, growth, inflation, and key indicators. ASEAN\'s 2nd largest economy and Southeast Asia\'s auto hub. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/thailand-economy' } };
export default async function ThailandEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('THA');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Thailand Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Thailand's GDP?`, acceptedAnswer: { '@type': 'Answer', text: `Thailand's GDP is approximately ${formatValue(gdp?.value, 'currency')} in ${year}, making it ASEAN's 2nd largest economy after Indonesia. Thailand is Southeast Asia's automotive hub, a top global tourism destination, and a major agricultural exporter. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/thailand" className="hover:text-gray-600 transition">Thailand</Link><span className="mx-2">/</span><span className="text-gray-600">Thailand Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Thailand Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">ASEAN&apos;s 2nd largest economy · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Thailand Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Thailand is <Link href="/asean-economy" className="text-[#0066cc] hover:underline">ASEAN&apos;s</Link> second-largest economy after <Link href="/indonesia-economy" className="text-[#0066cc] hover:underline">Indonesia</Link>, and Southeast Asia&apos;s automotive manufacturing hub — producing over 1.8 million vehicles annually for Toyota, Honda, Mitsubishi, and other Japanese automakers. The &quot;Detroit of Asia&quot; tag reflects decades of Japanese investment that built Thailand into the region&apos;s most advanced auto supply chain. Beyond automotive, the economy is driven by electronics manufacturing, agriculture (world&apos;s #1 rice exporter), and tourism (~40 million visitors annually pre-COVID).</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Thailand was the poster child of the 1997 Asian Financial Crisis, which began with the Thai baht&apos;s collapse. The crisis fundamentally reformed the economy — stronger financial regulation, flexible exchange rates, and current account surpluses became policy anchors. Growth has been slower but more stable since, averaging 3-4% annually. However, Thailand faces mounting demographic challenges — its <Link href="/fertility-rate-by-country" className="text-[#0066cc] hover:underline">fertility rate</Link> has fallen below 1.2, and the population is aging faster than most ASEAN neighbors.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Political instability — with multiple coups since 2006 — has deterred some foreign investment and contributed to the &quot;middle-income trap&quot; concern. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} has stalled relative to neighbors like Vietnam and Malaysia. The Eastern Economic Corridor (EEC) development zone and EV manufacturing push represent Thailand&apos;s strategy to upgrade its industrial base and maintain competitiveness against lower-cost competitors.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/thailand', label: 'Full Profile →' }, { href: '/indonesia-economy', label: 'Indonesia Economy' }, { href: '/asean-economy', label: 'ASEAN Economy' }, { href: '/japan-economy', label: 'Japan Economy' }, { href: '/tourism-by-country', label: 'Tourism' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
