import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Death Rate by Country 2026 — Crude Death Rates Ranked', description: 'Death rate by country: all countries ranked by crude death rate per 1,000 people. Reflects aging populations and health system quality. Source: World Bank / UN.', alternates: { canonical: 'https://statisticsoftheworld.com/death-rate-by-country' } };
export default async function DeathRateByCountryPage() {
  const data = await getIndicatorForAllCountries('SP.DYN.CDRT.IN');
  const year = data[0]?.year || '2024';
  const avg = data.length > 0 ? data.reduce((s, d) => s + (d.value || 0), 0) / data.length : 0;
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `Death Rate by Country ${year}`, description: `Crude death rate for ${data.length} countries. Source: World Bank.`, url: 'https://statisticsoftheworld.com/death-rate-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Which country has the highest death rate?', acceptedAnswer: { '@type': 'Answer', text: `${data[0]?.country} has the highest crude death rate at ${data[0]?.value ? Number(data[0].value).toFixed(1) : '—'} per 1,000. High death rates can indicate either aging populations (Eastern Europe) or poor health infrastructure (sub-Saharan Africa).` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">Death Rate by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">Death Rate by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · Global avg: {avg.toFixed(1)}/1000 · Source: World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Global Death Rate Patterns</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The crude death rate reflects both aging demographics and <Link href="/health-spending-by-country" className="text-[#0066cc] hover:underline">healthcare</Link> quality. Countries with aging populations (Eastern Europe, <Link href="/japan-economy" className="text-[#0066cc] hover:underline">Japan</Link>) and those with poor health infrastructure (sub-Saharan Africa) both show high death rates, but for very different reasons. Young, healthy populations with good healthcare — Gulf states, parts of Latin America — have the lowest rates. The gap between <Link href="/birth-rate-by-country" className="text-[#0066cc] hover:underline">birth rate</Link> and death rate determines natural <Link href="/population-by-country" className="text-[#0066cc] hover:underline">population</Link> growth.</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><caption className="sr-only">Death rate by country. Source: World Bank.</caption><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">Deaths/1000</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/death-rate`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]">{d.value ? Number(d.value).toFixed(1) : '—'}</td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/birth-rate-by-country', label: 'Birth Rate' }, { href: '/life-expectancy-by-country', label: 'Life Expectancy' }, { href: '/health-spending-by-country', label: 'Health Spending' }, { href: '/population-by-country', label: 'Population' }, { href: '/fertility-rate-by-country', label: 'Fertility Rate' }, { href: '/world-population', label: 'World Population' }, { href: '/japan-economy', label: 'Japan Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
