import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Philippines Economy 2026 — GDP, BPO, Remittances & Key Data', description: 'Philippines economy in 2026: GDP, growth, inflation, BPO sector, remittances, and key indicators. Southeast Asia\'s fastest-growing large economy. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/philippines-economy' } };
export default async function PhilippinesEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('PHL');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Philippines Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What drives the Philippines economy?`, acceptedAnswer: { '@type': 'Answer', text: `The Philippines economy is driven by services (particularly BPO/call centers — the world's 2nd largest hub), remittances from 10M+ overseas workers (10%+ of GDP), and a growing domestic consumer market of 115M people. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/philippines" className="hover:text-gray-600 transition">Philippines</Link><span className="mx-2">/</span><span className="text-gray-600">Philippines Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Philippines Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">115M people · BPO powerhouse · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Philippines Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The Philippines is <Link href="/asean-economy" className="text-[#0066cc] hover:underline">ASEAN&apos;s</Link> fastest-growing large economy, with a young, English-speaking population of 115 million that gives it unique competitive advantages in services. The country is the world&apos;s second-largest business process outsourcing (BPO) hub after <Link href="/india-economy" className="text-[#0066cc] hover:underline">India</Link>, employing over 1.5 million workers in call centers, IT services, and back-office operations for global companies. BPO contributes roughly 7% of GDP and has been growing at double-digit rates.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Remittances from over 10 million overseas Filipino workers (OFWs) — nurses, seafarers, domestic workers, engineers — amount to over 10% of GDP, providing a critical income stream that supports consumption and reduces poverty. The Philippine peso is one of the most remittance-dependent currencies in the world. The domestic economy is driven by consumption (70%+ of GDP), real estate, retail, and a growing fintech sector led by digital banks like Maya and GCash.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include inadequate infrastructure (Manila&apos;s traffic congestion is among the world&apos;s worst), high <Link href="/poverty-rate-by-country" className="text-[#0066cc] hover:underline">poverty</Link> in rural areas, vulnerability to typhoons (20+ annually), and a manufacturing sector that lags behind <Link href="/vietnam-economy" className="text-[#0066cc] hover:underline">Vietnam</Link> and <Link href="/indonesia-economy" className="text-[#0066cc] hover:underline">Indonesia</Link> in attracting FDI. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is among the lowest in ASEAN, though the young <Link href="/population-by-country" className="text-[#0066cc] hover:underline">population</Link> (median age ~26) provides a long demographic runway for growth.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/philippines', label: 'Full Profile →' }, { href: '/indonesia-economy', label: 'Indonesia Economy' }, { href: '/vietnam-economy', label: 'Vietnam Economy' }, { href: '/thailand-economy', label: 'Thailand Economy' }, { href: '/asean-economy', label: 'ASEAN Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
