import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Oman Economy 2026 — GDP, Oil, Diversification & Key Data', description: 'Oman economy in 2026: GDP, growth, oil sector, Vision 2040 diversification, and key indicators. A Gulf economy pivoting beyond oil. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/oman-economy' } };
export default async function OmanEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('OMN');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Oman Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Oman's economy based on?`, acceptedAnswer: { '@type': 'Answer', text: `Oman's economy is primarily oil-based (60%+ of government revenue) but is actively diversifying under Vision 2040 into tourism, logistics (Duqm port), manufacturing, fisheries, and mining. Oman has smaller oil reserves than its Gulf neighbors, making diversification more urgent. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/oman" className="hover:text-gray-600 transition">Oman</Link><span className="mx-2">/</span><span className="text-gray-600">Oman Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Oman Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Gulf state diversifying beyond oil · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">{[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}</div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Oman Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Oman is a Gulf state with a more modest oil endowment than its neighbors — its proven reserves are expected to last only a few more decades, making economic diversification more urgent than in <Link href="/saudi-arabia-economy" className="text-[#0066cc] hover:underline">Saudi Arabia</Link>, <Link href="/kuwait-economy" className="text-[#0066cc] hover:underline">Kuwait</Link>, or <Link href="/qatar-economy" className="text-[#0066cc] hover:underline">Qatar</Link>. Vision 2040 focuses on <Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">tourism</Link> (Oman&apos;s dramatic landscapes and cultural heritage), logistics (the mega-port at Duqm positioned as an Indian Ocean hub), manufacturing, fisheries, and mining.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Oman has pursued a distinctive foreign policy — maintaining relationships with all regional players including <Link href="/country/iran" className="text-[#0066cc] hover:underline">Iran</Link>, <Link href="/israel-economy" className="text-[#0066cc] hover:underline">Israel</Link>, and Western countries — giving it a unique diplomatic role. The economy has implemented significant fiscal reforms including VAT introduction and subsidy reduction. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is high but below other Gulf states. The &quot;Omanization&quot; policy aims to replace expatriate workers with nationals, particularly in the private sector.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/country/oman', label: 'Full Profile →' }, { href: '/saudi-arabia-economy', label: 'Saudi Arabia' }, { href: '/uae-economy', label: 'UAE Economy' }, { href: '/qatar-economy', label: 'Qatar Economy' }, { href: '/kuwait-economy', label: 'Kuwait Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}</div></div>
      </section><Footer /></main>);
}
