import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Israel Economy 2026 — GDP, Tech, Startups & Key Data', description: 'Israel economy in 2026: GDP, growth, inflation, tech sector, and key indicators. The "Startup Nation" with the highest VC investment per capita. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/israel-economy' } };
export default async function IsraelEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('ISR');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Israel Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `Why is Israel called the Startup Nation?`, acceptedAnswer: { '@type': 'Answer', text: `Israel has more startups per capita than any country in the world and the highest venture capital investment relative to GDP. The tech sector accounts for roughly 18% of GDP and 50% of exports. Companies like Wix, Mobileye, Check Point, and hundreds of cybersecurity firms originated in Israel.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/israel" className="hover:text-gray-600 transition">Israel</Link><span className="mx-2">/</span><span className="text-gray-600">Israel Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Israel Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">The &quot;Startup Nation&quot; · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Israel Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Israel is the Middle East&apos;s most innovative economy and one of the world&apos;s leading technology hubs. Known as the &quot;Startup Nation,&quot; Israel has more startups per capita than any country and the highest venture capital investment relative to GDP. The tech sector accounts for roughly 18% of GDP and 50% of exports. Cybersecurity, AI, agritech, medtech, and autonomous driving are particular strengths. Companies like Wix, Mobileye (acquired by Intel for $15B), Check Point, and Monday.com have made Israel a fixture in global tech.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Israel&apos;s innovation ecosystem is fueled by mandatory military service (the IDF&apos;s elite Unit 8200 is a renowned tech talent pipeline), world-class universities (Technion, Weizmann Institute, Hebrew University), high <Link href="/ranking/rd-spending" className="text-[#0066cc] hover:underline">R&amp;D spending</Link> (5.4% of GDP — among the world&apos;s highest), and a culture that rewards entrepreneurship and tolerates failure. Israel also has significant natural gas reserves discovered offshore since 2009, transforming it from an energy importer to a regional exporter.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is comparable to Western European levels, though Israel has higher <Link href="/gini-index-by-country" className="text-[#0066cc] hover:underline">inequality</Link> than most OECD countries. Challenges include the high cost of living (particularly housing), security expenditure (<Link href="/military-spending-by-country" className="text-[#0066cc] hover:underline">military spending</Link> is around 5% of GDP), economic disparities between the tech sector and traditional economy, and geopolitical risks that periodically disrupt economic activity.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/israel', label: 'Full Profile →' }, { href: '/saudi-arabia-economy', label: 'Saudi Arabia Economy' }, { href: '/ranking/rd-spending', label: 'R&D Spending' }, { href: '/richest-countries', label: 'Richest Countries' }, { href: '/military-spending-by-country', label: 'Military Spending' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
