import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Norway Economy 2026 — GDP, Oil, Wealth Fund & Key Data', description: 'Norway economy in 2026: GDP, growth, oil revenue, sovereign wealth fund, and key indicators. One of the world\'s wealthiest countries per capita. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/norway-economy' } };
export default async function NorwayEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('NOR');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Norway Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `How rich is Norway?`, acceptedAnswer: { '@type': 'Answer', text: `Norway's GDP per capita is approximately ${formatValue(gdpPerCapita?.value, 'currency')} — among the highest in the world. Norway also has the world's largest sovereign wealth fund ($1.7T+), worth roughly $300,000 per citizen. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/norway" className="hover:text-gray-600 transition">Norway</Link><span className="mx-2">/</span><span className="text-gray-600">Norway Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Norway Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">World&apos;s largest sovereign wealth fund · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Norway Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Norway is one of the world&apos;s wealthiest countries, with GDP per capita of {formatValue(gdpPerCapita?.value, 'currency')} and the world&apos;s largest sovereign wealth fund — the Government Pension Fund Global, worth over $1.7 trillion (roughly $300,000 per citizen). This extraordinary wealth is built on North Sea oil and gas, which Norway discovered in the late 1960s and managed with remarkable fiscal discipline. Rather than spending oil revenue immediately, Norway saves the vast majority in its sovereign wealth fund, investing globally and spending only the expected real return (~3% annually).</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Beyond oil, Norway has a diversified economy including shipping (one of the world&apos;s largest merchant fleets), aquaculture (world&apos;s largest salmon exporter), hydroelectric power (nearly 100% renewable electricity), and a growing tech sector. The Norwegian welfare state provides universal healthcare, free education through university, generous parental leave, and comprehensive social safety nets — funded by high taxes and oil wealth. <Link href="/life-expectancy-by-country" className="text-[#0066cc] hover:underline">Life expectancy</Link> at {lifeExp?.value ? Number(lifeExp.value).toFixed(1) : '83'} years is among the world&apos;s highest.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Norway is not an EU member (Norwegians rejected membership twice) but participates in the European Economic Area. The country faces long-term challenges: declining oil production as North Sea fields mature, an aging population, high cost of living (Oslo is one of the world&apos;s most expensive cities), and the need to transition away from fossil fuel dependence while fossil fuels still fund the welfare state. Norway leads globally in electric vehicle adoption — EVs are over 80% of new car sales, aided by generous tax incentives funded by oil money.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/norway', label: 'Full Profile →' }, { href: '/switzerland-economy', label: 'Switzerland Economy' }, { href: '/richest-countries', label: 'Richest Countries' }, { href: '/renewable-energy-by-country', label: 'Renewable Energy' }, { href: '/co2-emissions-by-country', label: 'CO2 Emissions' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
