import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Government Spending by Country 2026 — Expenditure as % GDP', description: 'Government spending by country: all countries ranked by government expenditure as % of GDP. From big-state Europe (50%+) to minimal-government economies. Source: World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/government-spending-by-country' } };
export default async function GovernmentSpendingByCountryPage() {
  const data = await getIndicatorForAllCountries('GC.XPN.TOTL.GD.ZS');
  const year = data[0]?.year || '2024';
  const avg = data.length > 0 ? data.reduce((s, d) => s + (d.value || 0), 0) / data.length : 0;
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `Government Spending by Country ${year}`, description: `Government expenditure as % of GDP for ${data.length} countries. Source: World Bank.`, url: 'https://statisticsoftheworld.com/government-spending-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Which country has the highest government spending?', acceptedAnswer: { '@type': 'Answer', text: `${data[0]?.country} has the highest government spending at ${formatValue(data[0]?.value, 'percent', 1)} of GDP. European welfare states typically spend 40-55% of GDP through government. The optimal level of government spending is debated — Nordic countries achieve both high spending and high competitiveness.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">Government Spending by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">Government Spending by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · % of GDP · Global avg: {avg.toFixed(1)}% · Source: World Bank</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">The Size of Government</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Government expenditure as a share of GDP measures the size of the public sector. <Link href="/france-economy" className="text-[#0066cc] hover:underline">France</Link> and Nordic countries spend 50%+ of GDP through government, funding comprehensive welfare states. At the other extreme, some developing countries spend under 15%, reflecting limited fiscal capacity. The debate over optimal government size is unresolved — high-spending <Link href="/denmark-economy" className="text-[#0066cc] hover:underline">Denmark</Link> and low-spending <Link href="/singapore-economy" className="text-[#0066cc] hover:underline">Singapore</Link> are both highly competitive. What matters most is spending quality, not just quantity.</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">% of GDP</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/government-expenditure`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]">{formatValue(d.value, 'percent', 1)}</td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/tax-revenue-by-country', label: 'Tax Revenue' }, { href: '/debt-by-country', label: 'Government Debt' }, { href: '/health-spending-by-country', label: 'Health Spending' }, { href: '/education-spending-by-country', label: 'Education' }, { href: '/military-spending-by-country', label: 'Military' }, { href: '/france-economy', label: 'France Economy' }, { href: '/denmark-economy', label: 'Denmark Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
