import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Population Density by Country 2026 — People per km² Ranked', description: 'Population density by country: all countries ranked by people per square kilometer. From microstates (20,000+/km²) to Mongolia (<2/km²). Source: World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/population-density-by-country' } };
export default async function PopulationDensityByCountryPage() {
  const data = await getIndicatorForAllCountries('EN.POP.DNST');
  const year = data[0]?.year || '2024';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `Population Density by Country ${year}`, description: `Population density for ${data.length} countries. Source: World Bank.`, url: 'https://statisticsoftheworld.com/population-density-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Which country is the most densely populated?', acceptedAnswer: { '@type': 'Answer', text: `${data[0]?.country} is the most densely populated at ${data[0]?.value ? Math.round(Number(data[0].value)) : '—'} people per km². Microstates like Monaco, Singapore, and Hong Kong have extreme density, while among large countries, Bangladesh (~1,300/km²) and South Korea (~530/km²) are the most dense.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">Population Density by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">Population Density by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · People per km² · Source: World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Global Population Density</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Population density varies enormously — from over 20,000 people per km² in Monaco to under 2 in Mongolia and Namibia. Among large countries, <Link href="/bangladesh-economy" className="text-[#0066cc] hover:underline">Bangladesh</Link> (~1,300/km²) is the most densely populated, followed by <Link href="/south-korea-economy" className="text-[#0066cc] hover:underline">South Korea</Link> (~530/km²) and the <Link href="/netherlands-economy" className="text-[#0066cc] hover:underline">Netherlands</Link> (~520/km²). Dense populations create both challenges (congestion, housing costs) and advantages (agglomeration economies, efficient service delivery).</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><caption className="sr-only">Population density by country. Source: World Bank.</caption><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">Per km²</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/population-density`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]">{d.value ? Math.round(Number(d.value)).toLocaleString() : '—'}</td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/population-by-country', label: 'Population' }, { href: '/most-populous-countries', label: 'Most Populous' }, { href: '/urban-population-by-country', label: 'Urbanization' }, { href: '/bangladesh-economy', label: 'Bangladesh Economy' }, { href: '/netherlands-economy', label: 'Netherlands Economy' }, { href: '/singapore-economy', label: 'Singapore Economy' }, { href: '/world-population', label: 'World Population' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
