import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Electricity Access by Country 2026 — Electrification Rates', description: 'Electricity access by country: all countries ranked by % of population with access to electricity. From 100% in developed nations to under 10% in parts of Africa. Source: World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/electricity-access-by-country' } };
export default async function ElectricityAccessByCountryPage() {
  const data = await getIndicatorForAllCountries('EG.ELC.ACCS.ZS');
  const year = data[0]?.year || '2024';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `Electricity Access by Country ${year}`, description: `Electrification rate for ${data.length} countries. Source: World Bank.`, url: 'https://statisticsoftheworld.com/electricity-access-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'How many people lack electricity?', acceptedAnswer: { '@type': 'Answer', text: 'Nearly 700 million people still lack access to electricity, concentrated in sub-Saharan Africa and South Asia. Countries like Chad, South Sudan, and Central African Republic have electrification rates below 15%. Off-grid solar is increasingly providing first-time access.' } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">Electricity Access by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">Electricity Access by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · % with electricity access · Source: World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Global Electrification</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Nearly 700 million people still lack access to electricity — a basic requirement for economic development, <Link href="/education-spending-by-country" className="text-[#0066cc] hover:underline">education</Link>, <Link href="/health-spending-by-country" className="text-[#0066cc] hover:underline">healthcare</Link>, and quality of life. Sub-Saharan Africa accounts for the majority of the electricity access gap. Off-grid solar, mini-grids, and mobile-pay-as-you-go models are increasingly providing first-time access in rural areas. Electricity access correlates strongly with <Link href="/gdp-per-capita-by-country" className="text-[#0066cc] hover:underline">GDP per capita</Link> and <Link href="/internet-users-by-country" className="text-[#0066cc] hover:underline">internet access</Link>.</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">Access %</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/electricity-access`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]"><span className={(d.value || 0) < 50 ? 'text-red-600' : 'text-green-600'}>{formatValue(d.value, 'percent', 0)}</span></td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/renewable-energy-by-country', label: 'Renewable Energy' }, { href: '/co2-emissions-by-country', label: 'CO2 Emissions' }, { href: '/gdp-per-capita-by-country', label: 'GDP per Capita' }, { href: '/poorest-countries', label: 'Poorest Countries' }, { href: '/internet-users-by-country', label: 'Internet Users' }, { href: '/ethiopia-economy', label: 'Ethiopia Economy' }, { href: '/kenya-economy', label: 'Kenya Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
