import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'External Debt by Country 2026 — Foreign Debt Rankings', description: 'External debt by country: all countries ranked by external debt as % of GNI. Which countries owe the most to foreign creditors? Source: World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/external-debt-by-country' } };
export default async function ExternalDebtByCountryPage() {
  const data = await getIndicatorForAllCountries('DT.DOD.DECT.GN.ZS');
  const year = data[0]?.year || '2024';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `External Debt by Country ${year}`, description: `External debt as % of GNI for ${data.length} countries. Source: World Bank.`, url: 'https://statisticsoftheworld.com/external-debt-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'What is external debt?', acceptedAnswer: { '@type': 'Answer', text: 'External debt is money owed by a country to foreign creditors — governments, banks, and international institutions. It differs from total government debt because it specifically measures foreign obligations. High external debt creates vulnerability to currency crises and capital flight, as repayments must be made in foreign currency.' } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">External Debt by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">External Debt by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · % of GNI · Source: World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Global External Debt</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">External debt — money owed to foreign creditors — creates vulnerability to currency crises and capital flight because repayments must be made in foreign currency. Countries with high external debt relative to GNI face greater risks during global financial stress. The 1997 Asian Financial Crisis, 2001 Argentine default, and <Link href="/sri-lanka-economy" className="text-[#0066cc] hover:underline">2022 Sri Lanka collapse</Link> were all triggered by external debt unsustainability. External debt data is primarily available for developing countries; advanced economies typically borrow domestically.</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><caption className="sr-only">External debt by country. Source: World Bank.</caption><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">% of GNI</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/external-debt`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]"><span className={(d.value || 0) > 100 ? 'text-red-600' : (d.value || 0) > 50 ? 'text-amber-600' : 'text-green-600'}>{formatValue(d.value, 'percent', 1)}</span></td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/debt-by-country', label: 'Government Debt' }, { href: '/gdp-by-country', label: 'GDP by Country' }, { href: '/inflation-by-country', label: 'Inflation' }, { href: '/sri-lanka-economy', label: 'Sri Lanka Economy' }, { href: '/argentina-economy', label: 'Argentina Economy' }, { href: '/pakistan-economy', label: 'Pakistan Economy' }, { href: '/poorest-countries', label: 'Poorest Countries' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
