import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Denmark Economy 2026 — GDP, Wind Energy, Pharma & Key Data', description: 'Denmark economy in 2026: GDP, growth, Novo Nordisk, wind energy, and key indicators. One of the world\'s wealthiest and happiest countries. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/denmark-economy' } };
export default async function DenmarkEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('DNK');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Denmark Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `Why is Denmark's economy so strong?`, acceptedAnswer: { '@type': 'Answer', text: `Denmark combines a flexible labor market ("flexicurity" model), world-class companies (Novo Nordisk is Europe's most valuable company, Maersk dominates container shipping, Vestas leads wind turbines), high education levels, low corruption, and a comprehensive welfare state. GDP per capita exceeds ${formatValue(gdpPerCapita?.value, 'currency')}. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/denmark" className="hover:text-gray-600 transition">Denmark</Link><span className="mx-2">/</span><span className="text-gray-600">Denmark Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Denmark Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Home of Novo Nordisk &amp; flexicurity · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Denmark Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Denmark is a small Nordic economy of 5.9 million people that punches extraordinarily above its weight. It is home to Novo Nordisk — maker of Ozempic and Wegovy, now Europe&apos;s most valuable company — which alone has reshaped Denmark&apos;s economic statistics, contributing an outsized share of GDP growth, exports, and tax revenue. Beyond pharma, Denmark hosts Maersk (world&apos;s second-largest container shipping company), Vestas (global wind turbine leader), Carlsberg, LEGO, and Ørsted (world&apos;s largest offshore wind developer).</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Denmark&apos;s &quot;flexicurity&quot; labor model is studied worldwide: it combines easy hiring and firing (flexibility for employers), generous <Link href="/unemployment-by-country" className="text-[#0066cc] hover:underline">unemployment</Link> benefits (security for workers), and active labor market policies (retraining programs). The result is low structural unemployment and high labor mobility. Denmark consistently ranks #1 or #2 globally in <Link href="/corruption-by-country" className="text-[#0066cc] hover:underline">low corruption</Link>, happiness indices, and social trust.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is among the world&apos;s highest. Denmark is a global leader in <Link href="/renewable-energy-by-country" className="text-[#0066cc] hover:underline">renewable energy</Link> — wind power generates over 50% of electricity, and the country aims for climate neutrality by 2050. Denmark is an EU member but retains its own currency (krone, pegged to the euro). Challenges include high taxes (the world&apos;s highest as a share of GDP), housing costs in Copenhagen, and dependence on Novo Nordisk for GDP growth.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/denmark', label: 'Full Profile →' }, { href: '/norway-economy', label: 'Norway Economy' }, { href: '/netherlands-economy', label: 'Netherlands Economy' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/richest-countries', label: 'Richest Countries' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
