import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Cambodia Economy 2026 — GDP, Garments, Tourism & Key Data', description: 'Cambodia economy in 2026: GDP, growth, garment exports, tourism, and key indicators. One of Southeast Asia\'s fastest-growing economies. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/cambodia-economy' } };
export default async function CambodiaEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('KHM');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Cambodia Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `How fast is Cambodia growing?`, acceptedAnswer: { '@type': 'Answer', text: `Cambodia has averaged 7%+ GDP growth for over two decades — one of the fastest sustained growth rates in the world. The economy is driven by garment/footwear exports (70% of merchandise exports), tourism (Angkor Wat), construction, and agriculture. Cambodia aims to reach upper-middle-income status by 2030. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/cambodia" className="hover:text-gray-600 transition">Cambodia</Link><span className="mx-2">/</span><span className="text-gray-600">Cambodia Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Cambodia Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Southeast Asia&apos;s growth star · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">{[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}</div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Cambodia Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Cambodia has achieved one of the world&apos;s most sustained growth performances — averaging over 7% annually for more than two decades since emerging from the Khmer Rouge era. This growth has halved the <Link href="/poverty-rate-by-country" className="text-[#0066cc] hover:underline">poverty rate</Link> and transformed Cambodia from one of Asia&apos;s poorest nations into a lower-middle-income country. The economy rests on four pillars: garment and footwear exports (70% of merchandise exports, primarily to the US and EU), <Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">tourism</Link> (Angkor Wat is Southeast Asia&apos;s most visited archaeological site), construction (Chinese-financed projects), and agriculture (rice is the staple crop and key export).</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Cambodia is highly dollarized — over 80% of deposits and loans are in US dollars, which provides price stability but limits monetary policy flexibility. <Link href="/china-economy" className="text-[#0066cc] hover:underline">Chinese</Link> investment has been transformative, particularly in infrastructure, real estate (Sihanoukville has been rebuilt by Chinese developers), and special economic zones. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is rising but remains low within <Link href="/asean-economy" className="text-[#0066cc] hover:underline">ASEAN</Link>. Challenges include governance concerns, environmental degradation, and dependence on garment preferential trade access.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/country/cambodia', label: 'Full Profile →' }, { href: '/vietnam-economy', label: 'Vietnam Economy' }, { href: '/thailand-economy', label: 'Thailand Economy' }, { href: '/asean-economy', label: 'ASEAN Economy' }, { href: '/gdp-growth-by-country', label: 'GDP Growth' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}</div></div>
      </section><Footer /></main>);
}
