import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Czech Republic Economy 2026 — GDP, Manufacturing, Auto & Key Data', description: 'Czech Republic economy in 2026: GDP, growth, inflation, and key indicators. Central Europe\'s most industrialized economy with the lowest inequality in the EU. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/czech-republic-economy' } };
export default async function CzechRepublicEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('CZE');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Czech Republic Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is the Czech Republic's GDP?`, acceptedAnswer: { '@type': 'Answer', text: `The Czech Republic's GDP is approximately ${formatValue(gdp?.value, 'currency')} in ${year}. It has Central Europe's most industrialized economy, with automotive manufacturing (Škoda/Volkswagen) at its core. The country has the EU's lowest unemployment and lowest Gini coefficient. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/czech-republic" className="hover:text-gray-600 transition">Czech Republic</Link><span className="mx-2">/</span><span className="text-gray-600">Czech Republic Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Czech Republic Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Central Europe&apos;s industrial powerhouse · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Czech Republic Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The Czech Republic is Central Europe&apos;s most industrialized economy and one of the <Link href="/eu-economy" className="text-[#0066cc] hover:underline">EU&apos;s</Link> post-2004 success stories. Manufacturing accounts for roughly 25% of GDP — among the highest shares in Europe — with automotive production at the core. Škoda Auto (owned by Volkswagen), Hyundai, and Toyota all have major factories, making the Czech Republic one of Europe&apos;s largest car producers per capita. The country also excels in machinery, electronics, and glass manufacturing, leveraging a strong engineering tradition dating to the Austro-Hungarian era.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The Czech economy stands out for having the EU&apos;s lowest <Link href="/unemployment-by-country" className="text-[#0066cc] hover:underline">unemployment rate</Link> (consistently under 3%) and lowest <Link href="/gini-index-by-country" className="text-[#0066cc] hover:underline">Gini coefficient</Link> — meaning it is the most equal society in the European Union. This reflects the Communist-era legacy of low inequality combined with a successful transition to market economics that didn&apos;t create the extreme wealth gaps seen in Russia. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} has been converging toward Western European levels.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The country maintains its own currency (Czech koruna) and has not adopted the euro, giving it monetary policy flexibility. Challenges include heavy dependence on <Link href="/germany-economy" className="text-[#0066cc] hover:underline">German</Link> automotive demand (Germany is the top export destination), the EV transition threatening its ICE-focused auto industry, an aging population, and labor shortages that constrain growth. Prague has become a major European tech hub and tourism destination.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/czech-republic', label: 'Full Profile →' }, { href: '/poland-economy', label: 'Poland Economy' }, { href: '/germany-economy', label: 'Germany Economy' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/gini-index-by-country', label: 'Inequality' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
