import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Pakistan Economy 2026 — GDP, IMF, Inflation & Key Data', description: 'Pakistan economy in 2026: GDP, growth, inflation, IMF programs, and key indicators. The world\'s 5th most populous country with 230M+ people. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/pakistan-economy' } };
export default async function PakistanEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('PAK');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Pakistan Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Pakistan's GDP?`, acceptedAnswer: { '@type': 'Answer', text: `Pakistan's GDP is approximately ${formatValue(gdp?.value, 'currency')} in ${year}. Despite being the world's 5th most populous country (230M+), Pakistan's economy ranks only around 40th globally, reflecting significant development challenges. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/pakistan" className="hover:text-gray-600 transition">Pakistan</Link><span className="mx-2">/</span><span className="text-gray-600">Pakistan Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Pakistan Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">World&apos;s 5th most populous country · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Pakistan Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Pakistan is the world&apos;s fifth most populous country with over 230 million people, yet its economy ranks only around 40th globally — a gap that reflects decades of political instability, chronic fiscal deficits, low tax collection, and underinvestment in human capital. The economy is driven by agriculture (employing ~40% of workers), textiles (the world&apos;s 4th largest cotton producer), remittances from the Pakistani diaspora, and a growing but still small services sector. The China-Pakistan Economic Corridor (CPEC), part of China&apos;s Belt and Road Initiative, has brought significant infrastructure investment.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Pakistan has been in a recurring cycle of IMF bailout programs — over 20 since 1958 — reflecting a structural inability to live within its means. Tax revenue is chronically low (under 10% of GDP in some years), government spending exceeds income, the current account deficit widens during growth periods, and the rupee depreciates, triggering <Link href="/inflation-by-country" className="text-[#0066cc] hover:underline">inflation</Link>. The latest IMF program requires painful reforms: tax base broadening, energy subsidy reduction, and privatization of state enterprises.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Pakistan&apos;s demographic profile — median age of just 22 — represents an enormous opportunity if the country can invest in <Link href="/education-spending-by-country" className="text-[#0066cc] hover:underline">education</Link> and create jobs. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is among the lowest in South Asia. The IT and freelancing sector is a bright spot, with Pakistan ranking among the top countries for freelance workers on global platforms. Security improvements since 2015 and a growing middle class in urban centers like Lahore, Karachi, and Islamabad provide reasons for cautious optimism.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/pakistan', label: 'Full Profile →' }, { href: '/india-economy', label: 'India Economy' }, { href: '/bangladesh-economy', label: 'Bangladesh Economy' }, { href: '/population-by-country', label: 'Population' }, { href: '/inflation-by-country', label: 'Inflation' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
