import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Myanmar Economy 2026 — GDP, Conflict, Sanctions & Key Data', description: 'Myanmar economy in 2026: GDP, impact of military coup, sanctions, and key indicators. Once Southeast Asia\'s fastest reformer, now in economic crisis. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/myanmar-economy' } };
export default async function MyanmarEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('MMR');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Myanmar Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/myanmar" className="hover:text-gray-600 transition">Myanmar</Link><span className="mx-2">/</span><span className="text-gray-600">Myanmar Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Myanmar Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Economy in crisis since 2021 coup · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">{[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}</div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Myanmar Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Myanmar&apos;s economy has been in severe crisis since the military coup of February 2021. What was once <Link href="/asean-economy" className="text-[#0066cc] hover:underline">ASEAN&apos;s</Link> fastest-reforming economy — attracting garment factories, telecom investment, and tourism — has seen GDP contract sharply, foreign investment flee, the banking system collapse, and Western sanctions imposed. Civil resistance, including a widespread civil disobedience movement and armed opposition, has further disrupted economic activity.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Myanmar has a <Link href="/population-by-country" className="text-[#0066cc] hover:underline">population</Link> of 55 million and significant natural resources including natural gas, jade, rubies, teak, and agricultural land. Before the coup, the economy was growing at 6-7% annually, garment exports were booming, and Yangon was attracting international attention. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is among the lowest in Asia. The humanitarian and economic outlook depends entirely on political resolution.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/country/myanmar', label: 'Full Profile →' }, { href: '/thailand-economy', label: 'Thailand Economy' }, { href: '/vietnam-economy', label: 'Vietnam Economy' }, { href: '/asean-economy', label: 'ASEAN Economy' }, { href: '/poorest-countries', label: 'Poorest Countries' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}</div></div>
      </section><Footer /></main>);
}
