import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Ireland Economy 2026 — GDP, Tech, Multinationals & Key Data', description: 'Ireland economy in 2026: GDP, growth, inflation, and key indicators. Europe\'s tech hub and home to Apple, Google, and pharma HQs. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/ireland-economy' } };
export default async function IrelandEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('IRL');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Ireland Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `Why is Ireland's GDP so high?`, acceptedAnswer: { '@type': 'Answer', text: `Ireland's GDP is inflated by multinational corporations (Apple, Google, Meta, Pfizer, etc.) routing intellectual property and profits through Ireland for tax purposes. Ireland's modified GNI* — which strips out these distortions — is roughly 40% lower than GDP, better reflecting the actual domestic economy.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/ireland" className="hover:text-gray-600 transition">Ireland</Link><span className="mx-2">/</span><span className="text-gray-600">Ireland Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Ireland Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Europe&apos;s tech and pharma hub · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Ireland Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Ireland&apos;s economic transformation from one of Europe&apos;s poorest countries to one of its wealthiest has been one of the most dramatic in postwar history. The &quot;Celtic Tiger&quot; boom of the 1990s-2000s was fueled by EU structural funds, low corporate tax rates (12.5%), English-speaking access to European markets, and massive inflows of US multinational investment. Today, Ireland hosts the European headquarters of Apple, Google, Meta, Microsoft, Pfizer, and dozens of other global corporations, making it a genuine tech and pharma powerhouse.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Ireland&apos;s GDP figures are notoriously distorted by multinational profit routing. When Apple moved its intellectual property to Ireland in 2015, Irish GDP jumped 26% overnight in what economists called &quot;Leprechaun Economics.&quot; Modified GNI* — a metric developed specifically for Ireland — strips out these distortions and shows the actual domestic economy is roughly 40% smaller than headline GDP suggests. Even so, Ireland&apos;s genuine economic performance has been strong, with low unemployment, high wages, and a thriving indigenous tech sector.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include a severe housing crisis (Dublin rents rival London), high cost of living, overreliance on multinational tax revenue (which could shift under OECD global minimum tax rules), and healthcare system strain. Ireland&apos;s corporation tax advantage is being eroded by the 15% global minimum tax, though the country has offset this by positioning itself as offering more than just low taxes — access to talent, EU market access, and established clusters matter more.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/ireland', label: 'Full Profile →' }, { href: '/uk-economy', label: 'UK Economy' }, { href: '/netherlands-economy', label: 'Netherlands Economy' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/richest-countries', label: 'Richest Countries' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
