import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Greece Economy 2026 — GDP, Debt Crisis Recovery, Tourism & Key Data', description: 'Greece economy in 2026: GDP, growth, debt, tourism, shipping, and key indicators. Recovery from Europe\'s worst debt crisis. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/greece-economy' } };
export default async function GreeceEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('GRC');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Greece Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `Has Greece recovered from its debt crisis?`, acceptedAnswer: { '@type': 'Answer', text: `Greece has made significant progress. GDP growth has returned, unemployment has fallen from 28% peak to around ${formatValue(unemployment?.value, 'percent', 1)}, and Greece regained investment-grade credit ratings in 2023. However, debt remains above 160% of GDP — the highest in the eurozone — and GDP has not fully recovered to pre-crisis levels. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/greece" className="hover:text-gray-600 transition">Greece</Link><span className="mx-2">/</span><span className="text-gray-600">Greece Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Greece Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Recovering from Europe&apos;s worst debt crisis · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Greece Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Greece experienced the worst sovereign debt crisis in modern European history. From 2010 to 2018, Greece received three bailout programs totaling &euro;289 billion — the largest financial rescue in history. GDP contracted by 25% (comparable to the US Great Depression), <Link href="/unemployment-by-country" className="text-[#0066cc] hover:underline">unemployment</Link> peaked at 28% (youth unemployment exceeded 60%), and government <Link href="/debt-by-country" className="text-[#0066cc] hover:underline">debt</Link> soared above 200% of GDP. The crisis was triggered by revelations that Greece had falsified its fiscal accounts to meet eurozone entry criteria.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Recovery has been gradual but real. Greece regained investment-grade credit ratings in 2023 for the first time since the crisis. <Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">Tourism</Link> has surged to record levels — over 30 million visitors annually for a country of 10 million — and the shipping industry (Greece controls roughly 20% of the world&apos;s shipping fleet) remains a crucial economic driver. Real estate, renewable energy, and digital services are emerging growth sectors.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Debt at {formatValue(debt?.value, 'percent', 1)} of GDP remains the eurozone&apos;s highest, though it&apos;s been restructured with long maturities and low interest rates making it more sustainable than the headline number suggests. Challenges include an aging and shrinking population (one of Europe&apos;s lowest <Link href="/fertility-rate-by-country" className="text-[#0066cc] hover:underline">fertility rates</Link>), brain drain of educated young Greeks, and a large informal economy. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} has not fully recovered to pre-crisis levels.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/greece', label: 'Full Profile →' }, { href: '/portugal-economy', label: 'Portugal Economy' }, { href: '/italy-economy', label: 'Italy Economy' }, { href: '/spain-economy', label: 'Spain Economy' }, { href: '/debt-by-country', label: 'Debt by Country' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
