import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Qatar Economy 2026 — GDP, LNG, World Cup Legacy & Key Data', description: 'Qatar economy in 2026: GDP, LNG exports, per capita wealth, World Cup legacy, and key indicators. One of the world\'s richest countries per capita. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/qatar-economy' } };
export default async function QatarEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('QAT');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Qatar Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `Why is Qatar so rich?`, acceptedAnswer: { '@type': 'Answer', text: `Qatar has the world's 3rd largest natural gas reserves and is the largest LNG (liquefied natural gas) exporter globally. This enormous resource wealth divided by a tiny population (~3 million, mostly expatriate workers) gives Qatar one of the highest GDP per capita figures in the world at ${formatValue(gdpPerCapita?.value, 'currency')}. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/qatar" className="hover:text-gray-600 transition">Qatar</Link><span className="mx-2">/</span><span className="text-gray-600">Qatar Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Qatar Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">World&apos;s largest LNG exporter · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Qatar Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Qatar is one of the world&apos;s wealthiest countries per capita, powered by the North Field — the world&apos;s third-largest natural gas reserve (shared with <Link href="/country/iran" className="text-[#0066cc] hover:underline">Iran</Link>). Qatar is the world&apos;s largest exporter of liquefied natural gas (LNG) through QatarEnergy, and European demand for LNG surged after the continent cut Russian pipeline gas imports in 2022. The massive North Field expansion will increase Qatar&apos;s LNG production by over 60% by 2027, further cementing its dominance.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} ranks among the world&apos;s highest — a reflection of enormous resource wealth divided by a small population of roughly 3 million, of which over 85% are expatriate workers. Qatar hosted the 2022 FIFA World Cup, investing over $200 billion in stadiums, metro, highways, and a new city (Lusail). The Qatar Investment Authority (QIA) manages $450B+ in assets globally, including stakes in Volkswagen, Barclays, and London&apos;s Harrods.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Diversification beyond gas is a strategic priority under Qatar National Vision 2030. Education City hosts branches of elite US universities (Georgetown, Northwestern, Cornell). Al Jazeera — the globally influential media network — is Qatar-funded. <Link href="/co2-emissions-by-country" className="text-[#0066cc] hover:underline">CO2 emissions per capita</Link> are among the world&apos;s highest due to energy-intensive desalination and cooling. Qatar weathered a 2017-2021 diplomatic blockade by <Link href="/saudi-arabia-economy" className="text-[#0066cc] hover:underline">Saudi Arabia</Link> and <Link href="/uae-economy" className="text-[#0066cc] hover:underline">UAE</Link> without major economic damage, demonstrating the power of gas wealth as a buffer.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/qatar', label: 'Full Profile →' }, { href: '/saudi-arabia-economy', label: 'Saudi Arabia' }, { href: '/uae-economy', label: 'UAE Economy' }, { href: '/richest-countries', label: 'Richest Countries' }, { href: '/co2-emissions-by-country', label: 'CO2 Emissions' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
