import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Kazakhstan Economy 2026 — GDP, Oil, Minerals & Key Data', description: 'Kazakhstan economy in 2026: GDP, growth, oil exports, minerals, and key indicators. Central Asia\'s largest economy and major oil producer. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/kazakhstan-economy' } };
export default async function KazakhstanEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('KAZ');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Kazakhstan Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Kazakhstan's economy based on?`, acceptedAnswer: { '@type': 'Answer', text: `Kazakhstan's economy is dominated by oil (the Kashagan and Tengiz fields are among the world's largest), minerals (the world's largest uranium producer, plus significant copper, zinc, and rare earths), and agriculture. Oil accounts for roughly 50% of government revenue and 60% of exports. Kazakhstan is Central Asia's largest and wealthiest economy. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/kazakhstan" className="hover:text-gray-600 transition">Kazakhstan</Link><span className="mx-2">/</span><span className="text-gray-600">Kazakhstan Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Kazakhstan Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Central Asia&apos;s largest economy · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Kazakhstan Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Kazakhstan is Central Asia&apos;s largest and wealthiest economy — accounting for over 60% of the region&apos;s GDP. The economy is built on massive natural resource wealth: the Kashagan and Tengiz oil fields in the Caspian Sea are among the world&apos;s largest, and Kazakhstan is the world&apos;s largest uranium producer (over 40% of global output). The country also has significant reserves of copper, zinc, chromium, and rare earth minerals increasingly critical for the green energy transition.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Since independence in 1991, Kazakhstan has positioned itself as Central Asia&apos;s most reform-oriented economy, attracting significant Western oil investment (Chevron, ExxonMobil, Shell) and maintaining relatively stable macroeconomic policy. The National Fund of the Republic of Kazakhstan (sovereign wealth fund) saves oil revenue for future generations, following the <Link href="/norway-economy" className="text-[#0066cc] hover:underline">Norwegian</Link> model. The new capital Astana (formerly Nur-Sultan) was built from scratch as a symbol of the country&apos;s ambitions.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Geopolitically, Kazakhstan navigates between <Link href="/russia-economy" className="text-[#0066cc] hover:underline">Russia</Link> (its northern neighbor and former colonial power) and <Link href="/china-economy" className="text-[#0066cc] hover:underline">China</Link> (its eastern neighbor and Belt and Road partner). The country has benefited from sanctions-driven trade rerouting and Russian emigration since 2022. Challenges include oil dependence, <Link href="/corruption-by-country" className="text-[#0066cc] hover:underline">corruption</Link>, limited political freedom, and the need to diversify toward manufacturing and services. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is the highest in Central Asia.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/kazakhstan', label: 'Full Profile →' }, { href: '/russia-economy', label: 'Russia Economy' }, { href: '/saudi-arabia-economy', label: 'Saudi Arabia' }, { href: '/co2-emissions-by-country', label: 'CO2 Emissions' }, { href: '/corruption-by-country', label: 'Corruption' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
