import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Peru Economy 2026 — GDP, Mining, Growth & Key Data', description: 'Peru economy in 2026: GDP, growth, mining sector, inflation, and key indicators. One of Latin America\'s fastest-growing economies. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/peru-economy' } };
export default async function PeruEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('PER');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Peru Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What is Peru's GDP?`, acceptedAnswer: { '@type': 'Answer', text: `Peru's GDP is approximately ${formatValue(gdp?.value, 'currency')} in ${year}. Peru is the world's 2nd largest copper producer and 6th largest gold producer, with mining driving exports and government revenue. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/peru" className="hover:text-gray-600 transition">Peru</Link><span className="mx-2">/</span><span className="text-gray-600">Peru Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Peru Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Latin America&apos;s mining powerhouse · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Peru Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Peru was one of Latin America&apos;s fastest-growing economies for two decades, averaging 5%+ annual GDP growth from 2000 to 2019. The economy is anchored by mining — Peru is the world&apos;s second-largest copper producer (after <Link href="/chile-economy" className="text-[#0066cc] hover:underline">Chile</Link>), sixth-largest gold producer, and a significant producer of zinc, silver, and tin. Mining generates roughly 60% of export revenue and 15% of government income. The copper boom has been a major driver of poverty reduction and infrastructure development.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Peru has maintained remarkably sound macroeconomic management for a Latin American country: low <Link href="/inflation-by-country" className="text-[#0066cc] hover:underline">inflation</Link> (the central bank has strong credibility), moderate government <Link href="/debt-by-country" className="text-[#0066cc] hover:underline">debt</Link>, healthy international reserves, and a floating exchange rate. This prudence has earned Peru investment-grade credit ratings and attracted significant mining FDI. The Pacific Alliance trade bloc (with <Link href="/mexico-economy" className="text-[#0066cc] hover:underline">Mexico</Link>, <Link href="/colombia-economy" className="text-[#0066cc] hover:underline">Colombia</Link>, and <Link href="/chile-economy" className="text-[#0066cc] hover:underline">Chile</Link>) has deepened regional trade integration.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include persistent <Link href="/gini-index-by-country" className="text-[#0066cc] hover:underline">inequality</Link> between Lima and rural Andean/Amazonian regions, a large informal economy (employing ~70% of workers), political instability (frequent presidential crises), and mining community conflicts over environmental and water issues. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} places Peru as a lower-middle-income country with significant growth potential if political stability improves.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/peru', label: 'Full Profile →' }, { href: '/chile-economy', label: 'Chile Economy' }, { href: '/colombia-economy', label: 'Colombia Economy' }, { href: '/brazil-economy', label: 'Brazil Economy' }, { href: '/gdp-growth-by-country', label: 'GDP Growth' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
