import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Morocco Economy 2026 — GDP, Manufacturing, Phosphates & Key Data', description: 'Morocco economy in 2026: GDP, growth, automotive manufacturing, phosphates, tourism, and key indicators. North Africa\'s most diversified economy. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/morocco-economy' } };
export default async function MoroccoEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('MAR');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Morocco Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What drives Morocco's economy?`, acceptedAnswer: { '@type': 'Answer', text: `Morocco's economy is driven by automotive manufacturing (Renault and Stellantis plants make it Africa's largest car producer), phosphates (75% of world reserves — critical for fertilizers), tourism (15M+ visitors), agriculture, and a growing aerospace/electronics sector. Morocco will co-host the 2030 FIFA World Cup. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/morocco" className="hover:text-gray-600 transition">Morocco</Link><span className="mx-2">/</span><span className="text-gray-600">Morocco Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Morocco Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">North Africa&apos;s most diversified economy · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Morocco Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Morocco is North Africa&apos;s most diversified and politically stable economy. Unlike oil-dependent neighbors, Morocco has built a manufacturing-oriented economy anchored by automotive production — Renault and Stellantis plants have made Morocco Africa&apos;s largest car producer, exporting primarily to <Link href="/eu-economy" className="text-[#0066cc] hover:underline">Europe</Link>. The country controls approximately 75% of the world&apos;s phosphate reserves through state-owned OCP Group, making it indispensable to global agriculture (phosphate is essential for fertilizers).</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]"><Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">Tourism</Link> is a major pillar — Marrakech, Fez, and Casablanca attract over 15 million visitors annually. Morocco has invested massively in infrastructure: Africa&apos;s first high-speed rail line (TGV connecting Tangier to Casablanca), the Tanger Med port (the Mediterranean&apos;s largest), and a growing <Link href="/renewable-energy-by-country" className="text-[#0066cc] hover:underline">renewable energy</Link> sector including the Noor-Ouarzazate solar complex — one of the world&apos;s largest. Morocco will co-host the 2030 FIFA World Cup with Spain and Portugal.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include high youth <Link href="/unemployment-by-country" className="text-[#0066cc] hover:underline">unemployment</Link> (~25%), significant rural-urban inequality, water scarcity (Morocco is one of the world&apos;s most water-stressed countries), and <Link href="/education-spending-by-country" className="text-[#0066cc] hover:underline">education</Link> quality gaps. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} reflects lower-middle-income status with significant room for convergence toward European living standards.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/morocco', label: 'Full Profile →' }, { href: '/egypt-economy', label: 'Egypt Economy' }, { href: '/nigeria-economy', label: 'Nigeria Economy' }, { href: '/spain-economy', label: 'Spain Economy' }, { href: '/tourism-by-country', label: 'Tourism' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
