import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Sri Lanka Economy 2026 — GDP, Debt Crisis, Recovery & Key Data', description: 'Sri Lanka economy in 2026: GDP, growth, debt crisis recovery, tourism, and key indicators. Rebuilding after the 2022 economic collapse. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/sri-lanka-economy' } };
export default async function SriLankaEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('LKA');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Sri Lanka Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What happened to Sri Lanka's economy?`, acceptedAnswer: { '@type': 'Answer', text: `Sri Lanka suffered a catastrophic economic collapse in 2022 — the country defaulted on foreign debt for the first time, ran out of foreign exchange reserves, experienced 70%+ inflation, and faced severe shortages of fuel, food, and medicine. Protests forced the president to resign. An IMF bailout and restructuring are supporting gradual recovery. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/sri-lanka" className="hover:text-gray-600 transition">Sri Lanka</Link><span className="mx-2">/</span><span className="text-gray-600">Sri Lanka Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Sri Lanka Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Recovering from 2022 crisis · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">{[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}</div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Sri Lanka Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Sri Lanka experienced one of the most severe economic collapses in recent history in 2022. A toxic combination of excessive government borrowing, ill-advised tax cuts, a disastrous ban on chemical fertilizers, COVID-19 tourism collapse, and depletion of foreign reserves led to sovereign default, 70%+ <Link href="/inflation-by-country" className="text-[#0066cc] hover:underline">inflation</Link>, and acute shortages of fuel, food, and medicine. Mass protests forced President Rajapaksa to flee the country.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Sri Lanka is now in an IMF-supported recovery program involving debt restructuring, tax increases, subsidy reform, and central bank independence. The economy has stabilized — inflation has fallen dramatically, reserves are rebuilding, and <Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">tourism</Link> is recovering. Before the crisis, Sri Lanka had South Asia&apos;s highest <Link href="/life-expectancy-by-country" className="text-[#0066cc] hover:underline">life expectancy</Link> and human development indicators — achievements that the crisis put at risk. The garment, tea, and IT services sectors continue to provide export earnings.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/country/sri-lanka', label: 'Full Profile →' }, { href: '/india-economy', label: 'India Economy' }, { href: '/bangladesh-economy', label: 'Bangladesh Economy' }, { href: '/debt-by-country', label: 'Debt by Country' }, { href: '/inflation-by-country', label: 'Inflation' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}</div></div>
      </section><Footer /></main>);
}
