import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Belgium Economy 2026 — GDP, EU Capital, Trade & Key Data', description: 'Belgium economy in 2026: GDP, growth, trade, EU/NATO headquarters, and key indicators. Europe\'s most trade-open major economy. Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/belgium-economy' } };
export default async function BelgiumEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('BEL');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Belgium Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `Why is Belgium economically important?`, acceptedAnswer: { '@type': 'Answer', text: `Belgium hosts the EU's main institutions (European Commission, Council, Parliament) and NATO headquarters in Brussels, making it the de facto capital of Europe. The port of Antwerp is Europe's 2nd largest. Belgium has one of the world's highest trade-to-GDP ratios and is a major chemicals, pharmaceuticals, and diamond trading hub. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/belgium" className="hover:text-gray-600 transition">Belgium</Link><span className="mx-2">/</span><span className="text-gray-600">Belgium Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Belgium Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">Capital of Europe · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Belgium Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Belgium is the de facto capital of Europe, hosting the European Commission, European Council, European Parliament, and NATO headquarters in Brussels. This institutional presence makes Belgium a center of international diplomacy, lobbying, and associated services. The economy is one of Europe&apos;s most <Link href="/trade-by-country" className="text-[#0066cc] hover:underline">trade-open</Link> — trade exceeds 170% of GDP — reflecting Belgium&apos;s position as a logistics hub between <Link href="/france-economy" className="text-[#0066cc] hover:underline">France</Link>, <Link href="/germany-economy" className="text-[#0066cc] hover:underline">Germany</Link>, and the <Link href="/netherlands-economy" className="text-[#0066cc] hover:underline">Netherlands</Link>.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The Port of Antwerp is Europe&apos;s second largest (after Rotterdam), handling over 230 million tons of cargo annually. Antwerp is also the world&apos;s diamond capital — roughly 80% of the world&apos;s rough diamonds pass through the city. Belgium has a strong chemicals and pharmaceutical sector (UCB, Janssen/J&amp;J&apos;s European base), advanced materials (Solvay, Umicore), and a thriving chocolate industry (Godiva, Neuhaus, Côte d&apos;Or). AB InBev, the world&apos;s largest brewery, is headquartered in Leuven.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Belgium&apos;s complex federal structure — divided between Dutch-speaking Flanders (wealthier, more conservative) and French-speaking Wallonia (more industrial, higher unemployment) — creates political complexity. Government <Link href="/debt-by-country" className="text-[#0066cc] hover:underline">debt</Link> at {formatValue(debt?.value, 'percent', 1)} of GDP is high for the eurozone. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} is above the EU average, with Flanders significantly richer than Wallonia. Belgium&apos;s high tax burden (among the world&apos;s highest) funds comprehensive social services but may reduce competitiveness.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/belgium', label: 'Full Profile →' }, { href: '/netherlands-economy', label: 'Netherlands Economy' }, { href: '/france-economy', label: 'France Economy' }, { href: '/germany-economy', label: 'Germany Economy' }, { href: '/eu-economy', label: 'EU Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
