import type { Metadata } from 'next';
import Link from 'next/link';
import { getAllIndicatorsForCountry, formatValue } from '@/lib/data';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Kenya Economy 2026 — GDP, Tech, M-Pesa & Key Data', description: 'Kenya economy in 2026: GDP, growth, M-Pesa, tech sector, and key indicators. East Africa\'s largest economy and the "Silicon Savannah." Source: IMF & World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/kenya-economy' } };
export default async function KenyaEconomyPage() {
  const indicators = await getAllIndicatorsForCountry('KEN');
  const gdp = indicators['IMF.NGDPD']; const gdpGrowth = indicators['IMF.NGDP_RPCH']; const gdpPerCapita = indicators['IMF.NGDPDPC']; const inflation = indicators['IMF.PCPIPCH']; const unemployment = indicators['IMF.LUR']; const debt = indicators['IMF.GGXWDG_NGDP']; const pop = indicators['SP.POP.TOTL']; const lifeExp = indicators['SP.DYN.LE00.IN']; const year = gdp?.year || '2026';
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Article', headline: `Kenya Economy ${year}`, dateModified: new Date().toISOString().split('T')[0], author: { '@type': 'Organization', name: 'Statistics of the World' } }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: `What makes Kenya's economy unique?`, acceptedAnswer: { '@type': 'Answer', text: `Kenya is East Africa's economic hub and the "Silicon Savannah" — home to M-Pesa (the world's most successful mobile money platform, used by 80%+ of adults), a thriving tech startup ecosystem (Nairobi is Africa's #2 tech hub after Lagos), and diversified economy spanning agriculture (tea, flowers, coffee), tourism (safaris, beaches), and financial services. Source: IMF.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><Link href="/country/kenya" className="hover:text-gray-600 transition">Kenya</Link><span className="mx-2">/</span><span className="text-gray-600">Kenya Economy</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">The Kenya Economy in {year}</h1>
        <p className="text-[15px] text-[#64748b] mb-6">East Africa&apos;s economic hub · &quot;Silicon Savannah&quot; · Source: IMF & World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
          {[{ label: 'GDP', value: formatValue(gdp?.value, 'currency') }, { label: 'Growth', value: formatValue(gdpGrowth?.value, 'percent', 1) }, { label: 'Inflation', value: formatValue(inflation?.value, 'percent', 1) }, { label: 'Unemployment', value: formatValue(unemployment?.value, 'percent', 1) }, { label: 'GDP/Capita', value: formatValue(gdpPerCapita?.value, 'currency') }, { label: 'Population', value: formatValue(pop?.value, 'number') }, { label: 'Debt (% GDP)', value: formatValue(debt?.value, 'percent', 1) }, { label: 'Life Exp.', value: lifeExp?.value ? `${Number(lifeExp.value).toFixed(1)}y` : '—' }].map(m => (<div key={m.label} className="bg-white border border-[#d5dce6] rounded-xl p-5"><div className="text-[13px] text-[#94a3b8] mb-1">{m.label}</div><div className="text-[22px] font-bold text-[#0d1b2a]">{m.value || '—'}</div></div>))}
        </div>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Kenya Economic Overview</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Kenya is East Africa&apos;s largest economy and one of the continent&apos;s most diversified. Unlike many African economies dependent on a single commodity, Kenya&apos;s GDP draws from agriculture (tea — world&apos;s largest exporter, flowers — Europe&apos;s main supplier, coffee), <Link href="/tourism-by-country" className="text-[#0066cc] hover:underline">tourism</Link> (safari parks, Indian Ocean coast), financial services (Nairobi is East Africa&apos;s financial center), and increasingly, technology. The economy has averaged 5-6% growth over the past decade.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Kenya&apos;s tech ecosystem is Africa&apos;s most innovative. M-Pesa, launched by Safaricom in 2007, revolutionized financial inclusion by enabling mobile payments for unbanked populations — over 80% of Kenyan adults use it, and the model has been replicated across developing countries. Nairobi is dubbed the &quot;Silicon Savannah,&quot; hosting Google&apos;s Africa headquarters, hundreds of startups, and a growing venture capital scene. Kenya also leads Africa in <Link href="/renewable-energy-by-country" className="text-[#0066cc] hover:underline">renewable energy</Link> — geothermal provides over 45% of electricity, and wind (Lake Turkana Wind Power) is expanding.</p>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Challenges include rising government <Link href="/debt-by-country" className="text-[#0066cc] hover:underline">debt</Link> (exceeding 70% of GDP, with significant Chinese debt for infrastructure), high youth unemployment, <Link href="/corruption-by-country" className="text-[#0066cc] hover:underline">corruption</Link>, and <Link href="/gini-index-by-country" className="text-[#0066cc] hover:underline">inequality</Link> between Nairobi&apos;s modern economy and rural subsistence. GDP per capita at {formatValue(gdpPerCapita?.value, 'currency')} remains low. Kenya&apos;s young <Link href="/population-by-country" className="text-[#0066cc] hover:underline">population</Link> of 55 million (median age ~20) represents both the country&apos;s greatest opportunity and challenge.</p>
        </div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
          {[{ href: '/country/kenya', label: 'Full Profile →' }, { href: '/nigeria-economy', label: 'Nigeria Economy' }, { href: '/south-africa-economy', label: 'South Africa Economy' }, { href: '/ethiopia-economy', label: 'Ethiopia Economy' }, { href: '/internet-users-by-country', label: 'Internet Users' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label}</Link>))}
        </div></div>
      </section><Footer /></main>);
}
