import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Tax Revenue by Country 2026 — Government Tax Collection Ranked', description: 'Tax revenue by country: all countries ranked by government tax collection as % of GDP. From Nordic 40%+ to developing nations under 10%. Source: World Bank.', alternates: { canonical: 'https://statisticsoftheworld.com/tax-revenue-by-country' } };
export default async function TaxRevenueByCountryPage() {
  const data = await getIndicatorForAllCountries('GC.TAX.TOTL.GD.ZS');
  const year = data[0]?.year || '2024';
  const avg = data.length > 0 ? data.reduce((s, d) => s + (d.value || 0), 0) / data.length : 0;
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `Tax Revenue by Country ${year}`, description: `Tax revenue as % of GDP for ${data.length} countries. Source: World Bank.`, url: 'https://statisticsoftheworld.com/tax-revenue-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Which country collects the most tax?', acceptedAnswer: { '@type': 'Answer', text: `As % of GDP, ${data[0]?.country} collects the most at ${formatValue(data[0]?.value, 'percent', 1)}. Nordic countries collect 40-50% of GDP in taxes, reflecting comprehensive welfare states. Many developing countries collect under 15% — below the IMF threshold for funding basic services.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">Tax Revenue by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">Tax Revenue by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · % of GDP · Global avg: {avg.toFixed(1)}% · Source: World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Global Tax Collection</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">Tax revenue as a percentage of GDP measures a government&apos;s fiscal capacity. Nordic countries collect 40-50% of GDP in taxes, funding comprehensive welfare states with universal healthcare, free education, and generous social safety nets — while still ranking among the world&apos;s most competitive economies. Many developing countries collect less than 15% — below the IMF&apos;s threshold for funding basic services — reflecting large informal economies, weak tax administration, and narrow tax bases. The relationship between tax level and growth is nuanced: high-tax Nordic economies and low-tax <Link href="/singapore-economy" className="text-[#0066cc] hover:underline">Singapore</Link> have both achieved prosperity.</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><caption className="sr-only">Tax revenue by country. Source: World Bank.</caption><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">Tax (% GDP)</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/tax-revenue`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]">{formatValue(d.value, 'percent', 1)}</td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/ranking/tax-revenue', label: 'Full Rankings' }, { href: '/debt-by-country', label: 'Government Debt' }, { href: '/gdp-per-capita-by-country', label: 'GDP per Capita' }, { href: '/corruption-by-country', label: 'Corruption' }, { href: '/denmark-economy', label: 'Denmark Economy' }, { href: '/finland-economy', label: 'Finland Economy' }, { href: '/singapore-economy', label: 'Singapore Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
