import type { Metadata } from 'next';
import Link from 'next/link';
import { getIndicatorForAllCountries, formatValue } from '@/lib/data';
import { getCleanCountryUrl } from '@/lib/country-slugs';
import Nav from '@/components/Nav';
import Footer from '@/components/Footer';
export const metadata: Metadata = { title: 'Birth Rate by Country 2026 — Crude Birth Rates Ranked', description: 'Birth rate by country: all countries ranked by crude birth rate per 1,000 people. From Niger (45+) to South Korea (<6). Source: World Bank / UN.', alternates: { canonical: 'https://statisticsoftheworld.com/birth-rate-by-country' } };
export default async function BirthRateByCountryPage() {
  const data = await getIndicatorForAllCountries('SP.DYN.CBRT.IN');
  const year = data[0]?.year || '2024';
  const avg = data.length > 0 ? data.reduce((s, d) => s + (d.value || 0), 0) / data.length : 0;
  const jsonLd = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Dataset', name: `Birth Rate by Country ${year}`, description: `Crude birth rate for ${data.length} countries. Global average: ${avg.toFixed(1)}/1000. Source: World Bank.`, url: 'https://statisticsoftheworld.com/birth-rate-by-country', creator: { '@type': 'Organization', name: 'World Bank' }, license: 'https://creativecommons.org/licenses/by/4.0/', dateModified: new Date().toISOString().split('T')[0] }, { '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: 'Which country has the highest birth rate?', acceptedAnswer: { '@type': 'Answer', text: `${data[0]?.country} has the highest birth rate at ${data[0]?.value ? Number(data[0].value).toFixed(1) : '—'} per 1,000 people. Sub-Saharan African countries dominate the top of the list due to high fertility rates and young populations.` } }] }] };
  return (
    <main className="min-h-screen"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><Nav />
      <section className="max-w-[1000px] mx-auto px-6 py-10">
        <nav aria-label="Breadcrumb" className="mb-4 text-sm text-gray-400"><Link href="/" className="hover:text-gray-600 transition">Home</Link><span className="mx-2">/</span><span className="text-gray-600">Birth Rate by Country</span></nav>
        <h1 className="text-[32px] font-bold text-[#0d1b2a] mb-2">Birth Rate by Country ({year})</h1>
        <p className="text-[15px] text-[#64748b] mb-6">{data.length} countries · Global avg: {avg.toFixed(1)}/1000 · Source: World Bank · Updated {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
        <div className="max-w-[800px] space-y-4 mb-10">
          <h2 className="text-[22px] font-bold text-[#0d1b2a]">Global Birth Rate Trends</h2>
          <p className="text-[15px] text-[#374151] leading-[1.8]">The crude birth rate measures births per 1,000 <Link href="/population-by-country" className="text-[#0066cc] hover:underline">population</Link> annually. High birth rates (30+) indicate young, rapidly growing populations concentrated in sub-Saharan Africa. Low rates (&lt;10) indicate aging societies — <Link href="/japan-economy" className="text-[#0066cc] hover:underline">Japan</Link>, <Link href="/south-korea-economy" className="text-[#0066cc] hover:underline">South Korea</Link>, and much of Europe face demographic decline. The global average has fallen from 36 in 1960 to about {avg.toFixed(0)} today. See also: <Link href="/fertility-rate-by-country" className="text-[#0066cc] hover:underline">fertility rate</Link>.</p>
        </div>
        <div className="mb-10"><div className="border border-[#d5dce6] rounded-xl overflow-hidden"><table className="w-full"><caption className="sr-only">Birth rate by country. Source: World Bank.</caption><thead><tr className="text-left text-[13px] text-[#94a3b8] border-b border-[#d5dce6] bg-[#f8f9fb]"><th scope="col" className="px-4 py-2.5 w-12">#</th><th scope="col" className="px-4 py-2.5">Country</th><th scope="col" className="px-4 py-2.5 text-right">Births/1000</th></tr></thead><tbody>{data.slice(0, 50).map((d, i) => (<tr key={d.countryId} className="border-b border-[#edf0f5] hover:bg-[#f8f9fb] transition"><td className="px-4 py-2.5 text-[#94a3b8]">{i + 1}</td><td className="px-4 py-2.5"><Link href={`${getCleanCountryUrl(d.countryId)}/birth-rate`} className="text-[#0066cc] hover:underline text-[14px]">{d.country}</Link></td><td className="px-4 py-2.5 text-right font-mono text-[14px]">{d.value ? Number(d.value).toFixed(1) : '—'}</td></tr>))}</tbody></table></div></div>
        <div className="border-t border-[#d5dce6] pt-8"><div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">{[{ href: '/fertility-rate-by-country', label: 'Fertility Rate' }, { href: '/population-by-country', label: 'Population' }, { href: '/death-rate-by-country', label: 'Death Rate' }, { href: '/life-expectancy-by-country', label: 'Life Expectancy' }, { href: '/most-populous-countries', label: 'Most Populous' }, { href: '/world-population', label: 'World Population' }, { href: '/ethiopia-economy', label: 'Ethiopia Economy' }, { href: '/world-economy', label: 'World Economy' }].map(l => (<Link key={l.href} href={l.href} className="px-3 py-2 bg-white border border-[#d5dce6] rounded-lg text-[13px] text-[#475569] hover:text-[#0d1b2a] hover:border-[#b0bdd0] transition text-center">{l.label} →</Link>))}</div></div>
      </section><Footer /></main>);
}
